import pickle


def loc_oberelsass():
    dict = {'Die Schlange im Jura': 'Jura', 'St Morands Ruhe': 'Altkirch', 'Der Käpellegeist': 'Heimersdorf',
            'Die Zwerge in der Wolfshöhle': 'Pfirt', 'Des Teufels Recht auf Pfirt': 'Pfirt',
            'Die Todtenprozession zu Luppach': 'Luppach', 'Die Galgenplatte': 'Alt-Pfirt',
            'Der Lachgeist im Haag': 'Alt-Pfirt', 'Der Geist Laxi im Biederthaler Schlosse': 'Biederthal',
            'Junker Schnabel': 'Hagenthal', 'Die Here von Köstlach': 'Köstlach', 'Das Herenschloß': 'Dürlinsdorf',
            'Der Schmied im Berge': 'Dürlinsdorf', 'Das versunkene Schloß Färis und der alte Graf': 'Mörnach',
            'Die Herdwible von Mörnach': 'Mörnach', 'Die Erbauung von Liebenstein': 'Liebsdorf',
            'Der schwarze Vogel von Liebenstein': 'Liebsdorf', 'Das Hündlein aus der wilden Jagd': 'Liebsdorf',
            'Der Hausgeist geht zur Kelte': 'Oberlarg', 'Die drei Spinnerinnen': 'Oberlarg',
            'Der Hexentanz auf der Kalmiser Weide': 'Oberlarg', 'Das gefundene Silbergeld bei Mörsberg': 'Oberlarg',
            'Der Mann mit dem Lapphute zu Oberlarg': 'Oberlarg', 'Die weiße Frau am Goldigberg': 'Langizen',
            'DasTotenpferd un dd ie Totenprozession zu Moos': 'Moos', 'Das Bildstöcklein bei Winkel': 'Winkel',
            'Das Altschloß bei Winkel': 'Winkel', 'Der Dornstrauch bei Neun-Eich': 'Lüzel',
            'Das Silberloch bei Lüzel': 'Lüzel', 'Die weiße Frau auf dem Küppele': 'Jufurt', 'Der Brißgyberg': 'Jufurt',
            'Versenkte Glocken': 'Brubach, Didenheim', 'Das Weingeigerlein von Brunstatt': 'Brunstatt',
            'Das schwarze Tier am Mühlbach': 'Brunstatt', 'Die Gespensterheere im Nordfeld': 'Mülhausen',
            'Kreuzregen': 'Mülhausen', 'Himmelschweiß': 'Mülhausen', 'Der Schapgräber am Davidsbrünnlein': 'Mülhausen',
            'Die weiße Frau in grünen Pantoffeln': 'Mülhausen', 'Der verlorene Bräutigam': 'Mülhausen',
            'Der Milchsuppenacker': 'Mülhausen',
            'Die Henne mit den goldenen Eiern in der St. Marykapelle bei Riedesheim': 'Riedesheim',
            'Das Dorftier zu Hegenheim': 'Hegenheim bei Hüningen', 'Die Geisterkirche auf dem Rhein': 'Kembs, Niffer',
            'Der weiße Mann vom Julzacher Schlosse': 'Julzach', 'Die weiße Jungfrau am Weiher': 'Julzach',
            'Die weißen Mädchen an der Lindlache': 'Julzach', 'Der schwarze Mann am Rain': 'Julzach',
            'Die Erscheinung am Rain': 'Julzach', 'Das weiße Pferd': 'Julzach', 'Der Pferdeschatten am Rain': 'Julzach',
            'Der Nachtjäger': 'Julzach', 'Das Tucherle am Viertelssteg': 'Julzach', 'Das Doggele': 'Julzach',
            'Das Fronfastentier': 'Julzach', 'Der Dorfejel': 'Julzach', 'Der Milchbrunnen': 'Julzach',
            'Maria in der Eich': 'Rülisheim', 'Masmünsters Entstehung': 'Masmünster',
            'Der Lachtelweiher': 'Kirchberg bei Masmünster', 'Das Muttergottesbild in Sewen': 'Sewen',
            'Das Dambürle im Masmünsterthale': 'Masmünsterthal',
            'Die weiße Dame von Rothenberg': 'Rothenberg (Rougemont)', 'Die Gründung von Neu-Thann': 'Thann',
            'StTheobaldus rettet Thann im Schwedenkriege': 'Thann', 'Das Ex Voto in der Kirche zu Alt- Thann': 'Thann',
            'Die gebannten Kriegsheere': 'Sennheim', 'Kaiser Barbarossa unter dem Bibelstein': 'Sennheim',
            'Der Freier auf Freundstein': 'Weile br ei Thann', 'Die Feldmesser auf dem Belchen': 'Großer Belchen',
            'Gespenstertiere im Belchensee': 'Großer Belchen', 'Wie Gebweiler gerettet wurde': 'Gebweiler',
            'Des Fürsten zu Murbach jäher Tod': 'Gebweiler', 'Der Teufel auf Hugstein': 'Gebweiler',
            'Kunigunde von Hungerstein': 'Gebweiler', 'Der Schlangenkönig vom Heißenstein': 'Gebweiler',
            'Die schwarze Frau am Heißenstein': 'Gebweiler', 'Die Alte auf der Barnabasbrücke': 'Gebweiler',
            'Der wundersame Käfer': 'Bühl bei Gebweiler', 'Die Glocke von Bühl': 'Bühl bei Gebweiler',
            'Die singende Jungfrau im Lauchthal': 'Bühl bei Gebweiler',
            'Die Erscheinung auf der Melkerei Hofrieth': 'Bühl bei Gebweiler',
            'Ritter Kurt und die Kapelle von Ungersheim': 'Ungersheim', 'St Maria im Schäferthal': 'Sulzmatt',
            'Der Langenstein bei Sulzmatt': 'Sulzmatt', 'DieStiftung des Klosters St. Valentin zu Rufach': 'Rufach',
            'St Landolins Gut zu Rufach': 'Rufach', 'Die Weiber von Rufach': 'Rufach',
            'Das Hungertuch in der Kirche von Rufach': 'Rufach', 'Der Rufacher Galgen': 'Rufach',
            'Dem Teufel zu': 'Rufach', 'Der Bollenberg': 'Rufach', 'Die Wallfahrt Schauenberg': 'Geberschweier',
            'Die Greifenklaue des heiligen Imerius': 'Geberschweier', 'Bischof Friedrich von Zeringen': 'Geberschweier',
            'Stiftung des Klosters Marbach': 'Geberschweier', 'Graf Hugos Buße': 'Egisheim',
            'Bruno von Egisheim': 'Egisheim', 'Die Erscheinung in Pfeffels Garten': 'Colmar',
            'Die Erscheinung im Waschhause': 'Colmar', 'Die gespenstige Milchfrau': 'Colmar', 'Das Nachtkalb': 'Colmar',
            'Warum die Colmarer Knöpfler heißen': 'Colmar', 'Die Kornmutter': 'Heiligkreuz bei Colmar',
            'Frau Faste': 'Heiligkreuz bei Colmar', 'Die wilde Jagd bei Heiligkreuz': 'Heiligkreuz bei Colmar',
            'Der Hexenzug in der Hardt': 'Hettenschlag bei Neubreisach',
            'Das Bruderhäuschen bei Widensolen': 'Widensolen bei Neubreisach', 'Der Riese im Kastenwald': 'Andolsheim',
            'Warum der Logelbach zur Gemeinde Winzenheim gehört': 'Logelbach bei Colmar',
            'Die weiße Frau von Pflixburg': 'Winzenheim',
            'Die Wallfahrt zum Waldbruderkreuz am Grabe des heiligen Ignatius': 'Zimmerbach',
            'Die Entstehung des Bades Sulzbach 84B': 'Sulzbach', 'Die Zwerge auf dem Kerbholz': 'Sulzern',
            'Die Schrägmännel': 'Sulzern', 'Der grüne See im Münsterthale': 'Sulzern',
            'Der Soldatenschlatten am Hoheneck': 'Sulzern', 'Der goldene Wagen': 'Mezeral',
            'Der Alte vom Berge': 'Weier im Thale', 'Die Wallfahrt Dreien Aehren': 'Drei Aehren',
            'Das Muttergottesbild zu Dreien Aehren': 'Drei Aehren', 'Das Riesengrab auf dem Hohnack': 'Drei Aehren',
            'Das weiße Mädchen an der Fecht': 'Ingersheim', 'Der Geist im Ingersheimer Schlosse': 'Ingersheim',
            'Die Wöchnerin': 'Ingersheim', 'Der Hungerbrunnen': 'Ingersheim', 'St Deodat': 'Ammerschweier',
            'Die Bilder der Muttergottes und des Evangelisten St. Johannes vergießen Thränen': 'Kienzheim',
            'Kaiser Friedrich Barbarossa in Kaysersberg': 'Kaysersberg',
            'Die riesenmäßigen Holzschuhe auf dem Rathause zu Kaysersberg': 'Kaysersberg', 'Der Flieger': 'Kaysersberg',
            'Die Teufelskutsche': 'Kaysersberg', 'Die Tschäpläre': 'Kaysersberg',
            'Das Pestkreuz bei Kaysersberg': 'Kaysersberg', 'Der feurige Kreis im Kaysersberger Wald': 'Kaysersberg',
            'Der Einsiedler von Alspach': 'Alspach bei Kaysersberg', 'Der weiße See': 'Urbeis (Orbey)',
            'Der Zellenberger Burgersmann': 'Reichenweier', 'Die heilige Huna': 'Hunaweier',
            'Das Wappen der Grafen von Rappoltstein': 'Rappoltsweiler', 'Die Brüder von Rappoltstein': 'Rappoltsweiler',
            'Die Jungfrau auf St. Ulric h': 'Rappoltsweiler', 'Die drei Schwestern von Rappoltstein': 'Rappoltsweiler',
            "Herni's Kreuz": 'Rappoltsweiler', 'Das Silberglöcklein und die Schloßhunde': 'Rappoltsweiler',
            'Die Gespensterkutsche von Hoh- Rappoltstein': 'Rappoltsweiler',
            'Der Höllenhaken bei Rappoltsweiler': 'Rappoltsweiler', 'Der Hirzsprung': 'Rappoltsweiler',
            'Die Gründung von Dreikirchen oder Dusenbach': 'Rappoltsweiler',
            'Die gespenstige Herde': 'Elsenheim u Jllhäusern', 'Das Dorf Tannenkirch': 'Lanneukirch',
            'Das Dorftier von Tannenkirch': 'Lanneukirch', 'Die Here von Tannenkirch': 'Lanneukirch',
            'Das gelbe Fräulein auf der Hohkönigsburg': 'Hohlönigsburg bei Tannenkirch',
            'Die silberne Rose': 'Markirch', 'Warum die Markircher Silberminen Nichts mehr abwerfen': 'Markirch',
            'Der Jungfrauenplaß bei Markirch': 'Markirch', 'Die Glocke von Leberau': 'Leberau',
            'Der Charlemont': 'Leberau'}

    locs = []
    for key in dict:
        locs.append(dict[key])
    print(locs)
    with open("ner_sagen/oberelsass_sagen.pkl", "wb") as f:
        pickle.dump(locs, f)


def loc_unterelsass():
    dict = {'Schlettstadts Ursprung': 'Schlettstadt', 'Die Kirche und das Kloster St. Fides': 'Schlettstadt',
            'Der Schimmelreiter bei Schlettstadt': 'Schlettstadt', 'Die Glocke von Kestenholz': 'Restenholz',
            'Die drei Kröten in Chlodwigs Wappenschild': 'Frankenburg',
            'Die heilige Odilia in Scherweiler': 'Scherweiler',
            'Hans Mary von Eckwersheim': 'Schloß Bilstein bei Urbeis',
            'Hans Mary v Eckwersheim u Anton v Wilsperg': 'Dambachu Bernstein', 'Die treue Gattin': 'Ebersmünster',
            'Der Sturm auf dem Rheine': 'Markolsheim',
            'Das Muttergottesbild in Neunkirchen': 'Neunkirchen bei Friesenheim',
            'Das versunkene Kloster zu Rheinau': 'Rheinau', 'Das weiße Pferd bei Roßfeld': 'Roßfeld',
            'Königsherberg': 'Roßfeld', 'Das Queermännel': 'Sermersheim', 'Der Stubenhanzel von Benfeld': 'Benfeld',
            'Der Heidengott von Ehl': 'Ehl bei Benfeld',
            'Die Legende des h Maternus, Apostels des Elsaßes': 'Ehl bei Benfeld',
            'Doktor Faust in Sand': 'Sand bei Benfeld',
            'Der schwarze Klaus bei Westhausen': 'Westhausen bei Benfeld',
            'Wie der Name der Edeln von Maßenheim seinen Ursprung dem Wirthshaus zu verdanken habe': 'Magenheim',
            'Die Gräfin von Geroldseck und Schwanau': 'Gerstheim', 'Die weiße Frau von Schwanau': 'Gerstheim',
            'Der Wirelesweg': 'Gerstheim', 'Die Hülfe der Todten': 'Osthausen',
            'Die Geistermesse in Erstein': 'Erstein', 'Maria zur Eich': 'Plobsheim', 'Das Kloster Eschau': 'Eschau',
            'Der Kranzen von Geispolsheim Wappenschild': 'Geispolsheim', 'Der gespenstige Feldmesser': 'Stoßheim',
            'Der Ungersberg': 'Ungersberg bei Andlau',
            'Der Fahnenstein auf dem Ungersberg': 'Ungersberg bei Andlau',
            'St Richardis, Kaiserin, Stifterin der Abtei Ardlau': 'Andlau',
            'Die Bären in der Kirche von Andlau': 'Andlau',
            'Der Müllerbursche und das Fräulein von Hoh-Andlau': 'Andlau', 'Die Wepfermänner': 'Barr',
            'Das Rothkäppel': 'Barr', 'Die Erscheinung auf dem Speicher': 'Barr',
            'Wie der Teufel das Städtlein Barr nicht hergeben kann': 'Barr', 'Der Hungerbrunnen': 'Heiligenstein',
            'Ein Hexenmahl bei Heiligenstein': 'Heiligenstein', 'Der Bocksfelsen': 'St Nabor',
            'Frreführendes Licht': 'St Nabor', 'Der Jägerpfad bei Ottrott': 'Ottrott',
            'Die Legende der heilg Odilia, Patronin des Elsaßes': 'Odilienberg',
            'Das heilige Kreuz in Niedermünster': 'Odilienberg',
            'Die unterirdischen Höhlen im Hagelschlosse': 'Odilienberg', 'Der Männelstein': 'Odilienberg',
            'Die Geister auf dem Hochfeld': 'Hochfeld', 'Der wilde Jäger': 'Hochfeld',
            'Die Kirche zu St. Peter und Paul in Rosheim': 'Rosheim',
            'Engel behüten die Kirche vor der Wuth der Mansfeldischen Truppen': 'Rosheim',
            'Die Rosheimer Glocke': 'Rosheim', 'Die Geisterkutsche': 'Rosheim',
            'Der Stadtschreiber von Rosheim': 'Rosheim', 'Die Geijenkapelle auf dem Glöckelsberg': 'Innenheim',
            'Das Muttergottesbild zu Rosenweiler': 'Rosenweiler', 'Das Teufelsgebirge': 'Laubenheim',
            'Die St. Valentinskapelle im Schloß Girbaden': 'Girbaden', 'Der lustige Vogt auf Girbaden': 'Girbaden',
            'Die Belagerung von Girbaden': 'Girbaden', 'Die Gerichtsnacht auf Girbaden': 'Girbaden',
            'Der Feengarten und die Feenbrücken': 'Lüzelhausen', 'Der Riese auf dem Nollen': 'Lüzelhausen',
            'Schabsagen von Salm': 'Salm bei Rothau', 'Die Regenfrau von Salm': 'Salm bei Rothau',
            'Die Jungfrau auf dem Urstein': 'Urstein', 'Der Lottelfelsen auf dem Schneeberge': 'Schneeberg',
            'Der gespenstige Förster am Schneeberge': 'Schneeberg', 'Die Riesentochter von Nideck': 'Nideck',
            'St Florentius': 'Oberhaslach', 'Das Grab der heilg Petronilla': 'Avolsheim',
            'Die Kapelle St. Armuth  3:#*': 'Dachstein', 'Die Entstehung des Sulzbades': 'Sulzbad',
            'Der feurige Mann': 'Balbronn', 'Der Rohracker': 'Westhofen', 'Die weißen Kazen': 'Wangen',
            'Der Dorfhammel': 'Wangen', 'Das Weinbrünnlein': 'Wangen',
            'Der König Dagobert und Neu-Troja': 'Kirchheim',
            'Die weißen Schafe': 'Marlenheim', 'Das Marienbild in der Kapelle zu Marlenheim': 'Marlenheim',
            'Die Spukthiere im Kronthal': 'Marlenheim',
            'Woher die Redensart kommt : „Benz unten, Benz oben"': 'Kochersberg',
            'Die St. Ulrichsquelle bei Avenheim': 'Kochersberg', 'Der Drescher von Rohr': 'Kochersberg',
            'Trenks Manteljack': 'Kochersberg', 'Das Mittagläuten in den Törfern des Kochersbergs': 'Kochersberg',
            'St Autors Brünnlein in Maursmünster': 'Maursmünster', 'Die Spille und die Kunkel': 'Dagsburger Land',
            'Der gedeckte Markstein': 'Dagsburger Land', 'Die Gespensterwiese bei der Hub': 'Dagsburger Land',
            'Der Todtenkopffelsen bei der Hub': 'Dagsburger Land',
            'Die weißen Jungfrauen bei Haselburg ≤': 'Dagsburger Land',
            'Die Belagerten im Schloß Dagsburg ≤': 'Dagsburger Land',
            'Das Dorfthier von Dagsburg': 'Dagsburger Land',
            'Der Ferrenfelsen bei Dagsburg': 'Dagsburger Land', 'Das graue Männlein von Altdorf': 'Dagsburger Land',
            'Gespenster auf dem Martelberge': 'Dagsburger Land', 'Dreiheiligen': 'Dagsburger Land',
            'Schatz auf dem Hohwalsch': 'Dagsburger Land', 'Feurige Männer bei Walscheid': 'Walscheid',
            'Die goldverwandelten Baumblätter': 'Walscheid', 'Die Schaßgräber auf St. Leon': 'Walscheid',
            'Fremde schaßgräber auf St. Leon': 'Walscheid',
            'Bestrafter Uebermuth': 'Alberschweiler und die saarthäler',
            'Der Geldfelsen': 'Alberschweiler und die saarthäler',
            'Der Lottelfelsen auf dem Nonnenberg': 'Alberschweiler und die saarthäler',
            'Der Gespensterfelsen bei soldatenthal': 'Alberschweiler und die saarthäler',
            'St Quirins Stuhl': 'Alberschweiler und die saarthäler',
            'Der sac de pierre>': 'Alberschweiler und die saarthäler', 'Die Gräfin von Lüzelburg': 'Lüzelburg',
            'Die Jungfrau von Lüzelburg': 'Lüzelburg', 'Der Pfaff von Garburg': 'Garburg',
            'Die Steinbütte': 'Zabern',
            'Der Brotschgeist': 'Zabern', 'Ein Müllerknecht wird in einen Esel verwandelt': 'Zabern',
            'Die gebannten Helden im Schloß Groß- Geroldseck': 'Zabern',
            'Chronik- Sage von den Schlössern Groß- Geroldseck und Lüzelhart': 'Zabern',
            'Der Brudermörder': 'Zabern',
            'Die Horn-Bruderschaft auf Hoh-Barr': 'Zabern', 'Die Panduren auf Hoh- Barr': 'Zabern',
            'Der St. Veits Tanz': 'Zabern', 'Die Dame von Greifenstein': 'Zabern', 'Der Karlssprung': 'Zabern',
            'Das Muttergottesbild in Monsweiler': 'Monsweiler',
            'Die redenden Bilder Christi und Mariä': 'St Johann',
            'Die Herenschule': 'St Johann', 'Das Forsthaus Oberhof': 'Oberhof bei Zabern',
            'Die Diebesschelle': 'Oberhof bei Zabern', 'Entweihe das Brod nicht !': 'Dettweiler',
            'Der spukende Mönch bei der Kirche von Bischheim': 'Bischheim',
            'Stiftung des Klosters Stephansfeld bei Brumath': 'Brumath',
            'Störe die Ruhe der Todten nicht !': 'Mommenheim', 'Die Klos-Kapelle': 'Ohlungen',
            'Das Schellenmännlein von Ettendorf': 'Ettendorf', 'Die Gespensterkutsche 1': 'Zöbersdorf',
            'Der Riegersche Garten': 'Zöbersdorf', 'Das Gänsbrückel': 'Bosselshausen',
            'Die Gespensterkutsche 2': 'Kirrweiler', 'Die gespenstigen Kinder im Dunzenbruch': 'Obermodern',
            'Die wilde Jagd im Moderer Wald': 'Obermodern', 'Die schwarze Kuh von Obermodern': 'Obermodern',
            'Historie von der schönen, aber bösen Bärbel': 'Buchsweiler',
            'Der Bildhauer Marderstecken': 'Buchsweiler',
            'Der Lure- Jerri': 'Buchsweiler', 'Warum es gewöhnlich am Buchsweiler Jahrmarkte regnet': 'Buchsweiler',
            'Das Stadtkalb und das Lezel': 'Buchsweiler', 'Gespensterthiere im Freihof': 'Buchsweiler',
            'Der Bäckerbursche in der Herrengasse': 'Buchsweiler', 'Der Spuk im Keller': 'Buchsweiler',
            'Die Here als Pferd': 'Buchsweiler', 'Die Here als Ente': 'Buchsweiler',
            'Die spinnenden Heren': 'Buchsweiler', 'Herenbann, wenn das Vieh veruntreut ist': 'Buchsweiler',
            'Der Bastberg': 'Buchsweiler', 'Der Schulmeister als Spielmann bei der Herenrunde': 'Buchsweiler',
            'Der Spielmann auf dem Bastberg': 'Buchsweiler', 'Der Geist im Kissel': 'Buchsweiler',
            'Der feurige Drache in Riedheim': 'Riedheim', 'Das Adelphusbrünnlein bei Neuweiler': 'Neuweiler',
            'Die weiße Jungfrau von der Hünenburg': 'Neuweiler', 'Der Geigerstein': 'Neuweiler',
            'Ueberfall der Veste Lüzelstein': 'Lüzelstein', 'Das weiße Fräulein vom Druttwald': 'Ottweiler',
            'Die angehaltenen Fruchtwagen': 'Ottweiler', 'Der gespenstige Schimmel': 'Aßweiler',
            'Die Fahrt auf dem Ziegenbock': 'Aßweiler', 'Der fliegende Hase': 'Aßweiler',
            'Das schwarze Hündlein': 'Aßweiler', 'Die Kornmutter': 'Drulingen',
            'Die Hunde auf dem Brücklein': 'Drulingen', 'Der Fluch des Jesuiten': 'Hirschland',
            'Berg und Thal': 'Berg und Thal', 'Die 11 Heilwog" in der Neujahrsnacht': 'Durstel',
            'Die geraubte Braut': 'Durstel', 'Der Tiefenbacher Wald': 'Tiefenbach',
            'Die versunkene Stadt': 'Volksberg',
            'Der Spigstein und der Breitenstein': 'Volksberg', 'Der wilde Jäger bei Waldhambach': 'Volksberg',
            'Herr von Bokisch und sein Schwan': 'Diemeringen',
            'Die kristallene Salzfee zu Diemeringen': 'Diemeringen',
            '„Der Hopp kommt!"': 'Diemeringen', 'Das weiße Fräulein von Diemeringen': 'Diemeringen',
            'Der leßte Graf von Saarwerden und die Fee': 'Saarwerden',
            'Der Bettag in der Grafschaft Hanau- Saarwerden': 'Saarwerden', 'Der unbequeme Mitbürger': 'Saarunion',
            'Die Here von Heimeldingen': 'Saarunion', 'Der Mann im Lapphut bei Lorenzen': 'Lorenzen',
            'Die Brücke von Herbißheim': 'Herbißheim', 'Der Graf von Engelweiler und die Fee': 'Engelweiler',
            'Der Schatz in der Helferei': 'Ingweiler', 'Das Ingweiler Stadtkalb': 'Ingweiler',
            'Das Frrkraut': 'Ingweiler', 'Das Haberkreuz bei Neuenburg': 'Neuenburg bei Hagenau',
            '"Wie die Burg und die Stadt Hagenau erhaben und gemacht worden"': 'Hagenau',
            'Kaiser Barbarossa ist in der Burg zu Hagenau lebendig verzückt worden': 'Hagenau',
            'Der Statthalter von Hagenau': 'Hagenau', 'Die Blaulichtlein': 'Hagenau',
            'Der verzückte Mönch': 'Biblisheim', 'Der dreibeinige Hase': 'Mietesheim',
            'Die Gloshecke': 'Mietesheim',
            'Das Geisterhecr bei der Gloshecke': 'Mietesheim', 'Der Mann ohne Kopf auf dem Schimmel': 'Mietesheim',
            'Der alte Krähn': 'Mietesheim', 'Das Mädchen von Engweiler': 'Engweiler',
            'Der Erzknappe von Uhrweiler': 'Uhrweiler', 'Helf Dir Gott!': 'Gumbrechtshofen',
            'Der Teufelshafer': 'Offweiler', 'Sagen vom Selhof bei Rothbach': 'Rothbach',
            'Bruderrache': 'Lichtenberg',
            'Lichter auf Hellebarden': 'Lichtenberg', 'Graf Jakob von Lichtenberg': 'Lichtenberg',
            'Graf Jakob von Lichtenberg der Zauberkundige': 'Lichtenberg',
            'Graf Jakob von Lichtenberg und der Franzose': 'Lichtenberg', 'Der starke Beilstein': 'Lichtenberg',
            'Graf Ludwig von Lichtenberg und der Roßtäuscher': 'Lichtenberg',
            'Graf Ludwig von Lichtenberg und der Kaufmann': 'Lichtenberg',
            'Graf Ludwig von Lichtenberg verschafft sich ein Nachtquartier': 'Lichtenberg',
            'Der Kellermeister von Arnsburg': 'Arnsberg bei Bärenthal',
            'Die Ritter auf Arneburg': 'Arnsberg bei Bärenthal',
            'Der Küfer von Falkenstein': 'Falkenstein bei Philippsburg',
            'Der Glockenfelsen bei Stürzelbronn': 'Stürzelbronn bei Bitsch',
            'Des Herzogs Hand': 'Stürzelbronn bei Bitsch', 'Die Gräfin von Bitsch': 'Bitsch',
            'Kühner Sprung': 'Eppenbrunn bei Bitsch', 'Der Bickelstein': 'Oberbronn',
            'Die weiße Frau an der Waschbach': 'Oberbronn', 'Der „Heilebrunnen“': 'Oberbronn',
            'Die lüsterne Here': 'Oberbronn', 'Die Kappe auf einem Ohr': 'Oberbronn',
            'Die Burgfrau auf Alt-Winstein': 'Alt- und Neu-Winstein im Jägerthal',
            'Die Belagerung von Neu-Winstein': 'Alt- und Neu-Winstein im Jägerthal',
            'Die goldenen Kegel auf Neu- Winstein': 'Alt- und Neu-Winstein im Jägerthal',
            'Die drei Schaßgräber im Jägerthale': 'Alt- und Neu-Winstein im Jägerthal',
            'Jrrführende Geister': 'Fröschweiler', 'Der erlöste Todte': 'Wörth a d sauer',
            'Der gespenstige Förster': 'Hatten', 'Der Geisenmajor': 'Beinheim',
            'Die Wallfahrt Unsrer Lieben Frauen zur Eich in Görsdorf': 'Görsdorf',
            'Der Kampf der Helden auf dem Wasgenstein': 'Wasigenstein', 'Der Maidebrunn': 'Hohenburg',
            'Der Krötenstuhl': 'Hohenburg', 'Der Lindenschmidt': 'Löwenstein', 'Hans Trapp': 'Bärbelstein',
            'Weißenburger Stadtgespenster': 'Weißenburg', 'Gespensterheer bei Weißenburg': 'Weißenburg',
            'Das Lezekäppel': 'Weißenburg',
            'Ursprung der Redensart : „Zu Weißenburg, wo man den Bumpernickel in der Kirche singt"': 'Weißenburg',
            'Sebastian Vogelsperger und Lazarus schwendi': 'Weißenburg',
            'Das Mädchen vom Pauliner Schlößchen': 'Weißenburg',
            'Die weiße Dame vom Pauliner Schlößchen': 'Weißenburg',
            'Der schwarze Hund und die unterirdischen Schäße im Pauliner Schlößchen': 'Weißenburg',
            'In Goldstücke verwandelte Porzellanscherben': 'Weißenburg',
            'Die Wäsche im Pauliner Schlößchen': 'Weißenburg',
            'Das Feldgewann Goldhaus bei Weißenburg': 'Weißenburg',
            'Straßburgs Stadtwappen': 'Straßburg', 'Eine alte Weissagung von Straßburg': 'Straßburg',
            'St Arbogast, Bischof von Straßburg': 'Straßburg', 'St Arbogast und der Sohn der Wittwe': 'Straßburg',
            'Die heilige Attala': 'Straßburg', 'Bischof Wilderolf wird von den Mäusen gefressen': 'Straßburg',
            'Bischof Ottos IV Gesicht': 'Straßburg', 'Des Ammeisters Sohn': 'Straßburg',
            'Der Marschall von Hünenburg und die Stiftung von St. Johann zum grünen Wörd': 'Straßburg',
            'Der Kinder Kreuzzug': 'Straßburg', 'Der tödtliche Sprung': 'Straßburg',
            'Die Wunderthaten der Geißler': 'Straßburg',
            'Die Sage von dem Ursprunge der beiden Ammeistergeschlechter der Barpfenning und der Leimer in Straßburg': 'Straßburg',
            'Kaiser Sigismund und die Straßburger Edelfrauen': 'Straßburg',
            'Die Sage von den ersten Zigeunern, welche in das Elsaß und nach Straßburg kamen': 'Straßburg',
            'Hansens von Westhausen Geist erscheint auf dem Hohensteg': 'Straßburg',
            'Die Inschrift am ehemaligen Weißthurmthore': 'Straßburg',
            'Die Erfindung der Buchdruckerkunst': 'Straßburg',
            'Der Bäckerknechte Zug nach Wasselnheim': 'Straßburg',
            'Warum die Straßburger Meisenlocker heißen': 'Straßburg',
            'Das Männlein am Katharinenthurm': 'Straßburg',
            'Die Hunde in der großen Kirchgasse': 'Straßburg', 'Straßburger Wahrzeichen': 'Straßburg',
            'Ein straßburger Wahrzeichen': 'Straßburg', 'Finkweiler Gespenster': 'Straßburg',
            'Der Geist zu St. Mary': 'Straßburg', 'Das Wüthenheer in der Weißthurmstraße': 'Straßburg',
            'Die Nonne von St. Klara': 'Straßburg',
            'Das Milchweibchen, das Loßmännel und der Flozemann in der Steinstraße': 'Straßburg',
            'Das Armjünderhaus in Straßburg': 'Straßburg', 'Das rothe Männel': 'Straßburg',
            'Kaiser Napoleon lebt noch': 'Straßburg', 'Die reiche Jungfrau mit dem Todtenkopf': 'Straßburg',
            'Das Wellenmännel im Mond': 'Straßburg', 'Das Donnerloch bei Straßburg': 'Straßburg',
            'Eisenbahnsagen': 'Straßburg', 'Der Wind auf dem straßburger Münsterplay': 'Straßburg',
            'Ein schaßfindender Venediger': 'Straßburg',
            'Die Glock ze u Haueneberstein und id e Straßburger': 'Straßburg',
            'Der heilige Hain und die drei Buchen': 'Straßburger Münster',
            'Der Bronnen im Münster': 'Straßburger Münster',
            'Das Gewölbe und der See unter dem Münster': 'Straßburger Münster',
            'Chlodwigs Taufe und die Stiftung des Münsters': 'Straßburger Münster',
            'Die Stiftung der Chorkönigspfründe': 'Straßburger Münster', 'Der Fronhof': 'Straßburger Münster',
            'Die drei steinernen Reiter am Münster': 'Straßburger Münster',
            'Das Reiterlein an der Säule': 'Straßburger Münster', 'Das Horn an der Säule': 'Straßburger Münster',
            'Die beiden Arbeiter': 'Straßburger Münster', 'Sabina': 'Straßburger Münster',
            'Das heilige Grab': 'Straßburger Münster', 'Das Grüselhorn" und der „Judenblos"': 'Straßburger Münster',
            'Des "Roraffen" und des Hahnen Streit': 'Straßburger Münster',
            'Das Einhorn und Herr Rudolf von Schauenburg': 'Straßburger Münster',
            'Der Werkmeister am Thurme': 'Straßburger Münster', 'Der Kaiser und der Mönch': 'Straßburger Münster',
            'Das traurige, kreuztragende Christusbild': 'Straßburger Münster',
            'Das Männlein oder Bäuerlein auf dem Geländer bei der Engelsäule': 'Straßburger Münster',
            'Das Uhrwerk im Münster': 'Straßburger Münster',
            'Der singende Knabe auf der Uhr': 'Straßburger Münster',
            'Der fremde Kavalier und sein Hund': 'Straßburger Münster',
            'Die Johannisnacht im Münster': 'Straßburger Münster'}
    locs = []
    for key in dict:
        locs.append(dict[key])
    print(locs)
    with open("ner_sagen/unterelsass_sagen.pkl", "wb") as f:
        pickle.dump(locs, f)


def loc_pfalz():
    locs_dict = {1: ['Bad Dürkheim', 'Limburg', 'Neuleiningen'], 2: ['Kaiserslautern', 'Kaiserburg'], 3: ['Speyer'],
                 4: ['Bliesbolchen', 'Bliesmengen'], 5: ['Erfweiler'], 6: ['Sponheim'],
                 7: ['Donnersberg', 'Ruppertsecken', 'Stolzenberg', 'Würzweiler'],
                 8: ['Frankenthal', 'Hohenburg', 'Lindenschmidt', 'Löwenstein'], 9: ['Dernbach', 'Scharfeneck'],
                 10: ['Dernbach', 'Scharfeneck'], 11: ['Berwartstein', 'Niederschlettenbach', 'Weißenberg'],
                 12: ['Dannenfels', 'Donnersberg'], 13: ['Neustadt an der Haardt'], 14: ['Kaiserslautern'],
                 15: ['Medard a. Glan'], 16: ['Biedershausen', 'Winterbach', 'Zweibrücken'],
                 17: ['Rhodt', 'Rietburg', 'Villa Ludwigshöhe'], 18: ['Kottweiler', 'Mackenbach', 'Miesenbach'],
                 19: ['Münchweiler an der Alsenz', 'Schorlenberger Forsthaus'],
                 20: ['Finkenbach', 'Ransweiler', 'Schiersfeld', 'Waldgrehweiler'],
                 21: ['Klingenmünster', 'Schloßköpfel', 'Schlössel'], 22: ['Beilstein', 'Kaiserslautern'],
                 23: ['Meisenheim'], 24: [], 25: ['Homburg', 'Jägersburg'], 26: ['Jägersburg'],
                 27: ['Niederauerbach', 'Oberauerbach', 'Zweibrücken'], 28: ['Neustadt an der Haardt', 'Nonnental'],
                 29: ['Niederauerbach'], 30: ['Ensheim', 'Eschringen'], 31: ['Offenbach a. Glan', 'Wolfstein'],
                 32: ['Ensheim'], 33: ['Ehlingen', 'Erfweiler'],
                 34: ['Busenberg', 'Drachenfels bei Dahn', 'Jettenbach', 'Lichtenberg', 'Marienthal',
                      'Niederkirchen im Ostertal', 'Oberkirchen', 'Münster-Dreisen Kloster Ohmbach', 'Pfeffelbach',
                      'Remigiusberg', 'Seebach'], 35: ['Großer Stiefel', 'St. Ingbert', 'Saarbrücken', 'Sengscheid'],
                 36: ['Großer Stiefel', 'St. Ingbert'], 37: ['Pauliner Schlößchen', 'Schweigen'], 38: [],
                 39: ['Frohnerbacherhof', 'Kusel', 'Rathsweiler', 'Steinalb'], 40: ['Schweinschied'],
                 41: ['Kusel', 'Schwarzerden'], 42: ['Lindelbrunn'], 43: ['Ensheim'],
                 44: ['Bischmisheim', 'Ensheim', 'Wadgassen'], 45: ['Pirmasens'], 46: ['Huneberg', 'Schwanau'],
                 47: ['Rheingrafenstein'], 48: ['Hagenbach', 'Jockgrim', 'Schweinheim', 'Wörth a. Rhein'],
                 49: ['Harzofen', 'Kaiserslautern'], 50: ['Erzhütten', 'Kaiserslautern'],
                 51: ['Bad Dürkheim', 'Drachensels bei Dürkheim', 'Esthal', 'Lindenberg', 'Saupferch',
                      'Siegfriedsbrunnen'], 52: ['Buhlstein', 'Busenberg', 'Drachenfels bei Dahn', 'Lindelbrunn'],
                 53: ['Pirmasens'], 54: ['Friedrichsthal', 'Miesenbach', 'Völklingen'],
                 55: ['Königsberg bei Wolfstein', 'Wolfstein'], 56: ['Bliestal'], 57: ['Wasgenwald'], 58: ['Speyer'],
                 59: ['Großer Stiefel', 'St. Ingbert', 'Rentrisch'], 60: ['Buren'], 61: ['Rodenbach b. Kaisersl.'],
                 62: ['Wartenberg', 'Winnweiler', 'Worms'], 63: ['Kaiserslautern', 'Landstuhl'],
                 64: ['Donnersberg', 'Göcklingen', 'Landeck'], 65: ['Rheingrafenstein'],
                 66: ['Limburg', 'Teufelsstein'], 67: ['Dahn', 'Kaltenbach', 'Teufelstisch'],
                 68: ['Burrweiler', 'Gleisweiler', 'Teufelsberg', 'Weyher'],
                 69: ['Einöd', 'Teufelsborn oder Teufelsbrunnen', 'Zweibrücken'], 70: ['Kirchheim'],
                 71: ['Freilaubersheim', 'Münstertal', 'Niederhausen a. d. Appel', 'Wöllstein', 'Zotzenheim'],
                 72: ['Wolfstein'], 73: [], 74: ['Oggersheim'], 75: ['Sickinger Gegend'],
                 76: ['Niederlauterbach', 'Schaidt'], 77: ['Lindelbrunn'], 78: ['Erlenbach b. Dahn', 'Miesenbach'],
                 79: ['Erlenbach b. Dahn'], 80: ['Königsberg bei Neustadt a. H.', 'Neustadt an der Haardt'],
                 81: ['Donnersberg', 'Hanweilerhof', 'Klauser-Hütte'],
                 82: ['Blieskastel', 'Bliesmengen', 'Gräfinthalerhof', 'Gräfinthal'], 83: [],
                 84: ['Leinsweiler', 'Ranschbach'], 85: ['Speyer'], 86: ['Speyer'], 87: ['Speyer'],
                 88: ['Dörrenbach', 'Forst', 'Kolmerbergkapelle', 'Pauliner Schlößchen'],
                 89: ['Cyriakuskapelle', 'Lindenberg', 'Lindenfels'],
                 90: ['Cyriakuskapelle', 'Deidesheim', 'Lindenberg'],
                 91: ['Blieskastel', 'Ormesheim', 'Strutelpeterskapelle'],
                 92: ['Eschringen', 'Lorenzenborn', 'St. Lorenzkapelle'], 93: ['Niederhochstadt'],
                 94: ['Servatiusbrunnen', 'Speyer'], 95: ['Göllheim', 'Lorenzenbrunnen'],
                 96: ['Enkenbach', 'Kaiserslautern', 'Niefernheim', 'Zell', 'Zellertal'], 97: ['Speyer'],
                 98: ['Aschbach b. Kaiserslautern', 'Horbach', 'Kaiserslautern'],
                 99: ['Königsberg bei Neustadt a. H.', 'Neustadt an der Haardt', 'Nonnental', 'Wolfsburg'],
                 100: ['Colgenstein', 'Dirmstein', 'invesheim', 'Obrigheim', 'Offstein'],
                 101: ['Eschringen', 'St. Lorenzkapelle'],
                 102: ['Albersweiler', 'St. Johann bei Albersweiler', 'Landau', 'Ramsen'],
                 103: ['Albersweiler', 'Eußerthal'],
                 104: ['Altdahn', 'Busenberg', 'Drachenfels bei Dahn', 'Hohenburg', 'Maidenbrunnen', 'Stöckelgarten',
                       'Wegelnburg'], 105: ['Beilstein', 'Heiligenberg', 'Hochspeyer', 'Kaiserslautern'],
                 106: ['Enkenbach', 'Matzenberg'], 107: ['Karlstal', 'Wilenstein'],
                 108: ['Bayerfeld-Cölln', 'Bollesbrunnen', 'Diemerstein', 'Frankenstein', 'Rockenhausen', 'Stahlberg',
                       'Stolzenberg'], 109: ['Wachenheim', 'Wachtenburg'],
                 110: ['Disibodenberg', 'Meisenheim', 'Odernheim', 'Staudernheim'],
                 111: ['Donnersberg', 'Hohenfels', 'Imsbach'], 112: ['Kirchheimbolanden', 'Rotenkircherhof'],
                 113: ['Dernbach', 'Scharfeneck'],
                 114: ['Börsborn', 'Glanmünchweiler', 'Heidenburg bei Oberstaufenbach', 'Oberstausenbach'],
                 115: ['Heidenburg bei Oberstaufenbach', 'Oberstausenbach'],
                 116: ['Fleckenstein', 'Krötenstuhl', 'Nothweiler', 'Wegelnburg'], 117: ['Pirmasens'],
                 118: ['Großer Stiefel', 'St. Ingbert'], 119: ['Großer Stiefel', 'St. Ingbert'], 120: ['Kirkel'],
                 121: ['Kirkel'], 122: ['Pauliner Schlößchen', 'Weißenburg'], 123: ['Pauliner Schlößchen', 'Schweigen'],
                 124: ['Frankenstein', 'Leinbachmühle', 'Neidenfels'], 125: ['Altwolfstein', 'Wolfstein'],
                 126: ['Annweiler'], 127: ['Kaiserslautern', 'Morlautern'], 128: ['Erzenhausen', 'Miesenbach'],
                 129: ['Finkenbach'], 130: ['Bad Dürkheim', 'Heidenmauer'], 131: ['Kallbach', 'Unkenbach'],
                 132: ['Heidenburg bei Oberstaufenbach', 'Oberstausenbach'],
                 133: ['Göllheim', 'Hasenbühl', 'Rosenthal', 'Speyer'], 134: ['Lindelbrunn'],
                 135: ['Altleiningen', 'Battenburg', 'Dirmstein', 'Neuleiningen'],
                 136: ['Fischbach b. Hochspeyer', 'Hochspeyer'], 137: ['Frankenthal', 'Oggersheim'],
                 138: ['Donnersberg', 'Falkenstein', 'Mordkammer'], 139: ['St. Medard', 'Mutterstadt', 'Ruchheim'],
                 140: ['Körborn', 'Kusel', 'Lichtenberg', 'Lichtenburg'],
                 141: ['Frankenthal', 'Neustadt an der Haardt', 'Speyer', 'Worms'],
                 142: ['Landsberg', 'Lewenstein', 'Obermoschel'], 143: ['Beilstein', 'Kaiserslautern'],
                 144: ['Hochspeyer', 'Matzenberg'], 145: ['Löllbach'], 146: ['Odernheim'], 147: ['Speyer'],
                 148: ['Donnersberg', 'Falkenstein', 'Hochstein'], 149: ['Altenbaumberg', 'Neuenbamberg', 'Treuenfels'],
                 150: ['Ebernburg', 'Kreuznach', 'Lichtenburg', 'Montfort', 'Rheingrafenstein'],
                 151: ['Hartenburg', 'Limburg'], 152: ['Göllheim', 'Rosenthal', 'Speyer'],
                 153: ['Bergzabern', 'Berwartstein'], 154: ['Neustadt an der Haardt', 'Wolfsburg'],
                 155: ['Schwarzerden'], 156: ['Einsiedel', 'Kaiserslautern'], 157: ['Lichtenstein', 'Neidenfels'],
                 158: ['Bad Dürkheim', 'Kehrdichannichts', 'Murmelnichtviel', 'Schaudichnichtum'],
                 159: ['Diedelkopf', 'Kusel'], 160: ['Kreuznach'], 161: ['Disibodenberg'],
                 162: ['Blidenfeld', 'Klingenmünster', 'Landeck'], 163: ['Speyer'],
                 164: ['Göllheim', 'Grünstadt', 'Kerzenheim', 'Rosenthal'], 165: ['Rosentreppe', 'Zweibrücken'],
                 166: ['Otterstadt', 'Roßsprung', 'Speyer'], 167: ['Zeiskam'],
                 168: ['Disibodenberg', 'Lichtenburg', 'Limburg', 'Oberstein'],
                 169: ['Altheim', 'Hornbach', 'Medelsheim', 'Pirmasens'],
                 170: ['Dietrichskirchel', 'Rheinzabern', 'Rülzheim'],
                 171: ['Aschbach b. Kaiserslautern', 'Schmalenberg'],
                 172: ['Bosenbach', 'Friedelhausen', 'Wolfskirche'],
                 173: ['Falkenburg', 'Hauenstein', 'Wilgartswiesen'], 174: ['Bergzabern', 'Peternell'],
                 175: ['Dagobertshecke', 'Frankweiler', 'Godramstein', 'Göcklingen', 'Haingeraiden', 'Klingenmünster',
                       'Landeck', 'Mörzheim'], 176: ['Altenglan', 'Kusel'], 177: ['Winnweiler'],
                 178: ['Mannweiler', 'Randeck', 'Schiersfeld'], 179: ['Miesenbach', 'Schwedelbach'],
                 180: ['Niederlauterbach', 'Schaidt'], 181: ['Landstuhl'],
                 182: ['Abtstein', 'Fröhnerhof', 'Mehlingen', 'Otterberg'], 183: ['Vollmersweiler'],
                 184: ['Alschbach', 'Blieskastel', 'Gollenstein'], 185: ['Bad Dürkheim'],
                 186: ['Fischbach b. Schönau', 'Hohe List', 'Ludwigswinkel', 'Reitersprung'], 187: ['Eppenbrunn'],
                 188: ['Battenberg', 'Jungfernsprung b. Battenberg', 'Schaidt'],
                 189: ['Dahn', 'Jungfernsprung bei Dahn'], 190: ['Steinalb', 'Ulmet', 'Wolfsfels'],
                 191: ['Marienthal', 'Steinbach'], 192: ['Hartenburg', 'Nonnenfels'], 193: ['Offenbach a. Glan'],
                 194: ['St. Ingbert', 'Kirkel'], 195: ['Affolterloch', 'Wörth a. Rhein'],
                 196: ['Hohenburg', 'Maidenbrunnen', 'Wegelnburg'],
                 197: ['Karlsberg', 'Karlslust', 'Kirrberg', 'Reiterbrunnen', 'Zweibrücken'],
                 198: ['Neuwolfstein', 'Wolfstein'], 199: ['Edenkoben', 'Hoheberg', 'Rhodt'],
                 200: ['Battweiler', 'Einöd', 'Hornbach', 'Pirmansborn', 'Rinckweiler',
                       'Teufelsborn oder Teufelsbrunnen', 'Werckborn'],
                 201: ['Hungerbrunnen bei Kaiserslautern', 'Kaiserslautern'],
                 202: ['Donnersberg', 'Hohenfels', 'Silbergrube', 'Wolferstal'],
                 203: ['Donnersberg', 'Hohenfels', 'Langental'], 204: ['Drei Züge', 'Ebernburg', 'Feil', 'Lemberg'],
                 205: ['Bingert', 'Drei Züge', 'Ernesti-Glück', 'Hallgarten'],
                 206: ['Bingert', 'Feil', 'Geißkammer', 'Kreuznach', 'Lemberg'], 207: ['Wasgenstein', 'Worms'],
                 208: ['Kaiserslautern', 'Kaiserburg', 'Kaiserwoog'],
                 209: ['Hagenau', 'Kaiserslautern', 'Kaiserburg', 'Trifels'],
                 210: ['Kaiserslautern', 'Kaiserburg', 'Kaiserwoog'], 211: ['Beilstein', 'Kaiserslautern'],
                 212: ['Kaiserslautern'], 213: ['Speyer'], 214: ['Germersheim', 'Speyer'],
                 215: ['Böckelheim', 'Ruppertsberg'], 216: ['Hartenburg'], 217: ['Göllheim', 'Königskreuz'],
                 218: ['Tschifflick', 'Zweibrücken'], 219: ['Neudahn'], 220: ['Altenbaumberg', 'Kirkel', 'Zweibrücken'],
                 221: ['Altenbaumberg'], 222: ['Ebernburg', 'Landstuhl', 'Rotenfels'],
                 223: ['Ruppertsfelsen', 'Ruppertsweiler'], 224: ['Seebach'], 225: ['Marienstein', 'Zweibrücken'],
                 226: ['Böckelheim', 'Grehweiler', 'Montfort', 'Rheingrafenstein'], 227: ['Montfort', 'Ruppertsecken'],
                 228: ['Altenbaumberg'], 229: [], 230: ['Großer Stiefel', 'St. Ingbert'],
                 231: ['Enkenbach', 'Hoheneck'],
                 232: ['Aschbach b. Kaiserslautern', 'Maxburg', 'Trippstadt', 'Wilenstein'], 233: ['Speyer'],
                 234: ['Trifels'], 235: ['Sembach'], 236: ['Heimbach', 'Zeiskam'], 237: ['Altleiningen', 'Höningen'],
                 238: ['Ramberger Schloß', 'Scharfeneck'], 239: ['Erfenstein', 'Spangenberg'],
                 240: ['Erfenstein', 'Spangenberg'], 241: ['Montfort', 'Montforter Hof', 'Sponheim'],
                 242: ['Großer Stiefel', 'St. Ingbert', 'Rentrisch', 'Saarbrücken'], 243: ['Falkenstein'],
                 244: ['Spangenberg', 'Worms'],
                 245: ['Beckenhof', 'Hornbach', 'Lemberg', 'Mordloch', 'Pirmasens', 'Ruppertsfelsen', 'Ruppertsweiler'],
                 246: ['Lauterecken'], 247: ['Lingenfeld', 'Niederlnstadt', 'Westheim'],
                 248: ['Ballweiler', 'Blickweiler', 'Blieskastel', 'Mimbach', 'Wecklingerhof'], 249: ['Eußerthal'],
                 250: ['Eisenberg'], 251: ['Altdorf'], 252: ['Speyer'], 253: [],
                 254: ['Bad Dürkheim', 'Grethen', 'Landau'], 255: ['Landstuhl', 'Ramstein'], 256: ['Rosenberg'],
                 257: ['Konken', 'Niederkirchen im Ostertal', 'Oberkirchen', 'Ostertal', 'Saal', 'Wyrsweiler'],
                 258: ['Forst', 'Maxburg'], 259: ['Freckenfeld', 'Minfeld', 'Schaidt', 'Schweigen'],
                 260: ['Lug', 'Schwanheim', 'Sitters'], 261: [], 262: ['Sausenheim'], 263: ['Oppau'],
                 264: ['Friesenheim'], 265: ['Annweiler'], 266: ['Annweiler', 'Trifels'],
                 267: ['Alsenborn', 'Gartenhof', 'Hoher Bühl', 'Karlsberg', 'Nackterhof', 'Neuleiningen'],
                 268: ['Dreisen', 'Kirchheimbolanden', 'Münchweiler an der Alsenz', 'Standenbühl'], 269: ['Grumbach'],
                 270: ['Meisenheim'], 271: ['Hüffelsheim', 'Rheingrafenstein', 'Roxheim'],
                 272: ['Böckelheim', 'Disibodenberg', 'Grumbach', 'Sponheim'], 273: ['Limburg', 'Wachenheim'],
                 274: ['Neustadt an der Haardt'], 275: ['Neustadt an der Haardt'], 276: ['Iagelheim'],
                 277: ['Ebernburg'],
                 278: ['Bad Dürkheim', 'Iagelheim', 'Kirrweiler', 'Mußbach', 'Neustadt an der Haardt'], 279: [],
                 280: [], 281: [], 282: [], 283: []}
    locs = []
    for key in locs_dict:
        if locs_dict[key]:
            locs.append(locs_dict[key][0])
        else:
            locs.append("NaN")
    print(locs)
    with open("ner_sagen/pfalz_sagen.pkl", "wb") as f:
        pickle.dump(locs, f)
loc_pfalz()