def get_titles_trier_umgebung():
    titles = ["Das Bild der Stärke",
              "Arimaspes und Eptes",
              "Die Teufelskirche",
              "St. Simeon",
              "Betrachtung",
              "Das goldene Kalb",
              "Die Arena",
              "Der Frankenfürst",
              "Bestrafte Untreue",
              "Katholdis",
              "Der gespenstige Kaiser",
              "Das Ungeheuer",
              "St. Nicolas",
              "Das Verließ",
              "Constantius",
              "Helena",
              "Die Schwalben",
              "Der Krummelstuhl",
              "Das alte Trier",
              "Der Stadtgeist",
              "Trier's Wahrzeichen",
              "Das Trebeta-Bild auf dem Stadthause",
              "Der Engelberg",
              "Die Blume der Mägde",
              "Der mit der Elle gemessene Wein",
              "Das Marktkreuz",
              "Die Inschrift auf der Steipe",
              "Die Steine des Gymnasiums",
              "Coder aureus",
              "Sendung Rictiovar's nach Trier",
              "Einzug der Thebaischen Legion",
              "Das Kreuz",
              "Die vier Steine",
              "Das Deckengemälde der St. Paulinskirche",
              "Der Engel mit dem hölzernen Beine",
              "Cunnet's Tod",
              "Der Mohr",
              "Die Zauberstiefel",
              "Unverhoffte Rettung",
              "Die Hieronymus-Höhle",
              "Friedrich Spee",
              "Der eingemauerte Mönch",
              "Heiteres Leben",
              "Die Blume des Thales",
              "Najaden-Tänze",
              "Der Krondiamant",
              "Hommerspläßchen",
              "Ansicht",
              "Der Fremde und das Sandmädchen",
              "Das Mühlenthal",
              "Das Heinzemännchen",
              "Schlürfen",
              "Das Metzgerskreuzchen",
              "Sonnenaufgang",
              "Die Octave",
              "Das Glöcklein",
              "Der Wassersalamander",
              "In nomine domini",
              "Der letzte Stuart",
              "Der Helenabrunnen",
              "Der Steinbruch der Liebfrauenkirche",
              "Das Abschiedsdenkmal",
              "Der Todtenkopf-Mantel",
              "Der verborgene Keller",
              "Das gerettete Kind",
              "Medardin von Rottenfelt",
              "Alte Inschrift",
              "Der Matheiser Sauerbrunnen",
              "Die Forsthütte",
              "Siko",
              "Spaziergang",
              "Der Name Olewig",
              "Ländliche Bilder",
              "Sauere Milch",
              "Trebeta's Grab",
              "Sickingens Kanonenkugel",
              "Der Erdhügel",
              "Die Kreuzkapelle",
              "Das Marmorbett",
              "Der Hirtenknabe",
              "Der gekreuzigte Amor",
              "Die drei Helden",
              "Glimpf und Schimpf des Moselweins",
              "Betheuerungen eines Liebhabers",
              "Bemerkungen",
              "qwertz"
              ]

    return titles


def get_categories_trier_umgebung():
    categories = ["Die Porta nigra",
                  "Die Römischen Bäder",
                  "Römische Bäder",
                  "Das Amphitheater",
                  "Der Constantinische Palast",
                  "Das Neuthor",
                  "Die Moselbrücke",
                  "Der Dom",
                  "Der Domkreuzgang",
                  "Die Stadt Trier",
                  "Die Stadt Crier",
                  "Einzelheiten der Stadt Trier",
                  "St. Paulin",
                  "Nell's Ländchen",
                  "Pfalzel",
                  "Biewer",
                  "St. Marien",
                  "Zurlauben",
                  "Pallien",
                  "Das Weißhaus",
                  "Der Kockelsberg",
                  "Der Wasserfall",
                  "Kaffe Wettendorf",
                  "Der Pulsberg",
                  "Der Markusberg",
                  "Balduinshäuschen",
                  "Euren",
                  "Zewen",
                  "Igel",
                  "Conz",
                  "Karthause",  # og Index: Karthaufe
                  "St. Medard",
                  "St. Matheis",
                  "Heiligkreuz",
                  "Die Seufzerallee",
                  "Die Olewig",
                  "Das Franzenknöppchen",
                  "Castell an der Saar",
                  "Fliessem",  # og Index: Fließem
                  "Verschiedenes"
                  ]
    return categories


def get_dict_trier_umgebung():
    dict = {"Das Bild der Stärke": "Die Porta nigra",
            "Arimaspes und Eptes": "Die Porta nigra",
            "Die Teufelskirche": "Die Porta nigra",
            "St. Simeon": "Die Porta nigra",
            "Betrachtung": "Die Römischen Bäder",
            "Das goldene Kalb": "Die Römischen Bäder",
            "Die Arena": "Das Amphitheater",
            "Der Frankenfürst": "Das Amphitheater",
            "Bestrafte Untreue": "Das Amphitheater",
            "Katholdis": "Das Amphitheater",
            "Der gespenstige Kaiser": "Der Constantinische Palast",
            "Das Ungeheuer": "Das Neuthor",
            "St. Nicolas": "Die Moselbrücke",
            "Das Verließ": "Die Moselbrücke",
            "Constantius": "Der Dom",
            "Helena": "Der Dom",
            "Die Schwalben": "Der Dom",
            "Der Krummelstuhl": "Der Domkreuzgang",
            "Das alte Trier": "Die Stadt Trier",
            "Der Stadtgeist": "Die Stadt Trier",
            "Trier's Wahrzeichen": "Die Stadt Trier",
            "Das Trebeta-Bild auf dem Stadthause": "Einzelheiten der Stadt Trier",
            "Der Engelberg": "Einzelheiten der Stadt Trier",
            "Die Blume der Mägde": "Einzelheiten der Stadt Trier",
            "Der mit der Elle gemessene Wein": "Einzelheiten der Stadt Trier",
            "Das Marktkreuz": "Einzelheiten der Stadt Trier",
            "Die Inschrift auf der Steipe": "Einzelheiten der Stadt Trier",
            "Die Steine des Gymnasiums": "Einzelheiten der Stadt Trier",
            "Coder aureus": "Einzelheiten der Stadt Trier",
            "Sendung Rictiovar's nach Trier": "St. Paulin",
            "Einzug der Thebaischen Legion": "St. Paulin",
            "Das Kreuz": "St. Paulin",
            "Die vier Steine": "St. Paulin",
            "Das Deckengemälde der St. Paulinskirche": "St. Paulin",
            "Der Engel mit dem hölzernen Beine": "St. Paulin",
            "Cunnet's Tod": "St. Paulin",
            "Der Mohr": "Nells Ländchen",
            "Die Zauberstiefel": "Pfalzel",
            "Unverhoffte Rettung": "Biewer",
            "Die Hieronymus-Höhle": "St. Marien",
            "Friedrich Spee": "St. Marien",
            "Der eingemauerte Mönch": "St. Marien",
            "Heiteres Leben": "Zurlauben",
            "Die Blume des Thales": "Pallien",
            "Najaden-Tänze": "Pallien",
            "Der Krondiamant": "Das Weißhaus",
            "Hommerspläßchen": "Der Kockelsberg",
            "Ansicht": "Der Wasserfall",
            "Der Fremde und das Sandmädchen": "Der Wasserfall",
            "Das Mühlenthal": "Der Wasserfall",
            "Das Heinzemännchen": "Der Wasserfall",
            "Schlürfen": "Kaffee Wettendorf",
            "Das Metzgerskreuzchen": "Der Pulsberg",
            "Sonnenaufgang": "Der Markusberg",
            "Die Octave": "Der Markusberg",
            "Das Glöcklein": "Der Markusberg",
            "Der Wassersalamander": "Balduinshäuschen",  # Wasserfalamandar im OCR
            "In nomine domini": "Balduinshäuschen",
            "Der letzte Stuart": "Balduinshäuschen",
            "Der Helenabrunnen": "Euren",
            "Der Steinbruch der Liebfrauenkirche": "Zewen",
            "Das Abschiedsdenkmal": "Igel",
            "Der Todtenkopf-Mantel": "Konz",
            "Der verborgene Keller": "Karthaufe",
            "Das gerettete Kind": "St. Medard",
            "Medardin von Rottenfelt": "St. Matheis",
            "Alte Inschrift": "St. Matheis",
            "Der Matheiser Sauerbrunnen": "St. Matheis",
            "Die Forsthütte": "St. Matheis",
            "Siko": "Heiligkreuz",
            "Spaziergang": "Die Seufzerallee",  # spazirgang im.txt verbessert
            "Der Name Olewig": "Die Olewig",
            "Ländliche Bilder": "Die Olewig",
            "Sauere Milch": "Die Olewig",
            "Trebeta's Grab": "Das Franzenknöppchen",
            "Sickingens Kanonenkugel": "Das Franzenknöppchen",
            "Der Erdhügel": "Das Franzenknöppchen",
            "Die Kreuzkapelle": "Das Franzenknöppchen",
            "Das Marmorbett": "Castell an der Saar",
            "Der Hirtenknabe": "Fließem",
            "Der gekreuzigte Amor": "Verschiedenes",
            "Die drei Helden": "Verschiedenes",
            "Glimpf und Schimpf des Moselweins": "Verschiedenes",
            "Betheuerungen eines Liebhabers": "Verschiedenes",
            "Bemerkungen": "Verschiedenes"
            }
    return dict


def get_titles_lothringen():
    titles = ["Frau Florentina die Getreue",
              "Die Bischöfe von Metz und ihre Legenden",
              "Im Königspalaste zu Metz",
              "Sankta Glossindis von Metz",
              "Im Schatten des Hirtenstabes von Gorze",
              "Die Kaiserin Hildegard",
              "Lohengrin",
              "Papst Leo IX.",
              "Der hlg. Richard und Kaiser Heinrich II.",
              "Die Sagen der Herzöge von Lothringen",
              "Wappen, Fahnen, Schlachtrufe u. Devisen der Herzöge von Lothringen",
              "Templer- und Adelssagen",
              "Der Graf von Engelweiler und die Waldfrau",
              "Auf Feld und Flur",
              "Geflügelte Worte aus dem alten Metz",
              "Der reiche Bürger von Verdun",
              "qwertz"]
    return titles


def get_ort_unterelsass():
    ort = ['Schlettstadt', 'Restenholz', 'Frankenburg', 'Scherweiler', 'Schloß Bilstein bei Urbeis',
           'Dambachu Bernstein', 'Ebersmünster', 'Markolsheim', 'Neunkirchen bei Friesenheim', 'Rheinau', 'Roßfeld',
           'Sermersheim', 'Benfeld', 'Ehl bei Benfeld', 'Sand bei Benfeld', 'Westhausen bei Benfeld', 'Magenheim',
           'Gerstheim', 'Osthausen', 'Erstein', 'Plobsheim', 'Eschau', 'Geispolsheim', 'Stoßheim',
           'Ungersberg bei Andlau', 'Andlau', 'Barr', 'Heiligenstein', 'St Nabor', 'Ottrott', 'Odilienberg',
           'Hochfeld', 'Rosheim', 'Innenheim', 'Rosenweiler', 'Laubenheim', 'Girbaden', 'Lüzelhausen',
           'Salm bei Rothau', 'Salm bei Rothau', 'Urstein', 'Schneeberg', 'Nideck', 'Oberhaslach', 'Avolsheim',
           'Dachstein', 'Sulzbad', 'Balbronn', 'Westhofen', 'Wangen', 'Kirchheim', 'Marlenheim', 'Kochersberg',
           'Maursmünster', 'Dagsburger Land', 'Walscheid', 'Alberschweiler und die saarthäler',
           'Alberschweiler und die saarthäler', 'Lüzelburg', 'Garburg', 'Zabern', 'Monsweiler', 'St Johann',
           'Oberhof bei Zabern', 'Dettweiler', 'Bischheim', 'Brumath', 'Mommenheim', 'Ohlungen', 'Ettendorf',
           'Zöbersdorf', 'Bosselshausen', 'Kirrweiler', 'Obermodern', 'Buchsweiler', 'Buchsweiler', 'Riedheim',
           'Neuweiler', 'Lüzelstein', 'Ottweiler', 'Aßweiler', 'Drulingen', 'Hirschland', 'Berg und Thal',
           'Durstel', 'Tiefenbach', 'Volksberg', 'Diemeringen', 'Saarwerden', 'Saarwerden', 'Saarunion', 'Lorenzen',
           'Herbißheim', 'Engelweiler', 'Ingweiler', 'Neuenburg bei Hagenau', 'Hagenau', 'Biblisheim', 'Mietesheim',
           'Engweiler', 'Uhrweiler', 'Gumbrechtshofen', 'Offweiler', 'Rothbach', 'Lichtenberg',
           'Arnsberg bei Bärenthal', 'Falkenstein bei Philippsburg', 'Stürzelbronn bei Bitsch', 'Bitsch',
           'Eppenbrunn bei Bitsch', 'Oberbronn', 'Alt- und Neu-Winstein im Jägerthal', 'Fröschweiler',
           'Wörth a d sauer', 'Hatten', 'Beinheim', 'Görsdorf', 'Wasigenstein', 'Hohenburg', 'Löwenstein',
           'Bärbelstein', 'Weißenburg', 'Straßburg', 'Straßburg', 'Straßburger Münster']

    return ort


def get_titles_unterelsass():
    titles = ["Schlettstadt's Ursprung", 'Die Kirche und das Kloster St. Fides', 'Der Schimmelreiter bei Schlettstadt',
              'Die Glocke von Kestenholz', 'Die drei Kröten in Chlodwigs Wappenschild',
              'Die heilige Odilia in Scherrweiler', 'Hans Marx von Eckwersheim',
              'Hans Marx von Eckwersheim und Anton von Wilsperg', 'Die treue Gattin', 'Der Sturm auf dem Rheine',
              'Das Muttergottesbild in Neunkirchen', 'Das versunkene Kloster zu Rheinau', 'Das weiße Pferd bei Roßfeld',
              'Königsherberg', 'Das Queermännel', 'Der Stubenhanzel von Benfeld', 'Der Heidengott von Ehl',
              'Die Legende des H. Maternus, Apostels des Elsasses', 'Doktor Faust in Sand',
              'Der schwarze Klaus bei Westhausen',
              'Wie der Name der Edeln von Matzenheim seinen Ursprung dem Wirthshaus zu verdanken habe',
              'Die Gräfin von Geroldseck und Schwanau', 'Die weiße Frau von Schwanau', 'Der Wiwelesweg',
              'Die Hülfe der Todten', 'Die Geistermesse in Erstein', 'Maria zur Eich', 'Das Kloster Eschau',
              'Der Krantzen von Geispolsheim Wappenschild', 'Der gespenstige Feldmesser', 'Der Ungersberg',
              'Der Fahnenstein auf dem Ungersberg', 'St. Richardis, Kaiserin, Stifterin der Abtei Andlau',
              'Die Bären in der Kirche von Andlau', 'Der Müllerbursche und das Fräulein von Hoh-Andlau',
              'Die Wepfermänner', 'Das Rothkäppel', 'Die Erscheinung auf dem Speicher',
              'Wie der Teufel das Städtlein Barr nicht hergeben kann', 'Der Hungerbrunnen',
              'Ein Hexenmahl bei Heiligenstein', 'Der Bocksfelsen', 'Irreführendes Licht', 'Der Jägerpfad bei Ottrott',
              'Die Legende der heiligen Odilia, Patronin des Elsasses', 'Das hl. Kreuz in Niedermünster',
              'Die unterirdischen Höhlen im Hagelschlosse', 'Der Männelstein', 'Die Geister auf dem Hochfeld',
              'Der wilde Jäger', 'Die Kirche zu St. Peter und Paul in Rosheim',
              'Engel behüten die Kirche vor der Wuth der Mansfeldischen Truppen', 'Die Rosheimer Glocke',
              'Die Geisterkutsche', 'Der Stadtschreiber von Rosheim', 'Die Geisenkapelle auf dem Glöckelsberg',
              'Das Muttergottesbild zu Rosenweiler', 'Das Teufelsgebirge',
              'Die St. Valentins-Kapelle im Schloß Girbaden',
              'Der lustige Vogt auf Girbaden', 'Die Belagerung von Girbaden', 'Die Gerichtsnacht auf Girbaden',
              'Der Feengarten und die Feenbrücken', 'Der Riese auf dem Nollen', 'Schatzsagen von Salm',
              'Die Regenfrau von Salm', 'Die Jungfrau auf dem Urstein', 'Der Lottelfelsen auf dem Schneeberge',
              'Der gespenstige Förster am Schneeberge', 'Die Riesentochter von Nideck', 'Sankt Florentius',
              'Das Grab der heiligen Petronilla', 'Die Kapelle St. Armuth', 'Die Entstehung des Sulzbades',
              'Der feurige Mann', 'Der Rohracker', 'Die weißen Katzen', 'Der Dorfhammel', 'Das Weinbrünnlein',
              'Der König Dagobert und Neu-Troja', 'Die weißen Schafe', 'Das Marienbild in der Kapelle zu Marlenheim',
              'Die Spukthiere im Kronthal', 'Woher die Redensart kommt: „Benz unten, Benz oben.“',
              'Die St. Ulrichsquelle bei Avenheim', 'Der Drescher von Rohr', 'Trenks Mantelsack',
              'Das Mittagläuten in den Dörfern des Kochersbergs', 'St. Autors Brünnlein in Maursmünster',
              'Die Spille und die Kunkel', 'Der gedeckte Markstein', 'Die Gespensterwiese bei der Hub',
              'Der Todtenkopffelsen bei der Hub', 'Die weißen Jungfrauen bei Haselburg',
              'Die Belagerten im Schloß Dagsburg', 'Das Dorfthier von Dagsburg', 'Der Herrenfelsen bei Dagsburg',
              'Das graue Männlein von Altdorf', 'Gespenster auf dem Martelberge', 'Dreiheiligen',
              'Schatz auf dem Hohwalsch', 'Feurige Männer bei Walscheid', 'Die goldverwandelten Baumblätter',
              'Die Schatzgräber auf St. Leon', 'Fremde Schatzgräber bei St. Leon', 'Bestrafter Uebermut',
              'Der Geldfelsen',
              'Der Lottelfelsen auf dem Nonnenberg', 'Der Gespensterfelsen bei Soldatental', "St. Quirin's Stuhl",
              'Der "sac de pierre"', 'Die Gräfin von Lützelburg', 'Die Jungfrau von Lützelburg',
              'Der Pfaff von Garburg',
              'Die Steinbütte', 'Der Brotschgeist', 'Ein Müllerknecht wird in einen Esel verwandelt',
              'Die gebannten Helden im Schloß Groß-Geroldseck',
              'Chronik-Sage von den Schlössern Groß-Geroldseck und Lützelhart', 'Der Brudermörder',
              'Die Horn-Bruderschaft auf Hoh-Barr', 'Die Panduren auf Hoh-Barr', 'Der St. Veits-Tanz',
              'Die Dame von Greifenstein', 'Der Karlssprung', 'Das Muttergottesbild in Monsweiler',
              'Die redenden Bilder Christi und Mariä', 'Die Herenschule', 'Das Forsthaus Oberhof', 'Die Diebesschelle',
              'Entweihe das Brod nicht!', 'Der spukende Mönch bei der Kirche von Bischheim',
              'Stiftung des Klosters Stephansfeld, bei Brumath', 'Störe die Ruhe der Todten nicht!', 'Die Klos-Kapelle',
              'Das Schellenmännlein von Ettendorf', 'Die Gespensterkutsche 1', 'Der Riegersche Garten',
              'Das Gänsbrückel',
              'Die Gespensterkutsche 2', 'Die gespenstigen Kinder im Dunzenbruch', 'Die wilde Jagd im Moderer Wald',
              'Die schwarze Kuh von Obermodern', 'Historie von der schönen, aber bösen Bärbel',
              'Der Bildhauer Marderstecken', 'Der Lure-Jerri', 'Warum es gewöhnlich am Buchsweiler Jahrmarkte regnet',
              'Das Stadtkalb und das Letzel', 'Gespensterthiere im Freihof', 'Der Bäckerbursche in der Herrengasse',
              'Der Spuk im Keller', 'Die Here als Pferd', 'Die Here als Ente', 'Die spinnenden Heren',
              'Hexenbann, wenn das Vieh veruntreut ist', 'Der Bastberg',
              'Der Schulmeister als Spielmann bei der Herenrunde', 'Der Spielmann auf dem Bastberg',
              'Der Geist im Kissel', 'Der feurige Drache in Riedheim', 'Das Adelphusbrünnlein bei Neuweiler',
              'Die weiße Jungfrau von der Hünenburg', 'Der Geigerstein', 'Ueberfall der Veste Lützelstein',
              'Das weiße Fräulein vom Druttwald', 'Die angehaltenen Fruchtwagen', 'Der gespenstige Schimmel',
              'Die Fahrt auf dem Ziegenbock', 'Der fliegende Hase', 'Das schwarze Hündlein', 'Die Kornmutter',
              'Die Hunde auf dem Brücklein', 'Der Fluch des Jesuiten', 'Berg und Thal',
              'Die „Heilwog“ in der Neujahrsnacht', 'Die geraubte Braut', 'Der Tiefenbacher Wald',
              'Die versunkene Stadt', 'Der Spitzstein und der Breitenstein', 'Der wilde Jäger bei Waldhambach',
              'Herr von Bokisch und sein Schwan', 'Die kristallene Salzfee zu Diemeringen', '„Der Hopp kommt!“',
              'Das weiße Fräulein von Diemeringen', 'Der letzte Graf von Saarwerden und die Fee',
              'Der Bettag in der Grafschaft Hanau-Saarwerden', 'Der unbequeme Mitbürger', 'Die Here von Heimeldingen',
              'Der Mann im Lapphut bei Lorenzen', 'Die Brücke von Herbitzheim', 'Der Graf von Engelweiler und die Fee',
              'Der Schatz in der Helferei', 'Das Ingweiler Stadtkalb', 'Das Irrkraut', 'Das Haberkreuz bei Neuenburg',
              '"Wie die Burg und die Stadt Hagenau erhaben und gemacht worden."',
              'Kaiser Barbarossa ist in der Burg zu Hagenau lebendig verzückt worden', 'Der Statthalter von Hagenau',
              'Die Blaulichtlein', 'Der verzückte Mönch', 'Der dreibeinige Hase', 'Die Gloshecke',
              'Das Geisterheer bei der Gloshecke', 'Der Mann ohne Kopf auf dem Schimmel', 'Der alte Krähn',
              'Das Mädchen von Engweiler', 'Der Erzknappe von Uhrweiler', 'Helf Dir Gott!', 'Der Teufelshafer',
              'Sagen vom Selhof, bei Rothbach', 'Bruderrache', 'Lichter auf Hellebarden', 'Graf Jakob von Lichtenberg',
              'Graf Jakob von Lichtenberg der Zauberkundige', 'Graf Jakob von Lichtenberg und der Franzose',
              'Der starke Beilstein', 'Graf Ludwig von Lichtenberg und der Roßtäuscher',
              'Graf Ludwig von Lichtenberg und der Kaufmann',
              'Graf Ludwig von Lichtenberg verschafft sich ein Nachtquartier', 'Der Kellermeister auf Arnsburg',
              'Die Ritter auf Arnsburg', 'Der Küfer vom Falkenstein', 'Der Glockenfelsen bei Stürzelbronn',
              'Des Herzogs Hand', 'Die Gräfin von Bitsch', 'Kühner Sprung', 'Der Bickelstein',
              'Die weiße Frau an der Waschbach', 'Der „Heilebrunnen“', 'Die lüsterne Here', 'Die Kappe auf einem Ohr',
              'Die Burgfrau auf Alt-Winstein', 'Die Belagerung von Neu-Winstein',
              'Die goldenen Kegel auf Neu-Windstein', 'Die drei Schatzgräber im Jägerthale', 'Irrführende Geister',
              'Der erlöste Todte', 'Der gespenstige Förster', 'Der Geisenmajor',
              'Die Wallfahrt Unsrer Lieben Frauen zur Eich in Görsdorf', 'Der Kampf der Helden auf dem Wasgenstein',
              'Der Maidebrunn', 'Der Krötenstuhl', 'Der Lindenschmidt', 'Hans Trapp', 'Weißenburger Stadtgespenster',
              'Gespensterheer bei Weißenburg', 'Das Letzekäppel',
              'Ursprung der Redensart : „Zu Weißenburg, wo man den Bumpernickel in der Kirche singt."',
              'Sebastian Vogelsperger und Lazarus Schwendi', 'Das Mädchen vom Pauliner Schlößchen',
              'Die weiße Dame vom Pauliner Schlößchen',
              'Der schwarze Hund und die unterirdischen Schätze im Pauliner Schlößchen',
              'In Goldstücke verwandelte Porzellanscherben', 'Die Wäsche im Pauliner Schlößchen',
              'Das Feldgewann Goldhaus bei Weißenburg', 'Straßburgs Stadtwappen', 'Eine alte Weissagung von Straßburg',
              'St. Arbogast, Bischof von Straßburg', 'St. Arbogast und der Sohn der Wittwe', 'Die heilige Attala',
              'Bischof Wilderolf wird von den Mäusen gefressen', "Bischof Otto's IV. Gesicht", 'Des Ammeisters Sohn',
              'Der Marschall von Hünenburg und die Stiftung von St. Johann zum grünen Wörd', 'Der Kinder Kreuzzug',
              'Der tödtliche Sprung', 'Die Wunderthaten der Geißler',
              'Die Sage von dem Ursprunge der beiden Ammeistergeschlechter der Barpfenning und der Leimer in Straßburg',
              'Kaiser Sigismund und die Straßburger Edelfrauen',
              'Die Sage von den ersten Zigeunern, welche in das Elsaß und nach Straßburg kamen',
              "Hansen's von Westhausen Geist erscheint auf dem Hohensteg", 'Die Inschrift am ehemaligen Weißthurmthore',
              'Die Erfindung der Buchdruckerkunst', 'Der Bäckerknechte Zug nach Wasselnheim',
              'Warum die Straßburger Meisenlocker heißen', 'Das Männlein am Katharinenthurm',
              'Die Hunde in der großen Kirchgasse', 'Straßburger Wahrzeichen', 'Ein Straßburger Wahrzeichen',
              'Finkweilerer Gespenster', 'Der Geist zu St. Marx', 'Das Wüthenheer in der Weißthurmstraße',
              'Die Nonne von St. Klara', 'Das Milchweibchen, das Loßmännel und der Flozemann in der Steinstraße',
              'Das Armsünderhaus in Straßburg', 'Das rothe Männel', 'Kaiser Napoleon lebt noch',
              'Die reiche Jungfrau mit dem Todtenkopf', 'Das Wellenmännel im Mond', 'Das Donnerloch bei Straßburg',
              'Eisenbahnsagen', 'Der Wind auf dem Straßburger Münsterplatze', 'Ein schatzfindender Venediger',
              'Die Glocke zu Haueneberstein und die Straßburger', 'Der heilige Hain und die drei Buchen',
              'Der Bronnen im Münster', 'Das Gewölbe und der See unter dem Münster',
              'Chlodwigs Taufe und die Stiftung des Münsters', 'Die Stiftung der Chorkönigspfründe', 'Der Fronhof',
              'Die drei steinernen Reiter am Münster', 'Das Reiterlein an der Säule', 'Das Horn an der Säule',
              'Die beiden Arbeiter', 'Sabina', 'Das heilige Grab', 'Das „Grüselhorn“ und der „Judenblos“',
              'Des „Roraffen“ und des Hahnen Streit', 'Das Einhorn und Herr Rudolf von Schauenburg',
              'Der Werkmeister am Thurme', 'Der Kaiser und der Mönch', 'Das traurige, kreuztragende Christusbild',
              'Das Männlein oder Bäuerlein auf dem Geländer bei der Engelsäule', 'Das Uhrwerk im Münster',
              'Der singende Knabe auf der Uhr', 'Der fremde Kavalier und sein Hund', 'Die Johannisnacht im Münster',
              "qwertz"]

    return titles


def get_dict_unterelsass():
    dict = {'Schlettstadts Ursprung': 'Schlettstadt', 'Die Kirche und das Kloster St. Fides': '',
            'Der Schimmelreiter bei Schlettstadt': '', 'Die Glocke von Kestenholz': 'Restenholz',
            'Die drei Kröten in Chlodwigs Wappenschild': 'Frankenburg',
            'Die heilige Odilia in Scherweiler': 'Scherweiler',
            'Hans Mary von Eckwersheim': 'Schloß Bilstein bei Urbeis',
            'Hans Mary v Eckwersheim u Anton v Wilsperg': 'Dambachu Bernstein', 'Die treue Gattin': 'Ebersmünster',
            'Der Sturm auf dem Rheine': 'Markolsheim',
            'Das Muttergottesbild in Neunkirchen': 'Neunkirchen bei Friesenheim',
            'Das versunkene Kloster zu Rheinau': 'Rheinau', 'Das weiße Pferd bei Roßfeld': 'Roßfeld',
            'Königsherberg': '', 'Das Queermännel': 'Sermersheim', 'Der Stubenhanzel von Benfeld': 'Benfeld',
            'Der Heidengott von Ehl': 'Ehl bei Benfeld', 'Die Legende des h Maternus, Apostels des Elsaßes': '',
            'Doktor Faust in Sand': 'Sand bei Benfeld', 'Der schwarze Klaus bei Westhausen': 'Westhausen bei Benfeld',
            'Wie der Name der Edeln von Maßenheim seinen Ursprung dem Wirthshaus zu verdanken habe': 'Magenheim',
            'Die Gräfin von Geroldseck und Schwanau': 'Gerstheim', 'Die weiße Frau von Schwanau': '',
            'Der Wirelesweg': '', 'Die Hülfe der Todten': 'Osthausen', 'Die Geistermesse in Erstein': 'Erstein',
            'Maria zur Eich': 'Plobsheim', 'Das Kloster Eschau': 'Eschau',
            'Der Kranzen von Geispolsheim Wappenschild': 'Geispolsheim', 'Der gespenstige Feldmesser': 'Stoßheim',
            'Der Ungersberg': 'Ungersberg bei Andlau', 'Der Fahnenstein auf dem Ungersberg': '',
            'St Richardis, Kaiserin, Stifterin der Abtei Ardlau': 'Andlau', 'Die Bären in der Kirche von Andlau': '',
            'Der Müllerbursche und das Fräulein von Hoh-Andlau': '', 'Die Wepfermänner': 'Barr', 'Das Rothkäppel': '',
            'Die Erscheinung auf dem Speicher': '', 'Wie der Teufel das Städtlein Barr nicht hergeben kann': '',
            'Der Hungerbrunnen': 'Heiligenstein', 'Ein Hexenmahl bei Heiligenstein': '', 'Der Bocksfelsen': 'St Nabor',
            'Frreführendes Licht': '', 'Der Jägerpfad bei Ottrott': 'Ottrott',
            'Die Legende der heilg Odilia, Patronin des Elsaßes': 'Odilienberg',
            'Das heilige Kreuz in Niedermünster': '', 'Die unterirdischen Höhlen im Hagelschlosse': '',
            'Der Männelstein': '', 'Die Geister auf dem Hochfeld': 'Hochfeld', 'Der wilde Jäger': '',
            'Die Kirche zu St. Peter und Paul in Rosheim': 'Rosheim',
            'Engel behüten die Kirche vor der Wuth der Mansfeldischen Truppen': '', 'Die Rosheimer Glocke': '',
            'Die Geisterkutsche': '', 'Der Stadtschreiber von Rosheim': '',
            'Die Geijenkapelle auf dem Glöckelsberg': 'Innenheim', 'Das Muttergottesbild zu Rosenweiler': 'Rosenweiler',
            'Das Teufelsgebirge': 'Laubenheim', 'Die St. Valentinskapelle im Schloß Girbaden': 'Girbaden',
            'Der lustige Vogt auf Girbaden': '', 'Die Belagerung von Girbaden': '',
            'Die Gerichtsnacht auf Girbaden': '', 'Der Feengarten und die Feenbrücken': 'Lüzelhausen',
            'Der Riese auf dem Nollen': '', 'Schabsagen von Salm': 'Salm bei Rothau',
            'Die Regenfrau von Salm': 'Salm bei Rothau', 'Die Jungfrau auf dem Urstein': 'Urstein',
            'Der Lottelfelsen auf dem Schneeberge': 'Schneeberg', 'Der gespenstige Förster am Schneeberge': '',
            'Die Riesentochter von Nideck': 'Nideck', 'St Florentius': 'Oberhaslach',
            'Das Grab der heilg Petronilla': 'Avolsheim', 'Die Kapelle St. Armuth  3:#*': 'Dachstein',
            'Die Entstehung des Sulzbades': 'Sulzbad', 'Der feurige Mann': 'Balbronn', 'Der Rohracker': 'Westhofen',
            'Die weißen Kazen': 'Wangen', 'Der Dorfhammel': '', 'Das Weinbrünnlein': '',
            'Der König Dagobert und Neu-Troja': 'Kirchheim', 'Die weißen Schafe': 'Marlenheim',
            'Das Marienbild in der Kapelle zu Marlenheim': '', 'Die Spukthiere im Kronthal': '',
            'Woher die Redensart kommt : „Benz unten, Benz oben"': 'Kochersberg',
            'Die St. Ulrichsquelle bei Avenheim': '', 'Der Drescher von Rohr': '', 'Trenks Manteljack': '',
            'Das Mittagläuten in den Törfern des Kochersbergs': '',
            'St Autors Brünnlein in Maursmünster': 'Maursmünster', 'Die Spille und die Kunkel': 'Dagsburger Land',
            'Der gedeckte Markstein': '', 'Die Gespensterwiese bei der Hub': '', 'Der Todtenkopffelsen bei der Hub': '',
            'Die weißen Jungfrauen bei Haselburg ≤': '', 'Die Belagerten im Schloß Dagsburg ≤': '',
            'Das Dorfthier von Dagsburg': '', 'Der Ferrenfelsen bei Dagsburg': '', 'Das graue Männlein von Altdorf': '',
            'Gespenster auf dem Martelberge': '', 'Dreiheiligen': '', 'Schatz auf dem Hohwalsch': '',
            'Feurige Männer bei Walscheid': 'Walscheid', 'Die goldverwandelten Baumblätter': '',
            'Die Schaßgräber auf St. Leon': '', 'Fremde schaßgräber auf St. Leon': '',
            'Bestrafter Uebermuth': 'Alberschweiler und die saarthäler',
            'Der Geldfelsen': 'Alberschweiler und die saarthäler', 'Der Lottelfelsen auf dem Nonnenberg': '',
            'Der Gespensterfelsen bei soldatenthal': '', 'St Quirins Stuhl': '', 'Der sac de pierre>': '',
            'Die Gräfin von Lüzelburg': 'Lüzelburg', 'Die Jungfrau von Lüzelburg': '',
            'Der Pfaff von Garburg': 'Garburg', 'Die Steinbütte': 'Zabern', 'Der Brotschgeist': '',
            'Ein Müllerknecht wird in einen Esel verwandelt': '', 'Die gebannten Helden im Schloß Groß- Geroldseck': '',
            'Chronik- Sage von den Schlössern Groß- Geroldseck und Lüzelhart': '', 'Der Brudermörder': '',
            'Die Horn-Bruderschaft auf Hoh-Barr': '', 'Die Panduren auf Hoh- Barr': '', 'Der St. Veits Tanz': '',
            'Die Dame von Greifenstein': '', 'Der Karlssprung': '', 'Das Muttergottesbild in Monsweiler': 'Monsweiler',
            'Die redenden Bilder Christi und Mariä': 'St Johann', 'Die Herenschule': '',
            'Das Forsthaus Oberhof': 'Oberhof bei Zabern', 'Die Diebesschelle': '',
            'Entweihe das Brod nicht !': 'Dettweiler', 'Der spukende Mönch bei der Kirche von Bischheim': 'Bischheim',
            'Stiftung des Klosters Stephansfeld bei Brumath': 'Brumath',
            'Störe die Ruhe der Todten nicht !': 'Mommenheim', 'Die Klos-Kapelle': 'Ohlungen',
            'Das Schellenmännlein von Ettendorf': 'Ettendorf', 'Die Gespensterkutsche 1': 'Zöbersdorf',
            'Der Riegersche Garten': '', 'Das Gänsbrückel': 'Bosselshausen', 'Die Gespensterkutsche 2': 'Kirrweiler',
            'Die gespenstigen Kinder im Dunzenbruch': 'Obermodern', 'Die wilde Jagd im Moderer Wald': '',
            'Die schwarze Kuh von Obermodern': '', 'Historie von der schönen, aber bösen Bärbel': 'Buchsweiler',
            'Der Bildhauer Marderstecken': '', 'Der Lure- Jerri': 'Buchsweiler',
            'Warum es gewöhnlich am Buchsweiler Jahrmarkte regnet': '', 'Das Stadtkalb und das Lezel': '',
            'Gespensterthiere im Freihof': '', 'Der Bäckerbursche in der Herrengasse': '', 'Der Spuk im Keller': '',
            'Die Here als Pferd': '', 'Die Here als Ente': '', 'Die spinnenden Heren': '',
            'Herenbann, wenn das Vieh veruntreut ist': '', 'Der Bastberg': '',
            'Der Schulmeister als Spielmann bei der Herenrunde': '', 'Der Spielmann auf dem Bastberg': '',
            'Der Geist im Kissel': '', 'Der feurige Drache in Riedheim': 'Riedheim',
            'Das Adelphusbrünnlein bei Neuweiler': 'Neuweiler', 'Die weiße Jungfrau von der Hünenburg': '',
            'Der Geigerstein': '', 'Ueberfall der Veste Lüzelstein': 'Lüzelstein',
            'Das weiße Fräulein vom Druttwald': 'Ottweiler', 'Die angehaltenen Fruchtwagen': '',
            'Der gespenstige Schimmel': 'Aßweiler', 'Die Fahrt auf dem Ziegenbock': '', 'Der fliegende Hase': '',
            'Das schwarze Hündlein': '', 'Die Kornmutter': 'Drulingen', 'Die Hunde auf dem Brücklein': '',
            'Der Fluch des Jesuiten': 'Hirschland', 'Berg und Thal': 'Berg und Thal',
            'Die 11 Heilwog" in der Neujahrsnacht': 'Durstel', 'Die geraubte Braut': '',
            'Der Tiefenbacher Wald': 'Tiefenbach', 'Die versunkene Stadt': 'Volksberg',
            'Der Spigstein und der Breitenstein': '', 'Der wilde Jäger bei Waldhambach': '',
            'Herr von Bokisch und sein Schwan': 'Diemeringen', 'Die kristallene Salzfee zu Diemeringen': '',
            '„Der Hopp kommt!"': '', 'Das weiße Fräulein von Diemeringen': '',
            'Der leßte Graf von Saarwerden und die Fee': 'Saarwerden',
            'Der Bettag in der Grafschaft Hanau- Saarwerden': 'Saarwerden', 'Der unbequeme Mitbürger': 'Saarunion',
            'Die Here von Heimeldingen': '', 'Der Mann im Lapphut bei Lorenzen': 'Lorenzen',
            'Die Brücke von Herbißheim': 'Herbißheim', 'Der Graf von Engelweiler und die Fee': 'Engelweiler',
            'Der Schatz in der Helferei': 'Ingweiler', 'Das Ingweiler Stadtkalb': '', 'Das Frrkraut': '',
            'Das Haberkreuz bei Neuenburg': 'Neuenburg bei Hagenau',
            '"Wie die Burg und die Stadt Hagenau erhaben und gemacht worden"': 'Hagenau',
            'Kaiser Barbarossa ist in der Burg zu Hagenau lebendig verzückt worden': '',
            'Der Statthalter von Hagenau': '', 'Die Blaulichtlein': '', 'Der verzückte Mönch': 'Biblisheim',
            'Der dreibeinige Hase': 'Mietesheim', 'Die Gloshecke': '', 'Das Geisterhecr bei der Gloshecke': '',
            'Der Mann ohne Kopf auf dem Schimmel': '', 'Der alte Krähn': '', 'Das Mädchen von Engweiler': 'Engweiler',
            'Der Erzknappe von Uhrweiler': 'Uhrweiler', 'Helf Dir Gott!': 'Gumbrechtshofen',
            'Der Teufelshafer': 'Offweiler', 'Sagen vom Selhof bei Rothbach': 'Rothbach', 'Bruderrache': 'Lichtenberg',
            'Lichter auf Hellebarden': '', 'Graf Jakob von Lichtenberg': '',
            'Graf Jakob von Lichtenberg der Zauberkundige': '', 'Graf Jakob von Lichtenberg und der Franzose': '',
            'Der starke Beilstein': '', 'Graf Ludwig von Lichtenberg und der Roßtäuscher': '',
            'Graf Ludwig von Lichtenberg und der Kaufmann': '',
            'Graf Ludwig von Lichtenberg verschafft sich ein Nachtquartier': '',
            'Der Kellermeister von Arnsburg': 'Arnsberg bei Bärenthal', 'Die Ritter auf Arneburg': '',
            'Der Küfer von Falkenstein': 'Falkenstein bei Philippsburg',
            'Der Glockenfelsen bei Stürzelbronn': 'Stürzelbronn bei Bitsch', 'Des Herzogs Hand': '',
            'Die Gräfin von Bitsch': 'Bitsch', 'Kühner Sprung': 'Eppenbrunn bei Bitsch', 'Der Bickelstein': 'Oberbronn',
            'Die weiße Frau an der Waschbach': '', 'Der „Heilebrunnen“': '', 'Die lüsterne Here': '',
            'Die Kappe auf einem Ohr': '', 'Die Burgfrau auf Alt-Winstein': 'Alt- und Neu-Winstein im Jägerthal',
            'Die Belagerung von Neu-Winstein': '', 'Die goldenen Kegel auf Neu- Winstein': '',
            'Die drei Schaßgräber im Jägerthale': '', 'Jrrführende Geister': 'Fröschweiler',
            'Der erlöste Todte': 'Wörth a d sauer', 'Der gespenstige Förster': 'Hatten', 'Der Geisenmajor': 'Beinheim',
            'Die Wallfahrt Unsrer Lieben Frauen zur Eich in Görsdorf': 'Görsdorf',
            'Der Kampf der Helden auf dem Wasgenstein': 'Wasigenstein', 'Der Maidebrunn': 'Hohenburg',
            'Der Krötenstuhl': '', 'Der Lindenschmidt': 'Löwenstein', 'Hans Trapp': 'Bärbelstein',
            'Weißenburger Stadtgespenster': 'Weißenburg', 'Gespensterheer bei Weißenburg': '', 'Das Lezekäppel': '',
            'Ursprung der Redensart : „Zu Weißenburg, wo man den Bumpernickel in der Kirche singt"': '',
            'Sebastian Vogelsperger und Lazarus schwendi': '', 'Das Mädchen vom Pauliner Schlößchen': '',
            'Die weiße Dame vom Pauliner Schlößchen': '',
            'Der schwarze Hund und die unterirdischen Schäße im Pauliner Schlößchen': '',
            'In Goldstücke verwandelte Porzellanscherben': '', 'Die Wäsche im Pauliner Schlößchen': '',
            'Das Feldgewann Goldhaus bei Weißenburg': '', 'Straßburgs Stadtwappen': 'Straßburg',
            'Eine alte Weissagung von Straßburg': '', 'St Arbogast, Bischof von Straßburg': '',
            'St Arbogast und der Sohn der Wittwe': 'Straßburg', 'Die heilige Attala': '',
            'Bischof Wilderolf wird von den Mäusen gefressen': '', 'Bischof Ottos IV Gesicht': '',
            'Des Ammeisters Sohn': '',
            'Der Marschall von Hünenburg und die Stiftung von St. Johann zum grünen Wörd': '',
            'Der Kinder Kreuzzug': '', 'Der tödtliche Sprung': '', 'Die Wunderthaten der Geißler': '',
            'Die Sage von dem Ursprunge der beiden Ammeistergeschlechter der Barpfenning und der Leimer in Straßburg': '',
            'Kaiser Sigismund und die Straßburger Edelfrauen': '',
            'Die Sage von den ersten Zigeunern, welche in das Elsaß und nach Straßburg kamen': '',
            'Hansens von Westhausen Geist erscheint auf dem Hohensteg': '',
            'Die Inschrift am ehemaligen Weißthurmthore': '', 'Die Erfindung der Buchdruckerkunst': '',
            'Der Bäckerknechte Zug nach Wasselnheim': '', 'Warum die Straßburger Meisenlocker heißen': '',
            'Das Männlein am Katharinenthurm': '', 'Die Hunde in der großen Kirchgasse': '',
            'Straßburger Wahrzeichen': '', 'Ein straßburger Wahrzeichen': '', 'Finkweiler Gespenster': '',
            'Der Geist zu St. Mary': '', 'Das Wüthenheer in der Weißthurmstraße': '', 'Die Nonne von St. Klara': '',
            'Das Milchweibchen, das Loßmännel und der Flozemann in der Steinstraße': '',
            'Das Armjünderhaus in Straßburg': '', 'Das rothe Männel': '', 'Kaiser Napoleon lebt noch': '',
            'Die reiche Jungfrau mit dem Todtenkopf': '', 'Das Wellenmännel im Mond': '',
            'Das Donnerloch bei Straßburg': '', 'Eisenbahnsagen': '', 'Der Wind auf dem straßburger Münsterplay': '',
            'Ein schaßfindender Venediger': '', 'Die Glock ze u Haueneberstein und id e Straßburger': '',
            'Der heilige Hain und die drei Buchen': 'Straßburger Münster', 'Der Bronnen im Münster': '',
            'Das Gewölbe und der See unter dem Münster': '', 'Chlodwigs Taufe und die Stiftung des Münsters': '',
            'Die Stiftung der Chorkönigspfründe': '', 'Der Fronhof': '', 'Die drei steinernen Reiter am Münster': '',
            'Das Reiterlein an der Säule': '', 'Das Horn an der Säule': '', 'Die beiden Arbeiter': '', 'Sabina': '',
            'Das heilige Grab': '', 'Das Grüselhorn" und der „Judenblos"': '',
            'Des "Roraffen" und des Hahnen Streit': '', 'Das Einhorn und Herr Rudolf von Schauenburg': '',
            'Der Werkmeister am Thurme': '', 'Der Kaiser und der Mönch': '',
            'Das traurige, kreuztragende Christusbild': '',
            'Das Männlein oder Bäuerlein auf dem Geländer bei der Engelsäule': '', 'Das Uhrwerk im Münster': '',
            'Der singende Knabe auf der Uhr': '', 'Der fremde Kavalier und sein Hund': '',
            'Die Johannisnacht im Münster': ''}
    return dict


def get_ort_oberelsass():
    ort = ['Jura', 'Altkirch', 'Heimersdorf', 'Pfirt', 'Luppach', 'Alt-Pfirt', 'Biederthal', 'Hagenthal', 'Köstlach',
           'Dürlinsdorf', 'Mörnach', 'Liebsdorf', 'Oberlarg', 'Langizen', 'Moos', 'Winkel', 'Winkel', 'Lüzel', 'Jufurt',
           'Brubach, Didenheim', 'Brunstatt', 'Mülhausen', 'Riedesheim', 'Hegenheim bei Hüningen', 'Kembs, Niffer',
           'Julzach', 'Rülisheim', 'Masmünster', 'Kirchberg bei Masmünster', 'Sewen', 'Masmünsterthal',
           'Rothenberg (Rougemont)', 'Thann', 'Thann', 'Sennheim', 'Weile br ei Thann', 'Großer Belchen', 'Gebweiler',
           'Bühl bei Gebweiler', 'Ungersheim', 'Sulzmatt', 'Rufach', 'Geberschweier', 'Egisheim', 'Colmar',
           'Heiligkreuz bei Colmar', 'Heiligkreuz bei Colmar', 'Hettenschlag bei Neubreisach',
           'Widensolen bei Neubreisach', 'Andolsheim', 'Logelbach bei Colmar', 'Winzenheim', 'Zimmerbach', 'Sulzbach',
           'Sulzern', 'Mezeral', 'Weier im Thale', 'Drei Aehren', 'Ingersheim', 'Ammerschweier', 'Kienzheim',
           'Kaysersberg', 'Alspach bei Kaysersberg', 'Urbeis (Orbey)', 'Reichenweier', 'Hunaweier', 'Rappoltsweiler',
           'Rappoltsweiler', 'Elsenheim u Jllhäusern', 'Lanneukirch', 'Hohlönigsburg bei Tannenkirch', 'Markirch',
           'Leberau']
    return ort


def get_titles_oberelsass():
    titles = ['Die Schlange im Jura', 'St. Morands Ruhe', 'Der Käpellegeist', 'Die Zwerge in der Wolfshöhle',
              'Des Teufels Recht auf Pfirt', 'Die Todtenprozession zu Luppach', 'Die Galgenplatte',
              'Der Lachgeist im Haag', 'Der Geist "Laxi" im Biederthaler Schlosse', 'Junker Schnabel',
              'Die Here von Köstlach', 'Das Herenschloß', 'Der Schmied im Berge',
              'Das versunkene Schloß Färis und der alte Graf', 'Die Herdwible von Mörnach',
              'Die Erbauung von Liebenstein', 'Der schwarze Vogel auf Liebenstein', 'Das Hündlein aus der wilden Jagd',
              'Der Hausgeist geht zur Kelte', 'Die drei Spinnerinnen', 'Der Hexentanz auf der Kalmiser Waide',
              'Das gefundene Silbergeld bei Mörsperg', 'Der Mann mit dem Lapphute zu Oberlarg',
              'Die weiße Dame vom Goldigberg', 'Das Totenpferd und die Totenprozession zu Moos',
              'Das Bildstöcklein bei Winkel', 'Das Altschloß bei Winkel', 'Der Dornstrauch bei Neun-Eich',
              'Das Silberloch bei Lützel', 'Die weiße Frau auf dem Küppele', 'Der Britzgyberg', 'Versenkte Glocken',
              'Das Weingeigerlein auf Brunstatt', 'Das schwarze Tier am Mühlbach', 'Die Gespensterheere im Nordfeld',
              'Kreuzregen', 'Himmelschweiß', 'Der Schatzgräber am Davidsbrünnlein',
              'Die weiße Frau in grünen Pantoffeln', 'Der verlorene Bräutigam', 'Der Milchsuppen-Acker',
              'Die Henne mit den goldenen Eiern in der Sankt-Marx-Kapelle bei Riedisheim', 'Das Dorftier zu Hegenheim',
              'Die Geisterkirche auf dem Rhein', 'Der weiße Mann vom Illzacher Schlosse',
              'Die weiße Jungfrau am Weiher', 'Die weißen Mädchen an der Lindlache', 'Der schwarze Mann am Rain',
              'Die Erscheinung am Rain', 'Das weiße Pferd', 'Der Pferdeschatten am Rain', 'Der Nachtjäger',
              'Das Tucherle am Viertelssteg', 'Das Doggele', 'Das Fronfastentier', 'Der Dorfesel', 'Der Milchbrunnen',
              'Maria in der Eich', 'Masmünsters Entstehung', 'Der Lachtelweiher', 'Das Muttergottesbild in Sewen',
              'Das Dambürle im Masmünsterthale', 'Die weiße Dame von Rothenberg', 'Die Gründung von Neu-Thann',
              'St. Theobaldus rettet Thann im Schwedenkriege', 'Das Ex Voto von der Kirche Alt-Thann',
              'Die gebannten Kriegsheere', 'Kaiser Barbarossa unter dem Bibelstein', 'Der Freier auf Freundstein',
              'Die Feldmesser auf dem Belchen', 'Die Gespenstertiere im Belchensee',
              'Wie Gebweiler gerettet ward. 1448',
              'Des Fürsten zu Murbach jäher Tod. 1477', 'Der Teufel auf Hugstein', 'Kunigunde von Hungerstein. 1487',
              'Der Schlangenkönig vom Heißenstein', 'Die Schwarze Frau am Heißenstein',
              'Die Alte auf der Barnabasbrücke', 'Der wundersame Käfer', 'Die Glocke von Bühl',
              'Die singende Jungfrau im Lauchthal', 'Die Erscheinung auf der Melkerei Hofrieth',
              'Ritter Kurt und die Kapelle von Ungersheim', 'St. Maria im Schäferthal', 'Der Langenstein bei Sulzmatt',
              'Die Stiftung des Klosters St. Valentin zu Rufach', 'St. Landolins Gut zu Rufach',
              'Die Weiber von Rufach',
              'Das Hungertuch in der Kirche von Rufach', 'Der Rufacher Galgen', 'Dem Teufel zu! 1721', 'Der Bollenberg',
              'Die Wallfahrt Schauenberg', 'Die Greifenklaue des heiligen Imerius', 'Bischof Friedrich von Zeringen',
              'Die Stiftung des Kloster Marbach', 'Graf Hugos Buße', 'Bruno von Egisheim',
              'Die Erscheinung in Pfeffels Garten', 'Die Erscheinung im Waschhause', 'Die gespenstische Milchfrau',
              'Das Nachtkalb', 'Warum die Colmarer Knöpfler heißen', 'Die Kornmutter', 'Frau Faste',
              'Die wilde Jagd bei Heilig-Kreuz', 'Der Hexenzug in der Hardt', 'Das Bruderhäuschen bei Widensolen',
              'Der Riese im Kastenwald', 'Warum der Logelbach zur Gemeinde Winzenheim gehört',
              'Die weiße Frau von Pflixburg', 'Die Wallfahrt zum Waldbruderkreuz am Grabe des heiligen Ignatius',
              'Die Entstehung des Bades Sulzbach', 'Die Zwerge auf dem Kerbholz', 'Die Schrätzmännel',
              'Der Grüne See im Münsterthale', 'Der Soldatenschlatten am Hoheneck', 'Der goldene Wagen',
              'Der Alte vom Berge', 'Die Wallfahrt Dreien-Aehren', 'Das Muttergottesbild zu Dreien-Aehren',
              'Das Riesengrab auf dem Hohnack', 'Das weiße Mädchen an der Fecht', 'Der Geist im Ingersheimer Schlosse',
              'Die Wöchnerin', 'Der Hungerbrunnen', 'St. Deodat',
              'Die Bilder der Muttergottes und des Evangelisten St. Johannes vergießen Thränen',
              'Kaiser Friedrich Barbarossa in Kaysersberg',
              'Die riesenmäßigen Holzschuhe auf dem Rathause zu Kaysersberg', 'Der Flieger', 'Die Teufelskutsche',
              'Die Tschäpläre', 'Das Pestkreuz bei Kaysersberg', 'Der feurige Kreis bei Rappoltsweiler',
              'Der Einsiedler von Alspach', 'Der weiße See', 'Der Zellenberger Burgersmann', 'Die heilige Hunna',
              'Das Wappen des Grafen von Rappoltstein', 'Die Brüder von Rappoltstein', 'Die Jungfrau auf St. Ulrich',
              'Die drei Schwestern von Rappoltstein', "Herni's Kreuz", 'Das Silberglöcklein und die Schloßhunde',
              'Die Gespensterkutsche von Hoh-Rappoltstein', 'Der Höllenhaken bei Rappoltsweiler', 'Der Hirzsprung',
              'Die Gründung von Dreikirchen oder Dusenbach', 'Die gespenstige Herde', 'Das Dorf Tannenkirch',
              'Das Dorftier von Tannenkirch', 'Die Here von Tannenkirch', 'Das gelbe Fräulein auf der Hohkönigsburg',
              'Die silberne Rose', 'Warum die Markircher Silberminen Nichts mehr abwerfen',
              'Der Jungfrauenplatz bei Markirch', 'Die Glocke von Leberau', 'Der Charlemont', 'qwertz']

    return titles


def get_dict_oberelsass():
    dict = {'Die Schlange im Jura': 'Jura', 'St Morands Ruhe': 'Altkirch', 'Der Käpellegeist': 'Heimersdorf',
            'Die Zwerge in der Wolfshöhle': 'Pfirt', 'Des Teufels Recht auf Pfirt': '',
            'Die Todtenprozession zu Luppach': 'Luppach', 'Die Galgenplatte': 'Alt-Pfirt', 'Der Lachgeist im Haag': '',
            'Der Geist Laxi im Biederthaler Schlosse': 'Biederthal', 'Junker Schnabel': 'Hagenthal',
            'Die Here von Köstlach': 'Köstlach', 'Das Herenschloß': 'Dürlinsdorf', 'Der Schmied im Berge': '',
            'Das versunkene Schloß Färis und der alte Graf': 'Mörnach', 'Die Herdwible von Mörnach': '',
            'Die Erbauung von Liebenstein': 'Liebsdorf', 'Der schwarze Vogel von Liebenstein': '',
            'Das Hündlein aus der wilden Jagd': '', 'Der Hausgeist geht zur Kelte': 'Oberlarg',
            'Die drei Spinnerinnen': '', 'Der Hexentanz auf der Kalmiſer Weide': '',
            'Das gefundene Silbergeld bei Mörsberg': '', 'Der Mann mit dem Lapphute zu Oberlarg': '',
            'Die weiße Frau am Goldigberg': 'Langizen', 'DasTotenpferd un dd ie Totenprozeſſion zu Moos': 'Moos',
            'Das Bildstöcklein bei Winkel': 'Winkel', 'Das Altschloß bei Winkel': 'Winkel',
            'Der Dornstrauch bei Neun-Eich': 'Lüzel', 'Das Silberloch bei Lüzel': '',
            'Die weiße Frau auf dem Küppele': 'Jufurt', 'Der Brißgyberg': '', 'Versenkte Glocken': 'Brubach, Didenheim',
            'Das Weingeigerlein von Brunstatt': 'Brunstatt', 'Das schwarze Tier am Mühlbach': '',
            'Die Gespensterheere im Nordfeld': 'Mülhausen', 'Kreuzregen': '', 'Himmelschweiß': '',
            'Der Schapgräber am Davidsbrünnlein': '', 'Die weiße Frau in grünen Pantoffeln': '',
            'Der verlorene Bräutigam': '', 'Der Milchsuppenacker': '',
            'Die Henne mit den goldenen Eiern in der St. Marykapelle bei Riedesheim': 'Riedesheim',
            'Das Dorftier zu Hegenheim': 'Hegenheim bei Hüningen', 'Die Geisterkirche auf dem Rhein': 'Kembs, Niffer',
            'Der weiße Mann vom Julzacher Schlosse': 'Julzach', 'Die weiße Jungfrau am Weiher': '',
            'Die weißen Mädchen an der Lindlache': '', 'Der schwarze Mann am Rain': '', 'Die Erscheinung am Rain': '',
            'Das weiße Pferd': '', 'Der Pferdeschatten am Rain': '', 'Der Nachtjäger': '',
            'Das Tucherle am Viertelssteg': '', 'Das Doggele': '', 'Das Fronfaſtentier': '', 'Der Dorfejel': '',
            'Der Milchbrunnen': '', 'Maria in der Eich': 'Rülisheim', 'Masmünsters Entstehung': 'Masmünster',
            'Der Lachtelweiher': 'Kirchberg bei Masmünster', 'Das Muttergottesbild in Sewen': 'Sewen',
            'Das Dambürle im Masmünsterthale': 'Masmünsterthal',
            'Die weiße Dame von Rothenberg': 'Rothenberg (Rougemont)', 'Die Gründung von Neu-Thann': 'Thann',
            'StTheobaldus rettet Thann im Schwedenkriege': 'Thann', 'Das Ex Voto in der Kirche zu Alt- Thann': '',
            'Die gebannten Kriegsheere': 'Sennheim', 'Kaiser Barbarossa unter dem Bibelstein': '',
            'Der Freier auf Freundstein': 'Weile br ei Thann', 'Die Feldmesser auf dem Belchen': 'Großer Belchen',
            'Gespenstertiere im Belchensee': '', 'Wie Gebweiler gerettet wurde': 'Gebweiler',
            'Des Fürsten zu Murbach jäher Tod': '', 'Der Teufel auf Hugſtein': '', 'Kunigunde von Hungerstein': '',
            'Der Schlangenkönig vom Heißenstein': '', 'Die schwarze Frau am Heißenſtein': '',
            'Die Alte auf der Barnabasbrücke': '', 'Der wundersame Käfer': 'Bühl bei Gebweiler',
            'Die Glocke von Bühl': '', 'Die singende Jungfrau im Lauchthal': '',
            'Die Erscheinung auf der Melkerei Hofrieth': '', 'Ritter Kurt und die Kapelle von Ungersheim': 'Ungersheim',
            'St Maria im Schäferthal': 'Sulzmatt', 'Der Langenſtein bei Sulzmatt': '',
            'DieStiftung des Klosters St. Valentin zu Rufach': 'Rufach', 'St Landolins Gut zu Rufach': '',
            'Die Weiber von Rufach': '', 'Das Hungertuch in der Kirche von Rufach': '', 'Der Rufacher Galgen': '',
            'Dem Teufel zu': '', 'Der Bollenberg': '', 'Die Wallfahrt Schauenberg': 'Geberschweier',
            'Die Greifenklaue des heiligen Imerius': '', 'Bischof Friedrich von Zeringen': '',
            'Stiftung des Klosters Marbach': '', 'Graf Hugos Buße': 'Egisheim', 'Bruno von Egisheim': '',
            'Die Erscheinung in Pfeffels Garten': 'Colmar', 'Die Erscheinung im Waschhause': '',
            'Die gespenstige Milchfrau': '', 'Das Nachtkalb': '', 'Warum die Colmarer Knöpfler heißen': '',
            'Die Kornmutter': 'Heiligkreuz bei Colmar', 'Frau Faste': '',
            'Die wilde Jagd bei Heiligkreuz': 'Heiligkreuz bei Colmar',
            'Der Hexenzug in der Hardt': 'Hettenschlag bei Neubreisach',
            'Das Bruderhäuschen bei Widenſolen': 'Widensolen bei Neubreisach', 'Der Riese im Kastenwald': 'Andolsheim',
            'Warum der Logelbach zur Gemeinde Winzenheim gehört': 'Logelbach bei Colmar',
            'Die weiße Frau von Pflixburg': 'Winzenheim',
            'Die Wallfahrt zum Waldbruderkreuz am Grabe des heiligen Ignatius': 'Zimmerbach',
            'Die Entstehung des Bades Sulzbach 84B': 'Sulzbach', 'Die Zwerge auf dem Kerbholz': 'Sulzern',
            'Die Schrägmännel': '', 'Der grüne See im Münsterthale': '', 'Der Soldatenschlatten am Hoheneck': '',
            'Der goldene Wagen': 'Mezeral', 'Der Alte vom Berge': 'Weier im Thale',
            'Die Wallfahrt Dreien Aehren': 'Drei Aehren', 'Das Muttergottesbild zu Dreien Aehren': '',
            'Das Riesengrab auf dem Hohnack': '', 'Das weiße Mädchen an der Fecht': 'Ingersheim',
            'Der Geist im Ingersheimer Schlosse': '', 'Die Wöchnerin': '', 'Der Hungerbrunnen': '',
            'St Deodat': 'Ammerschweier',
            'Die Bilder der Muttergottes und des Evangelisten St. Johannes vergießen Thränen': 'Kienzheim',
            'Kaiser Friedrich Barbarossa in Kaysersberg': 'Kaysersberg',
            'Die riesenmäßigen Holzschuhe auf dem Rathause zu Kaysersberg': '', 'Der Flieger': '',
            'Die Teufelskutsche': '', 'Die Tschäpläre': '', 'Das Pestkreuz bei Kaysersberg': '',
            'Der feurige Kreis im Kaysersberger Wald': '', 'Der Einsiedler von Alspach': 'Alspach bei Kaysersberg',
            'Der weiße See': 'Urbeis (Orbey)', 'Der Zellenberger Burgersmann': 'Reichenweier',
            'Die heilige Huna': 'Hunaweier', 'Das Wappen der Grafen von Rappoltstein': 'Rappoltsweiler',
            'Die Brüder von Rappoltstein': '', 'Die Jungfrau auf St. Ulric h': 'Rappoltsweiler',
            'Die drei Schwestern von Rappoltſtein': '', "Herni's Kreuz": '',
            'Das Silberglöcklein und die Schloßhunde': '', 'Die Gespensterkutſche von Hoh- Rappoltstein': '',
            'Der Höllenhaken bei Rappoltsweiler': '', 'Der Hirzsprung': '',
            'Die Gründung von Dreikirchen oder Duſenbach': '', 'Die gespenstige Herde': 'Elsenheim u Jllhäusern',
            'Das Dorf Tannenkirch': 'Lanneukirch', 'Das Dorftier von Tannenkirch': '', 'Die Here von Tannenkirch': '',
            'Das gelbe Fräulein auf der Hohkönigsburg': 'Hohlönigsburg bei Tannenkirch',
            'Die silberne Rose': 'Markirch', 'Warum die Markircher Silberminen Nichts mehr abwerfen': '',
            'Der Jungfrauenplaß bei Markirch': '', 'Die Glocke von Leberau': 'Leberau', 'Der Charlemont': ''}
    return dict
