import json
import re


def get_tei_header():
    MainTitle = "Pfälzisches Sagenbuch"
    SubTitle = None
    Author = "F. W. Hebel"
    PublicationYear = "1912"
    PublicationPlace = "Kaiserslautern, Germany"
    # PublicationCountry="Germany"
    Publisher = " Eugen Crusius Hofbuchhandlung"
    # Edition = "first"
    Edition = None
    source = "Sammlung von Sagen aus dem pfälzischen Bereich"

    Copyright = "CC0"
    encoder = "Ben Conrad, Dennis Binz"

    return [MainTitle, SubTitle, Author, PublicationYear, PublicationPlace, Publisher, Edition, source, Copyright,
            encoder]


def get_pkl():
    pickle_filename = "pfalz_sagen"
    return pickle_filename


def get_dict():
    titles = {'1. Die Geisterschlacht': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                         'I. Von Seelen, Geistern und Gespenstern.'],
              '2. Die Fahrt der Toten': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                         'I. Von Seelen, Geistern und Gespenstern.'],
              '3. Die überschiffenden Mönche': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                'I. Von Seelen, Geistern und Gespenstern.'],
              '4. Der ewige Jäger': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                     'I. Von Seelen, Geistern und Gespenstern.'],
              '5. Der Jägerpfuhl': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                    'I. Von Seelen, Geistern und Gespenstern.'],
              '6. Der wilde Jäger von Sponheim': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                  'I. Von Seelen, Geistern und Gespenstern.'],
              '7. Der wilde Jäger am Donnersberg': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                    'I. Von Seelen, Geistern und Gespenstern.'],
              '8. Der Lindenschmidt': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                       'I. Von Seelen, Geistern und Gespenstern.'],
              '9. Der Einaug vom Scharfeneck': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                'I. Von Seelen, Geistern und Gespenstern.'],
              '10. Der Geist vom Scharfeneck': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                'I. Von Seelen, Geistern und Gespenstern.'],
              '11. Hans Trapp': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                 'I. Von Seelen, Geistern und Gespenstern.'],
              '12. Das weiße Reh': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                    'I. Von Seelen, Geistern und Gespenstern.'],
              '13. Der Geist auf dem Bleifelsen': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                   'I. Von Seelen, Geistern und Gespenstern.'],
              '14. Der blutschwitzende Stein': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                'I. Von Seelen, Geistern und Gespenstern.'],
              '15. Der gebannte Geist': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                         'I. Von Seelen, Geistern und Gespenstern.'],
              '16. Der Irrwisch auf dem Klosterberg bei Winterbach': [
                  'A. Vom alten und neuen Glauben. (Mythische Sagen.)', 'I. Von Seelen, Geistern und Gespenstern.'],
              '17. Das Flämmchen': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                    'I. Von Seelen, Geistern und Gespenstern.'],
              '18. Der Schuß auf das Flämmchen': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                  'I. Von Seelen, Geistern und Gespenstern.'],
              '19. Der Geist auf dem Kieneck': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                'I. Von Seelen, Geistern und Gespenstern.'],
              '20. Der falsche Eid': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                      'I. Von Seelen, Geistern und Gespenstern.'],
              '21. Die Sage vom Maulus': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                          'I. Von Seelen, Geistern und Gespenstern.'],
              '22. Des Beilsteiners Umgang': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                              'I. Von Seelen, Geistern und Gespenstern.'],
              '23. Der Maire von Meisenheim': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                               'I. Von Seelen, Geistern und Gespenstern.'],
              '24. Das Mädchen vom Pauliner Schlößchen': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                          'I. Von Seelen, Geistern und Gespenstern.'],
              '25. Die unredliche Wirtin': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                            'I. Von Seelen, Geistern und Gespenstern.'],
              '26. Der Grenzsteinverrücker': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                              'I. Von Seelen, Geistern und Gespenstern.'],
              '27. Kanzel und Nonne': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                       'I. Von Seelen, Geistern und Gespenstern.'],
              '28. Das Nonnental bei Neustadt': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                 'I. Von Seelen, Geistern und Gespenstern.'],
              '29. Der Hund von Auerbach': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                            'I. Von Seelen, Geistern und Gespenstern.'],
              '30. Die Wassernixe zu Eschringen': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                   'II. Von Elfen und Nixen, Zwergen und Wichten.'],
              '31. Die schöne Tanne': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                       'II. Von Elfen und Nixen, Zwergen und Wichten.'],
              '32. Die drei Wiesenfräulein': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                              'II. Von Elfen und Nixen, Zwergen und Wichten.'],
              '33. Die drei Jungfrauen': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                          'II. Von Elfen und Nixen, Zwergen und Wichten.'],
              '34. Die drei Schwestern': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                          'II. Von Elfen und Nixen, Zwergen und Wichten.'],
              '35. Das Schloßfräulein': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                         'II. Von Elfen und Nixen, Zwergen und Wichten.'],
              '36. Der Schloßgarten auf dem Großen Stiefel': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                              'II. Von Elfen und Nixen, Zwergen und Wichten.'],
              '37. Die Schloßfrau und ihre Wäsche': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                     'II. Von Elfen und Nixen, Zwergen und Wichten.'],
              '38. Die weiße Dame vom Pauliner Schlößchen': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                             'II. Von Elfen und Nixen, Zwergen und Wichten.'],
              '39. Die Wildfrau': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                   'II. Von Elfen und Nixen, Zwergen und Wichten.'],
              '40. Das Wildfrauloch bei Schweinschied': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                         'II. Von Elfen und Nixen, Zwergen und Wichten.'],
              '41. Das Wildfrauenloch bei Schwarzerden': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                          'II. Von Elfen und Nixen, Zwergen und Wichten.'],
              '42. Das Lindenmütterchen': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                           'II. Von Elfen und Nixen, Zwergen und Wichten.'],
              '43. Die guten Zwerge': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                       'II. Von Elfen und Nixen, Zwergen und Wichten.'],
              '44. Das Graumännchensloch': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                            'II. Von Elfen und Nixen, Zwergen und Wichten.'],
              '45. Das graue Männchen': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                         'II. Von Elfen und Nixen, Zwergen und Wichten.'],
              '46. Der Ritter vom Huneberg': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                              'II. Von Elfen und Nixen, Zwergen und Wichten.'],
              '47. Das Kehrebacher Knüppchen': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                'II. Von Elfen und Nixen, Zwergen und Wichten.'],
              '48. Die Erdmännlein': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                      'II. Von Elfen und Nixen, Zwergen und Wichten.'],
              '49. Die Schlange und das Kind': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                'II. Von Elfen und Nixen, Zwergen und Wichten.'],
              '50. Die Schlangenkönigin': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                           'III. Von Dämonen und Göttern.'],
              '51. Der Drachenfels bei Dürkheim': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                   'III. Von Dämonen und Göttern.'],
              '52. Der Drachenfels bei Busenberg': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                    'III. Von Dämonen und Göttern.'],
              '53. Das wütende Heer': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                       'III. Von Dämonen und Göttern.'],
              '54. Die wilde Jagd': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                     'III. Von Dämonen und Göttern.'],
              '55. Vom Rosse des wilden Jägers': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                  'III. Von Dämonen und Göttern.'],
              '56. Die Riesen des Bliestales': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                'III. Von Dämonen und Göttern.'],
              '57. Die Riesen des Wasgenwaldes': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                  'III. Von Dämonen und Göttern.'],
              '58. Das Heidentürmchen zu Speyer': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                   'III. Von Dämonen und Göttern.'],
              '59. Der Riese Kreuzmann': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                          'III. Von Dämonen und Göttern.'],
              '60. Das Riesen- oder Hünengrab': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                 'III. Von Dämonen und Göttern.'],
              '61. Vom Gotte Wodan': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                      'III. Von Dämonen und Göttern.'],
              '62. Kolb von Wartenberg': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                          'III. Von Dämonen und Göttern.'],
              '63. Die Waldkapelle': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                      'III. Von Dämonen und Göttern.'],
              '64. Gott Donar und sein Gefährt': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                  'III. Von Dämonen und Göttern.'],
              '65. Der Burgbau auf dem Rheingrafenstein': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                           'IV. Von Teufeln, Hexen und Zauberern.'],
              '66. Der Teufelsstein': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                       'IV. Von Teufeln, Hexen und Zauberern.'],
              '67. Der Teufelstisch': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                       'IV. Von Teufeln, Hexen und Zauberern.'],
              '68. Der Teufelsberg': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                      'IV. Von Teufeln, Hexen und Zauberern.'],
              '69. Der Teufelsbrunnen': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                         'IV. Von Teufeln, Hexen und Zauberern.'],
              '70. Der Müller und der Teufel': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                'IV. Von Teufeln, Hexen und Zauberern.'],
              '71. Die Hexe vom Münstertal': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                              'IV. Von Teufeln, Hexen und Zauberern.'],
              '72. Die gebrannte Hexe': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                         'IV. Von Teufeln, Hexen und Zauberern.'],
              '73. Die diebische Hexe': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                         'IV. Von Teufeln, Hexen und Zauberern.'],
              '74. Das Hexengewitter': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                        'IV. Von Teufeln, Hexen und Zauberern.'],
              '75. Der Hexenball': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                    'IV. Von Teufeln, Hexen und Zauberern.'],
              '76. Hexentanz und Hexenkraut': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                               'IV. Von Teufeln, Hexen und Zauberern.'],
              '77. Der Zauberschüße Punker von Rohrbach': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                           'IV. Von Teufeln, Hexen und Zauberern.'],
              '78. Der Schnittlfelsen': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                         'IV. Von Teufeln, Hexen und Zauberern.'],
              '79. Der Heidenfelsen': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                       'IV. Von Teufeln, Hexen und Zauberern.'],
              '80. Der krumme Dallacker': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                           'IV. Von Teufeln, Hexen und Zauberern.'],
              '81. Der Stab des Klausners': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                             'V. Von Zeichen und Wundern.'],
              '82. Das Marienbild zu Gräfinthal': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                   'V. Von Zeichen und Wundern.'],
              '83. Das Muttergottesbild zu Forst': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                    'V. Von Zeichen und Wundern.'],
              '84. Das Marienbild zu Ranschbach': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                   'V. Von Zeichen und Wundern.'],
              '85. Das fromme Knäblein zu Speyer': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                    'V. Von Zeichen und Wundern.'],
              '86. Das Marienbild im Dom zu Speyer': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                      'V. Von Zeichen und Wundern.'],
              '87. Der rauschende Kelch im Speyerer Dom': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                           'V. Von Zeichen und Wundern.'],
              '88. Die Maria-Hilf-Kapelle auf dem Kolmerberg': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                                'V. Von Zeichen und Wundern.'],
              '89. Die Kapelle und das Glöckchen des hl. Cyriakus': [
                  'A. Vom alten und neuen Glauben. (Mythische Sagen.)', 'V. Von Zeichen und Wundern.'],
              '90. Der hl. Cyriakus und der Wingertsbalken': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                              'V. Von Zeichen und Wundern.'],
              '91. Die Strutelpeters-Kapelle': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                'V. Von Zeichen und Wundern.'],
              '92. Die St. Lorenzkapelle': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                            'V. Von Zeichen und Wundern.'],
              '93. Das goldene Kreuz im Klosterweiher': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                         'V. Von Zeichen und Wundern.'],
              '94. Der Servatiusbrunnen': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                           'V. Von Zeichen und Wundern.'],
              '95. Der Lorenzenbrunnen': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                          'V. Von Zeichen und Wundern.'],
              '96. Die Wunder des hl. Philipp von Zell': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                          'V. Von Zeichen und Wundern.'],
              '97. Die Glocken zu Speyer': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                            'VI. Von Glocken und Schätzen.'],
              '98. Die fliegende Glocke': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                           'VI. Von Glocken und Schätzen.'],
              '99. Die große Glocke von Neustadt': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                    'VI. Von Glocken und Schätzen.'],
              '100. Die Glocke von Lindesheim': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                 'VI. Von Glocken und Schätzen.'],
              '101. Das versunkene Glöcklein': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                'VI. Von Glocken und Schätzen.'],
              '102. Die vergrabenen Glocken': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                               'VI. Von Glocken und Schätzen.'],
              '103. Die goldene Orgel': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                         'VI. Von Glocken und Schätzen.'],
              '104. Das goldene Kegelspiel': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                              'VI. Von Glocken und Schätzen.'],
              '105. Der Schatz zu Beilstein': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                               'VI. Von Glocken und Schätzen.'],
              '106. Das weiße Fräulein an der dicken Eiche': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                              'VI. Von Glocken und Schätzen.'],
              '107. Die Schätze zu Wilenstein': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                 'VI. Von Glocken und Schätzen.'],
              '108. Der Stolzenberger Schatz': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                'VI. Von Glocken und Schätzen.'],
              '109. Der weiße Peter': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                       'VI. Von Glocken und Schätzen.'],
              '110. Der Schatz auf dem Disibodenberg': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                        'VI. Von Glocken und Schätzen.'],
              '111. Der Schatz auf Hohenfels': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                'VI. Von Glocken und Schätzen.'],
              '112. Der Schatz zu Rotenkirchen': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                  'VI. Von Glocken und Schätzen.'],
              '113. Der Schatz auf Scharfeneck': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                  'VI. Von Glocken und Schätzen.'],
              '114. Die Juden und der Schatz': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                'VI. Von Glocken und Schätzen.'],
              '115. Die Heidenburg': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                      'VI. Von Glocken und Schätzen.'],
              '116. Der Krötenstuhl': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                       'VI. Von Glocken und Schätzen.'],
              '117. Der Klosterbrunnen bei Pirmasens': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                        'VI. Von Glocken und Schätzen.'],
              '118. Der Bauer und der Schatz': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                'VI. Von Glocken und Schätzen.'],
              '119. Die vergessene Schlüsselblume': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                     'VI. Von Glocken und Schätzen.'],
              '120. Die Schätze im Innern des Kirkeler Bergs': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                                'VI. Von Glocken und Schätzen.'],
              '121. Der Birkenbusch auf Kirkel': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                  'VI. Von Glocken und Schätzen.'],
              '122. Die unterirdischen Schätze im Pauliner Schlößchen': [
                  'A. Vom alten und neuen Glauben. (Mythische Sagen.)', 'VI. Von Glocken und Schätzen.'],
              '123. In Gold verwandelte Porzellanscherben': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                             'VI. Von Glocken und Schätzen.'],
              '124. Das weiße Fräulein auf der Leinbachmühle': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                                'VI. Von Glocken und Schätzen.'],
              '125. Der entgangene Schatz': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                             'VI. Von Glocken und Schätzen.'],
              '126. Der gehobene Schatz': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                           'VI. Von Glocken und Schätzen.'],
              '127. Das Glühhäuschen': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                        'VI. Von Glocken und Schätzen.'],
              '128. Die Glut': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)', 'VI. Von Glocken und Schätzen.'],
              '129. Die blaue Flamme': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                        'VI. Von Glocken und Schätzen.'],
              '130. Die Heidenmauer': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.', 'IVI. Ohne Gruppe'],
              '131. Attilas Grab': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.', 'IVI. Ohne Gruppe'],
              '132. Wie die Heidenburg fiel': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                               'IVI. Ohne Gruppe'],
              '133. Kaiser Adolfs Tod': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                         'IVI. Ohne Gruppe'], '134. Wie die Bauern Schloß Lindelbrunn nahmen': [
            'B. Von pfälzischer Landes-, Orts- und Familiengeschichte.', 'IVI. Ohne Gruppe'],
              '135. Die Bauern auf Neuleiningen': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                   'IVI. Ohne Gruppe'],
              '136. Das Klösterlein zu Fischbach': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                    'IVI. Ohne Gruppe'],
              '137. Der Hirt von Oggersheim': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                               'IVI. Ohne Gruppe'],
              '138. Die Mordkammer': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.', 'IVI. Ohne Gruppe'],
              '139. Zerstörung des Klosters St. Medard': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                          'I. Von Kriegen und Fehden und anderen Nöten.'],
              '140. Belagerung von Burg Lichtenberg': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                       'I. Von Kriegen und Fehden und anderen Nöten.'],
              '141. Neustadts Retterin': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                          'I. Von Kriegen und Fehden und anderen Nöten.'],
              '142. Der Metallfühler': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                        'I. Von Kriegen und Fehden und anderen Nöten.'],
              '143. Jammerhalde und Hahnenfalz': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                  'I. Von Kriegen und Fehden und anderen Nöten.'],
              '144. Der Trompeter an der dicken Eiche': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                         'I. Von Kriegen und Fehden und anderen Nöten.'],
              '145. Der tote Soldat': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                       'I. Von Kriegen und Fehden und anderen Nöten.'],
              '146. Der heimgekehrte Krieger': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                'I. Von Kriegen und Fehden und anderen Nöten.'],
              '147. Nächtliche Erscheinung zu Speyer': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                        'I. Von Kriegen und Fehden und anderen Nöten.'],
              '148. Wie du willt, Melchior': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                              'I. Von Kriegen und Fehden und anderen Nöten.'],
              '149. Treuenfels': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                  'I. Von Kriegen und Fehden und anderen Nöten.'],
              '150. Der Eberkopf': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                    'I. Von Kriegen und Fehden und anderen Nöten.'],
              '151. Der Mönchskopf': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                      'I. Von Kriegen und Fehden und anderen Nöten.'],
              '152. Die Grafen von Eberstein': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                'I. Von Kriegen und Fehden und anderen Nöten.'],
              '153. Die Burgfrau von Berwartstein': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                     'I. Von Kriegen und Fehden und anderen Nöten.'],
              '154. Der böse Wolfsberger': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                            'I. Von Kriegen und Fehden und anderen Nöten.'],
              '155. Das Grab Noes und die Pest': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                  'I. Von Kriegen und Fehden und anderen Nöten.'],
              '156. Entstehung von Kaiserslautern': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                     'II. Von Gründungen, Stiftungen und Ortsbenennungen.'],
              '157. Schloß und Dorf Neidenfels': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                  'II. Von Gründungen, Stiftungen und Ortsbenennungen.'],
              '158. Kehrdichannichts, Murmelnichtviel, Schaudichnichtum': [
                  'B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                  'II. Von Gründungen, Stiftungen und Ortsbenennungen.'],
              '159. Entstehung von Bad Diedelkopf': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                     'II. Von Gründungen, Stiftungen und Ortsbenennungen.'],
              '160. Gründung Kreuznachs': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                           'II. Von Gründungen, Stiftungen und Ortsbenennungen.'],
              '161. Gründung des Klosters Difibodenberg': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                           'II. Von Gründungen, Stiftungen und Ortsbenennungen.'],
              '162. Stiftung von Klingenmünster': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                   'II. Von Gründungen, Stiftungen und Ortsbenennungen.'],
              '163. Limburgs Entstehung': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                           'II. Von Gründungen, Stiftungen und Ortsbenennungen.'],
              '164. Das Kloster Rosenthal': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                             'II. Von Gründungen, Stiftungen und Ortsbenennungen.'],
              '165. Die Rosentreppe': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                       'II. Von Gründungen, Stiftungen und Ortsbenennungen.'],
              '166. Der Roßsprung bei Speyer': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                'II. Von Gründungen, Stiftungen und Ortsbenennungen.'],
              '167. Das Fuchsloch oder Gnadenwasser bei Zeiskam': [
                  'B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                  'II. Von Gründungen, Stiftungen und Ortsbenennungen.'],
              '168. Die Felsenkirche zu Oberstein': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                     'II. Von Gründungen, Stiftungen und Ortsbenennungen.'],
              '169. Der Abt Jakob von Hornbach': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                  'II. Von Gründungen, Stiftungen und Ortsbenennungen.'],
              '170. Das Dietrichskirchel': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                            'II. Von Gründungen, Stiftungen und Ortsbenennungen.'],
              '171. Die verkehrte Kirche': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                            'II. Von Gründungen, Stiftungen und Ortsbenennungen.'],
              '172. Die Wolfskirche bei Bosenbach': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                     'II. Von Gründungen, Stiftungen und Ortsbenennungen.'],
              '173. Das Kind von der Falkenburg': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                   'II. Von Gründungen, Stiftungen und Ortsbenennungen.'],
              '174. Die Peternell bei Bergzabern': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                    'II. Von Gründungen, Stiftungen und Ortsbenennungen.'],
              '175. Die Dagobertshecke und die Haingeraiden': [
                  'B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                  'II. Von Gründungen, Stiftungen und Ortsbenennungen.'],
              '176. Des Remigs Teil vom Wafichenwald': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                        'II. Von Gründungen, Stiftungen und Ortsbenennungen.'],
              '177. Das steinerne Kreuz': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                           'III. Von Kreuzen und Steinen, von'],
              '178. Das gläserne Kreuz': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                          'III. Von Kreuzen und Steinen, von'],
              '179. Das Steinkreuz im Walde': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                               'III. Von Kreuzen und Steinen, von'],
              '180. Das weiße Kreuz im Bienwald': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                   'III. Von Kreuzen und Steinen, von'],
              '181. Sickingens Würfel': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                         'III. Von Kreuzen und Steinen, von'],
              '182. Der Abtstein': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                    'III. Von Kreuzen und Steinen, von'],
              '183. Der Hohe Stein': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                      'III. Von Kreuzen und Steinen, von'],
              '184. Der Gollenstein': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                       'III. Von Kreuzen und Steinen, von'],
              '185. Ein Grabstein in der St. Johanniskirche zu Dürkheim': [
                  'B. Von pfälzischer Landes-, Orts- und Familiengeschichte.', 'III. Von Kreuzen und Steinen, von'],
              '186. Der Reitersprung': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                        'III. Von Kreuzen und Steinen, von'],
              '187. Kühner Sprung': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                     'III. Von Kreuzen und Steinen, von'],
              '188. Der Jungfernsprung bei Battenberg': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                         'III. Von Kreuzen und Steinen, von'],
              '189. Der Jungfernsprung bei Dahn': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                   'III. Von Kreuzen und Steinen, von'],
              '190. Der Wolfsfels': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                     'III. Von Kreuzen und Steinen, von'],
              '191. Die Hirschtrabe': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                       'III. Von Kreuzen und Steinen, von'],
              '192. Der Nonnenfels': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                      'III. Von Kreuzen und Steinen, von'],
              '193. Das Frifraloch bei Offenbach am Glan': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                            'III. Von Kreuzen und Steinen, von'],
              '194. Die Heidenhöhle': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                       'III. Von Kreuzen und Steinen, von'],
              '195. Das Affolterloch': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                        'III. Von Kreuzen und Steinen, von'],
              '196. Der Maidenbrunnen': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                         'III. Von Kreuzen und Steinen, von'],
              '197. Der Reiterbrunnen': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                         'III. Von Kreuzen und Steinen, von'],
              '198. Der tiefe Brunnen': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                         'III. Von Kreuzen und Steinen, von'],
              '199. Wasserberg und tiefer Brunnen': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                     'III. Von Kreuzen und Steinen, von'],
              '200. Von drei Brunnen': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                        'III. Von Kreuzen und Steinen, von'],
              '201. Der Hungerbrunnen bei Kaiserslautern': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                            'III. Von Kreuzen und Steinen, von'],
              '202. Die Silbergrube': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                       'IV. Vom heimischen Bergbau.'],
              '203. Die Erzgrube im Langental': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                 'IV. Vom heimischen Bergbau.'],
              '204. Die drei Züge': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                     'IV. Vom heimischen Bergbau.'],
              '205. Ernesti-Glück': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                     'IV. Vom heimischen Bergbau.'],
              '206. Die Geißkammer': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                      'IV. Vom heimischen Bergbau.'],
              '207. Der Kampf am Wasgenstein': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                'V. Von Helden, Geschlechtern und Wappen.'],
              '208. Keiser Friderich zu Keiserslautern': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                          'V. Von Helden, Geschlechtern und Wappen.'],
              '209. Des Kaisers Bett': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                        'V. Von Helden, Geschlechtern und Wappen.'],
              '210. Der Hecht im Kaiserwoog': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                               'V. Von Helden, Geschlechtern und Wappen.'],
              '211. Der Ritter von Beilstein': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                'V. Von Helden, Geschlechtern und Wappen.'],
              '212. Das Hufeisen zu Kaiserslautern': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                      'V. Von Helden, Geschlechtern und Wappen.'],
              '213. Warum die Kaiser im Dom zu Speyer bestattet wurden': [
                  'B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                  'V. Von Helden, Geschlechtern und Wappen.'],
              '214. Kaiser Rudolfs Ritt zum Grabe': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                     'V. Von Helden, Geschlechtern und Wappen.'],
              '215. Kaiser Heinrich IV. zu Böckelheim': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                         'V. Von Helden, Geschlechtern und Wappen.'],
              '216. Der Lindenplatz auf Hartenburg': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                      'V. Von Helden, Geschlechtern und Wappen.'],
              '217. Die Göllheimer Ulme': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                           'V. Von Helden, Geschlechtern und Wappen.'],
              '218. Die Tschiffliker Kirschen': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                 'V. Von Helden, Geschlechtern und Wappen.'],
              '219. Der Pfeil': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                 'V. Von Helden, Geschlechtern und Wappen.'],
              '220. Der Löwe im pfälzischen und bayerischen Wappen': [
                  'B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                  'V. Von Helden, Geschlechtern und Wappen.'], '221. Raugraf Heinrich und Maria von Brabant': [
            'B. Von pfälzischer Landes-, Orts- und Familiengeschichte.', 'V. Von Helden, Geschlechtern und Wappen.'],
              '222. Franz von Sickingen und der Geist vom Rotenfelsen': [
                  'B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                  'V. Von Helden, Geschlechtern und Wappen.'],
              '223. Der alte Ruppert vom Ruppertsfelsen': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                           'V. Von Helden, Geschlechtern und Wappen.'],
              '224. Das Kloster Seebach': ['C. Von allerlei Gutem und Bösem. (Ethische Sagen.)',
                                           'I. Von mancherlei Treue und Verrat.'],
              '225. Das Kloster Marienstein': ['C. Von allerlei Gutem und Bösem. (Ethische Sagen.)',
                                               'I. Von mancherlei Treue und Verrat.'],
              '226. Die Brautfahrt': ['C. Von allerlei Gutem und Bösem. (Ethische Sagen.)',
                                      'I. Von mancherlei Treue und Verrat.'],
              '227. Weibestreue': ['C. Von allerlei Gutem und Bösem. (Ethische Sagen.)',
                                   'I. Von mancherlei Treue und Verrat.'],
              '228. Das Fräulein mit dem steinernen Herzen': ['C. Von allerlei Gutem und Bösem. (Ethische Sagen.)',
                                                              'I. Von mancherlei Treue und Verrat.'],
              '229. Die Lilie zu Altenbaumberg': ['C. Von allerlei Gutem und Bösem. (Ethische Sagen.)',
                                                  'I. Von mancherlei Treue und Verrat.'],
              '230. Die gelben Schlüsselblumen': ['C. Von allerlei Gutem und Bösem. (Ethische Sagen.)',
                                                  'I. Von mancherlei Treue und Verrat.'],
              '231. Hildegard von Hoheneck': ['C. Von allerlei Gutem und Bösem. (Ethische Sagen.)',
                                              'I. Von mancherlei Treue und Verrat.'],
              '232. Das Fräulein von Wilenstein': ['C. Von allerlei Gutem und Bösem. (Ethische Sagen.)',
                                                   'I. Von mancherlei Treue und Verrat.'],
              '233. Schön Elsbeth von der Kästenburg': ['C. Von allerlei Gutem und Bösem. (Ethische Sagen.)',
                                                        'I. Von mancherlei Treue und Verrat.'],
              '234. Richard Löwenherz auf Trifels': ['C. Von allerlei Gutem und Bösem. (Ethische Sagen.)',
                                                     'I. Von mancherlei Treue und Verrat.'],
              '235. Das Pfälzer Weberlein': ['C. Von allerlei Gutem und Bösem. (Ethische Sagen.)',
                                             'I. Von mancherlei Treue und Verrat.'],
              '236. Das ehrliche Weberlein zu Zeiskam': ['C. Von allerlei Gutem und Bösem. (Ethische Sagen.)',
                                                         'I. Von mancherlei Treue und Verrat.'],
              '237. Der Junker von Randeck': ['C. Von allerlei Gutem und Bösem. (Ethische Sagen.)',
                                              'I. Von mancherlei Treue und Verrat.'],
              '238. Der böse Scharfenecker': ['C. Von allerlei Gutem und Bösem. (Ethische Sagen.)',
                                              'I. Von mancherlei Treue und Verrat.'],
              '239. Die lederne Brücke': ['C. Von allerlei Gutem und Bösem. (Ethische Sagen.)',
                                          'I. Von mancherlei Treue und Verrat.'],
              '240. Des Spangenbergers Sohn': ['C. Von allerlei Gutem und Bösem. (Ethische Sagen.)',
                                               'I. Von mancherlei Treue und Verrat.'],
              '241. Der Raub der Monstranz': ['C. Von allerlei Gutem und Bösem. (Ethische Sagen.)',
                                              'II. Von übler Taten Lohn.'],
              '242. Der Raubritter Wynant': ['C. Von allerlei Gutem und Bösem. (Ethische Sagen.)',
                                             'II. Von übler Taten Lohn.'],
              '243. Die Falkensteiner Blutnelken': ['C. Von allerlei Gutem und Bösem. (Ethische Sagen.)',
                                                    'II. Von übler Taten Lohn.'],
              '244. Kaspar von Spangenberg': ['C. Von allerlei Gutem und Bösem. (Ethische Sagen.)',
                                              'II. Von übler Taten Lohn.'],
              '245. Das Mordloch': ['C. Von allerlei Gutem und Bösem. (Ethische Sagen.)', 'II. Von übler Taten Lohn.'],
              '246. Der Mutter Fluch': ['C. Von allerlei Gutem und Bösem. (Ethische Sagen.)',
                                        'II. Von übler Taten Lohn.'],
              '247. Der ewige Fuhrmannsweg': ['C. Von allerlei Gutem und Bösem. (Ethische Sagen.)',
                                              'II. Von übler Taten Lohn.'],
              '248. Junker Elz von Wecklingen': ['C. Von allerlei Gutem und Bösem. (Ethische Sagen.)',
                                                 'II. Von übler Taten Lohn.'],
              '249. Die Hand des Toten': ['C. Von allerlei Gutem und Bösem. (Ethische Sagen.)',
                                          'II. Von übler Taten Lohn.'],
              '250. Die unverwelkliche Hand': ['C. Von allerlei Gutem und Bösem. (Ethische Sagen.)',
                                               'II. Von übler Taten Lohn.'],
              '251. Die Edelfräulein zu Altdorf': ['C. Von allerlei Gutem und Bösem. (Ethische Sagen.)',
                                                   'II. Von übler Taten Lohn.'],
              '252. Der böse Bischof und der getreue Hutzmann': ['C. Von allerlei Gutem und Bösem. (Ethische Sagen.)',
                                                                 'II. Von übler Taten Lohn.'],
              '253. Das Balkemännel': ['C. Von allerlei Gutem und Bösem. (Ethische Sagen.)',
                                       'II. Von übler Taten Lohn.'],
              '254. Der Mann im Monde': ['C. Von allerlei Gutem und Bösem. (Ethische Sagen.)',
                                         'II. Von übler Taten Lohn.'],
              '255. Der böse Müller': ['C. Von allerlei Gutem und Bösem. (Ethische Sagen.)',
                                       'II. Von übler Taten Lohn.'],
              '256. Der Eremit auf dem Rosenberg': ['C. Von allerlei Gutem und Bösem. (Ethische Sagen.)',
                                                    'II. Von übler Taten Lohn.'],
              '257. Das versunkene Kloster': ['C. Von allerlei Gutem und Bösem. (Ethische Sagen.)',
                                              'II. Von übler Taten Lohn.'],
              '258. Woher die Pfalz ihren Namen hat': ['D. Von Schalkheit und Torheit. (Humoristische Sagen.)',
                                                       'I. Von Orts- und Spitznamen.'],
              '259. Wie vier ehemals Guttenbergische Dörfer ihre Namen erhielten': [
                  'D. Von Schalkheit und Torheit. (Humoristische Sagen.)', 'I. Von Orts- und Spitznamen.'],
              '260. Noch zwei andere Ortsnamen': ['D. Von Schalkheit und Torheit. (Humoristische Sagen.)',
                                                  'I. Von Orts- und Spitznamen.'],
              '261. Warum die Pfälzer Krischer heißen': ['D. Von Schalkheit und Torheit. (Humoristische Sagen.)',
                                                         'I. Von Orts- und Spitznamen.'],
              '262. Die Sausenheimer "Essel"': ['D. Von Schalkheit und Torheit. (Humoristische Sagen.)',
                                                'I. Von Orts- und Spitznamen.'],
              '263. Die Oppauer "Dampfnudelstürmer"': ['D. Von Schalkheit und Torheit. (Humoristische Sagen.)',
                                                       'I. Von Orts- und Spitznamen.'],
              '264. Die Friesenheimer "Eulen"': ['D. Von Schalkheit und Torheit. (Humoristische Sagen.)',
                                                 'I. Von Orts- und Spitznamen.'],
              '265. Annweilers Name und Spottname': ['D. Von Schalkheit und Torheit. (Humoristische Sagen.)',
                                                     'I. Von Orts- und Spitznamen.'],
              '266. Der Sammetärmel von Annweiler': ['D. Von Schalkheit und Torheit. (Humoristische Sagen.)',
                                                     'I. Von Orts- und Spitznamen.'],
              '267. Was der Teufel verlor': ['D. Von Schalkheit und Torheit. (Humoristische Sagen.)',
                                             'I. Von Orts- und Spitznamen.'],
              '268. Der Hofnarr von Münster': ['D. Von Schalkheit und Torheit. (Humoristische Sagen.)',
                                               'II. Von Streichen und Schwänken.'],
              '269. Der Pfarrer von Grumbach': ['D. Von Schalkheit und Torheit. (Humoristische Sagen.)',
                                                'II. Von Streichen und Schwänken.'],
              '270. Die dicke Landgräfin': ['D. Von Schalkheit und Torheit. (Humoristische Sagen.)',
                                            'II. Von Streichen und Schwänken.'],
              '271. Der Trunk aus dem Stiefel': ['D. Von Schalkheit und Torheit. (Humoristische Sagen.)',
                                                 'II. Von Streichen und Schwänken.'],
              '272. Der durstige Abt': ['D. Von Schalkheit und Torheit. (Humoristische Sagen.)',
                                        'II. Von Streichen und Schwänken.'],
              '273. Der Weinkampf zu Wachenheim': ['D. Von Schalkheit und Torheit. (Humoristische Sagen.)',
                                                   'II. Von Streichen und Schwänken.'],
              '274. Der Gescheideste': ['D. Von Schalkheit und Torheit. (Humoristische Sagen.)',
                                        'II. Von Streichen und Schwänken.'],
              '275. Des Pfalzgrafen Hirschjagd': ['D. Von Schalkheit und Torheit. (Humoristische Sagen.)',
                                                  'II. Von Streichen und Schwänken.'],
              '276. Der Reiterlud von Iggelheim': ['D. Von Schalkheit und Torheit. (Humoristische Sagen.)',
                                                   'II. Von Streichen und Schwänken.'],
              '277. Die Kugeltaufe zu Ebernburg': ['D. Von Schalkheit und Torheit. (Humoristische Sagen.)',
                                                   'II. Von Streichen und Schwänken.'],
              '278. Der pfälzische Eulenspiegel': ['D. Von Schalkheit und Torheit. (Humoristische Sagen.)',
                                                   'II. Von Streichen und Schwänken.'],
              '279. Das Eselsei': ['D. Von Schalkheit und Torheit. (Humoristische Sagen.)',
                                   'III. Vom pfälzischen Schilda.'],
              '280. Das neue Schulhaus': ['D. Von Schalkheit und Torheit. (Humoristische Sagen.)',
                                          'III. Vom pfälzischen Schilda.'],
              '281. Der englische Schneider': ['D. Von Schalkheit und Torheit. (Humoristische Sagen.)',
                                               'III. Vom pfälzischen Schilda.'],
              '282. Die Adjunkten-Wahl': ['D. Von Schalkheit und Torheit. (Humoristische Sagen.)',
                                          'III. Vom pfälzischen Schilda.'],
              '283. Wie tief ist der Brunnen?': ['D. Von Schalkheit und Torheit. (Humoristische Sagen.)',
                                                 'III. Vom pfälzischen Schilda.']}

    locs = [['Bad Dürkheim', 49.4618, 8.17236], ['Kaiserslautern', 49.443, 7.77161], ['Speyer', 49.33049, 8.19983],
            ['Bliesbolchen', 49.15374, 7.11467], ['Erfweiler', 49.19662, 7.18454], ['Sponheim', 49.84496, 7.72665],
            ['Donnersberg', 49.6, 7.95], ['Frankenthal', 49.53414, 8.35357], ['Dernbach', 50.55, 7.6],
            ['Dernbach', 50.55, 7.6], ['Berwartstein', 'NaN'], ['Dannenfels', 49.62868, 7.94355],
            ['Neustadt an der Haardt', 49.35009, 8.13886], ['Kaiserslautern', 49.443, 7.77161],
            ['Medard a. Glan', 'NaN'], ['Biedershausen', 49.31667, 7.48333], ['Rhodt', 49.26972, 8.10778],
            ['Kottweiler', 49.46667, 7.53333], ['Münchweiler an der Alsenz', 49.55, 7.88333],
            ['Finkenbach', 49.68333, 7.75], ['Klingenmünster', 49.14056, 8.01861], ['Beilstein', 50.11667, 7.25],
            ['Meisenheim', 49.70721, 7.66765], ['NaN', 'NaN'], ['Homburg', 49.32637, 7.33867],
            ['Jägersburg', 49.36896, 7.32376], ['Niederauerbach', 49.2572, 7.39403],
            ['Neustadt an der Haardt', 49.35009, 8.13886], ['Niederauerbach', 49.2572, 7.39403],
            ['Ensheim', 49.80639, 8.11556], ['Offenbach a. Glan', 'NaN'], ['Ensheim', 49.80639, 8.11556],
            ['Ehlingen', 49.19677, 7.17664], ['Busenberg', 49.13024, 7.8293], ['Großer Stiefel', 'NaN'],
            ['Großer Stiefel', 'NaN'], ['Pauliner Schlößchen', 'NaN'], ['NaN', 'NaN'], ['Frohnerbacherhof', 'NaN'],
            ['Schweinschied', 49.7, 7.56667], ['Kusel', 49.53772, 7.40472], ['Lindelbrunn', 'NaN'],
            ['Ensheim', 49.80639, 8.11556], ['Bischmisheim', 49.22158, 7.06897], ['Pirmasens', 49.19211, 7.85492],
            ['Huneberg', 'NaN'], ['Rheingrafenstein', 'NaN'], ['Hagenbach', 49.01734, 8.25024],
            ['Harzofen', 49.36143, 7.95206], ['Erzhütten', 49.45833, 7.7324], ['Bad Dürkheim', 49.4618, 8.17236],
            ['Buhlstein', 'NaN'], ['Pirmasens', 49.19211, 7.85492], ['Friedrichsthal', 49.32786, 7.09622],
            ['Königsberg bei Wolfstein', 'NaN'], ['Bliestal', 'NaN'], ['Wasgenwald', 'NaN'],
            ['Speyer', 49.33049, 8.19983], ['Großer Stiefel', 'NaN'], ['Buren', 'NaN'],
            ['Rodenbach b. Kaisersl.', 'NaN'], ['Wartenberg', 49.53333, 7.85], ['Kaiserslautern', 49.443, 7.77161],
            ['Donnersberg', 49.6, 7.95], ['Rheingrafenstein', 'NaN'], ['Limburg', 49.42444, 8.39194],
            ['Dahn', 49.15098, 7.77843], ['Burrweiler', 49.24778, 8.07833], ['Einöd', 49.27251, 7.31638],
            ['Kirchheim', 49.53722, 8.18083], ['Freilaubersheim', 'NaN'], ['Wolfstein', 49.58411, 7.60496],
            ['NaN', 'NaN'], ['Oggersheim', 49.4925, 8.36833], ['Sickinger Gegend', 'NaN'], ['Niederlauterbach', 'NaN'],
            ['Lindelbrunn', 'NaN'], ['Erlenbach b. Dahn', 'NaN'], ['Erlenbach b. Dahn', 'NaN'],
            ['Königsberg bei Neustadt a. H.', 'NaN'], ['Donnersberg', 49.6, 7.95], ['Blieskastel', 49.23724, 7.25617],
            ['NaN', 'NaN'], ['Leinsweiler', 49.18333, 8.01917], ['Speyer', 49.33049, 8.19983],
            ['Speyer', 49.33049, 8.19983], ['Speyer', 49.33049, 8.19983], ['Dörrenbach', 49.43378, 7.23523],
            ['Cyriakuskapelle', 'NaN'], ['Cyriakuskapelle', 'NaN'], ['Blieskastel', 49.23724, 7.25617],
            ['Eschringen', 49.18894, 7.10149], ['Niederhochstadt', 49.242, 8.21828], ['Servatiusbrunnen', 'NaN'],
            ['Göllheim', 49.595, 8.05083], ['Enkenbach', 49.48333, 7.88333], ['Speyer', 49.33049, 8.19983],
            ['Aschbach b. Kaiserslautern', 'NaN'], ['Königsberg bei Neustadt a. H.', 'NaN'],
            ['Colgenstein', 49.58692, 8.20478], ['Eschringen', 49.18894, 7.10149], ['Albersweiler', 49.21917, 8.03],
            ['Albersweiler', 49.21917, 8.03], ['Altdahn', 'NaN'], ['Beilstein', 50.11667, 7.25],
            ['Enkenbach', 49.48333, 7.88333], ['Karlstal', 'NaN'], ['Bayerfeld-Cölln', 'NaN'],
            ['Wachenheim', 49.44045, 8.18041], ['Disibodenberg', 'NaN'], ['Donnersberg', 49.6, 7.95],
            ['Kirchheimbolanden', 49.66249, 8.01513], ['Dernbach', 50.55, 7.6], ['Börsborn', 49.43333, 7.4],
            ['Heidenburg bei Oberstaufenbach', 'NaN'], ['Fleckenstein', 'NaN'], ['Pirmasens', 49.19211, 7.85492],
            ['Großer Stiefel', 'NaN'], ['Großer Stiefel', 'NaN'], ['Kirkel', 49.28333, 7.23333],
            ['Kirkel', 49.28333, 7.23333], ['Pauliner Schlößchen', 'NaN'], ['Pauliner Schlößchen', 'NaN'],
            ['Frankenstein', 49.44015, 7.97744], ['Altwolfstein', 'NaN'], ['Annweiler', 49.20613, 7.97527],
            ['Kaiserslautern', 49.443, 7.77161], ['Erzenhausen', 49.5, 7.61667], ['Finkenbach', 49.68333, 7.75],
            ['Bad Dürkheim', 49.4618, 8.17236], ['Kallbach', 'NaN'], ['Heidenburg bei Oberstaufenbach', 'NaN'],
            ['Göllheim', 49.595, 8.05083], ['Lindelbrunn', 'NaN'], ['Altleiningen', 49.5075, 8.07333],
            ['Fischbach b. Hochspeyer', 'NaN'], ['Frankenthal', 49.53414, 8.35357], ['Donnersberg', 49.6, 7.95],
            ['St. Medard', 'NaN'], ['Körborn', 49.56667, 7.36667], ['Frankenthal', 49.53414, 8.35357],
            ['Landsberg', 'NaN'], ['Beilstein', 50.11667, 7.25], ['Hochspeyer', 49.44207, 7.89504],
            ['Löllbach', 49.68333, 7.58333], ['Odernheim', 49.78472, 8.19417], ['Speyer', 49.33049, 8.19983],
            ['Donnersberg', 49.6, 7.95], ['Altenbaumberg', 'NaN'], ['Ebernburg', 49.81159, 7.84523],
            ['Hartenburg', 'NaN'], ['Göllheim', 49.595, 8.05083], ['Bergzabern', 49.10245, 8.00092],
            ['Neustadt an der Haardt', 49.35009, 8.13886], ['Schwarzerden', 49.53394, 7.283], ['Einsiedel', 'NaN'],
            ['Lichtenstein', 'NaN'], ['Bad Dürkheim', 49.4618, 8.17236], ['Diedelkopf', 49.54655, 7.38668],
            ['Kreuznach', 49.8414, 7.86713], ['Disibodenberg', 'NaN'], ['Blidenfeld', 'NaN'],
            ['Speyer', 49.33049, 8.19983], ['Göllheim', 49.595, 8.05083], ['Rosentreppe', 'NaN'],
            ['Otterstadt', 49.37222, 8.44778], ['Zeiskam', 49.23278, 8.24722], ['Disibodenberg', 'NaN'],
            ['Altheim', 49.17189, 7.31259], ['Dietrichskirchel', 'NaN'], ['Aschbach b. Kaiserslautern', 'NaN'],
            ['Bosenbach', 49.54022, 7.53029], ['Falkenburg', 50.00682, 7.85201], ['Bergzabern', 49.10245, 8.00092],
            ['Dagobertshecke', 'NaN'], ['Altenglan', 49.55, 7.46667], ['Winnweiler', 49.56667, 7.85],
            ['Mannweiler', 49.7, 7.8], ['Miesenbach', 49.46072, 7.55632], ['Niederlauterbach', 'NaN'],
            ['Landstuhl', 49.41306, 7.57021], ['Abtstein', 'NaN'], ['Vollmersweiler', 49.065, 8.07722],
            ['Alschbach', 49.23954, 7.23806], ['Bad Dürkheim', 49.4618, 8.17236], ['Fischbach b. Schönau', 'NaN'],
            ['Eppenbrunn', 49.11667, 7.56667], ['Battenberg', 49.53193, 8.13714], ['Dahn', 49.15098, 7.77843],
            ['Steinalb', 49.31667, 7.65], ['Marienthal', 50.73619, 7.67197], ['Hartenburg', 'NaN'],
            ['Offenbach a. Glan', 'NaN'], ['St. Ingbert', 'NaN'], ['Affolterloch', 'NaN'], ['Hohenburg', 'NaN'],
            ['Karlsberg', 'NaN'], ['Neuwolfstein', 'NaN'], ['Edenkoben', 49.28393, 8.12714],
            ['Battweiler', 49.27848, 7.46366], ['Hungerbrunnen bei Kaiserslautern', 'NaN'], ['Donnersberg', 49.6, 7.95],
            ['Donnersberg', 49.6, 7.95], ['Drei Züge', 'NaN'], ['Bingert', 49.78137, 7.79915],
            ['Bingert', 49.78137, 7.79915], ['Wasgenstein', 'NaN'], ['Kaiserslautern', 49.443, 7.77161],
            ['Hagenau', 'NaN'], ['Kaiserslautern', 49.443, 7.77161], ['Beilstein', 50.11667, 7.25],
            ['Kaiserslautern', 49.443, 7.77161], ['Speyer', 49.33049, 8.19983], ['Germersheim', 49.2144, 8.36687],
            ['Böckelheim', 49.80891, 7.74425], ['Hartenburg', 'NaN'], ['Göllheim', 49.595, 8.05083],
            ['Tschifflick', 'NaN'], ['Neudahn', 'NaN'], ['Altenbaumberg', 'NaN'], ['Altenbaumberg', 'NaN'],
            ['Ebernburg', 49.81159, 7.84523], ['Ruppertsfelsen', 'NaN'], ['Seebach', 49.45202, 8.15831],
            ['Marienstein', 'NaN'], ['Böckelheim', 49.80891, 7.74425], ['Montfort', 49.76611, 7.76449],
            ['Altenbaumberg', 'NaN'], ['NaN', 'NaN'], ['Großer Stiefel', 'NaN'], ['Enkenbach', 49.48333, 7.88333],
            ['Aschbach b. Kaiserslautern', 'NaN'], ['Speyer', 49.33049, 8.19983], ['Trifels', 49.20613, 7.97527],
            ['Sembach', 49.51177, 7.86661], ['Heimbach', 50.45, 7.53333], ['Altleiningen', 49.5075, 8.07333],
            ['Ramberger Schloß', 'NaN'], ['Erfenstein', 49.35378, 8.01775], ['Erfenstein', 49.35378, 8.01775],
            ['Montfort', 49.76611, 7.76449], ['Großer Stiefel', 'NaN'], ['Falkenstein', 49.6, 7.88333],
            ['Spangenberg', 'NaN'], ['Beckenhof', 'NaN'], ['Lauterecken', 49.64993, 7.59265],
            ['Lingenfeld', 49.25389, 8.33861], ['Ballweiler', 49.2038, 7.21527], ['Eußerthal', 49.25, 7.96667],
            ['Eisenberg', 49.55859, 8.07199], ['Altdorf', 49.28722, 8.21611], ['Speyer', 49.33049, 8.19983],
            ['NaN', 'NaN'], ['Bad Dürkheim', 49.4618, 8.17236], ['Landstuhl', 49.41306, 7.57021], ['Rosenberg', 'NaN'],
            ['Konken', 49.5088, 7.35393], ['Forst', 50.8, 7.68333], ['Freckenfeld', 49.065, 8.11389],
            ['Lug', 49.18333, 7.9], ['NaN', 'NaN'], ['Sausenheim', 49.54744, 8.15769], ['Oppau', 49.51861, 8.39917],
            ['Friesenheim', 49.83639, 8.25694], ['Annweiler', 49.20613, 7.97527], ['Annweiler', 49.20613, 7.97527],
            ['Alsenborn', 49.48333, 7.91667], ['Dreisen', 49.60333, 8.01056], ['Grumbach', 49.65, 7.56667],
            ['Meisenheim', 49.70721, 7.66765], ['Hüffelsheim', 49.81667, 7.8], ['Böckelheim', 49.80891, 7.74425],
            ['Limburg', 49.42444, 8.39194], ['Neustadt an der Haardt', 49.35009, 8.13886],
            ['Neustadt an der Haardt', 49.35009, 8.13886], ['Iagelheim', 'NaN'], ['Ebernburg', 49.81159, 7.84523],
            ['Bad Dürkheim', 49.4618, 8.17236], ['NaN', 'NaN'], ['NaN', 'NaN'], ['NaN', 'NaN'], ['NaN', 'NaN'],
            ['NaN', 'NaN']]

    n_book = 1
    n_universal = 42  # Start Nummer für universelle Nummer
    num_dict = {}  # ID/Nummern statt Sagennamen als key. Manche Sagen können die gleichen Titel haben, zb. einfach Nummern
    i = 0
    uid = 250
    werkID = 3
    dict = {}
    for title in titles:
        group = titles[title][1]
        categorie = titles[title][
            0]  # if cat and group already in dict, replace with value[1]. Nested categories split using a symbol(f.ex. @)
        placeID = locs[i][0]
        if locs[i][1] != "NaN":
            longitude = locs[i][2]
            latitude = locs[i][1]
        else:
            longitude = 0
            latitude = 0
        title = re.sub(r'\d+\.\s', '', title)
        # xml_id = "Elsass2." + str(n_book)
        dict[title] = {"id": uid,
                       "werk_id": werkID,
                       "n_book": n_book,
                       "title": title,
                       "division_1": categorie,
                       "division_2": group,
                       "place_id": placeID,
                       "longitude": longitude,
                       "latitude": latitude}
        # num_dict[xml_id] = dict[key]
        n_book += 1
        i += 1
        uid += 1
    # print(dict)
    # print(num_dict)

    with open("pfalz_sagen.json", "w", encoding="UTF-8") as f:
        json.dump(dict, f, ensure_ascii=False, indent=2)

    return dict

get_dict()

def get_front():
    with open("vorwort/pfalz_vorwort.txt", "r", encoding="utf-8") as f:
        return " ".join(
            [
                word.strip()
                for word in f.read().split()
            ]
        )


def get_back():
    with open("nachwort/pfalz_nachwort.txt", "r", encoding="utf-8") as f:
        return " ".join(
            [
                word.strip()
                for word in f.read().split()
            ]
        )


def get_sql():
    name = "pfalz_sagen"
    book_title = "Pfälzisches Sagenbuch"
    dict = get_dict()
    # lang = "deutsch"
    return name, book_title, dict


"""
d, titles = get_dict()
import re
print(d)
for title in titles:
    print(title)
titles = [re.sub(r"\d+\.\s", "", title) for title in titles]
"""
