def get_pkl():
    pickle_filename = "unterelsass_sagen"
    return pickle_filename


def get_dict():
    titles = {'1. Die Geisterschlacht': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                         'I. Von Seelen, Geistern und Gespenstern.'],
              '2. Die Fahrt der Toten': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                         'I. Von Seelen, Geistern und Gespenstern.'],
              '3. Die überschiffenden Mönche': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                'I. Von Seelen, Geistern und Gespenstern.'],
              '4. Der ewige Jäger': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                     'I. Von Seelen, Geistern und Gespenstern.'],
              '5. Der Jägerpfuhl': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                    'I. Von Seelen, Geistern und Gespenstern.'],
              '6. Der wilde Jäger von Sponheim': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                  'I. Von Seelen, Geistern und Gespenstern.'],
              '7. Der wilde Jäger am Donnersberg': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                    'I. Von Seelen, Geistern und Gespenstern.'],
              '8. Der Lindenschmidt': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                       'I. Von Seelen, Geistern und Gespenstern.'],
              '9. Der Einaug vom Scharfeneck': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                'I. Von Seelen, Geistern und Gespenstern.'],
              '10. Der Geist vom Scharfeneck': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                'I. Von Seelen, Geistern und Gespenstern.'],
              '11. Hans Trapp': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                 'I. Von Seelen, Geistern und Gespenstern.'],
              '12. Das weiße Reh': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                    'I. Von Seelen, Geistern und Gespenstern.'],
              '13. Der Geist auf dem Bleifelsen': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                   'I. Von Seelen, Geistern und Gespenstern.'],
              '14. Der blutschwitzende Stein': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                'I. Von Seelen, Geistern und Gespenstern.'],
              '15. Der gebannte Geist': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                         'I. Von Seelen, Geistern und Gespenstern.'],
              '16. Der Irrwisch auf dem Klosterberg bei Winterbach': [
                  'A. Vom alten und neuen Glauben. (Mythische Sagen.)', 'I. Von Seelen, Geistern und Gespenstern.'],
              '17. Das Flämmchen': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                    'I. Von Seelen, Geistern und Gespenstern.'],
              '18. Der Schuß auf das Flämmchen': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                  'I. Von Seelen, Geistern und Gespenstern.'],
              '19. Der Geist auf dem Kieneck': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                'I. Von Seelen, Geistern und Gespenstern.'],
              '20. Der falsche Eid': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                      'I. Von Seelen, Geistern und Gespenstern.'],
              '21. Die Sage vom Maulus': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                          'I. Von Seelen, Geistern und Gespenstern.'],
              '22. Des Beilsteiners Umgang': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                              'I. Von Seelen, Geistern und Gespenstern.'],
              '23. Der Maire von Meisenheim': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                               'I. Von Seelen, Geistern und Gespenstern.'],
              '24. Das Mädchen vom Pauliner Schlößchen': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                          'I. Von Seelen, Geistern und Gespenstern.'],
              '25. Die unredliche Wirtin': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                            'I. Von Seelen, Geistern und Gespenstern.'],
              '26. Der Grenzsteinverrücker': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                              'I. Von Seelen, Geistern und Gespenstern.'],
              '27. Kanzel und Nonne': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                       'I. Von Seelen, Geistern und Gespenstern.'],
              '28. Das Nonnental bei Neustadt': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                 'I. Von Seelen, Geistern und Gespenstern.'],
              '29. Der Hund von Auerbach': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                            'I. Von Seelen, Geistern und Gespenstern.'],
              '30. Die Wassernixe zu Eschringen': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                   'II. Von Elfen und Nixen, Zwergen und Wichten.'],
              '31. Die schöne Tanne': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                       'II. Von Elfen und Nixen, Zwergen und Wichten.'],
              '32. Die drei Wiesenfräulein': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                              'II. Von Elfen und Nixen, Zwergen und Wichten.'],
              '33. Die drei Jungfrauen': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                          'II. Von Elfen und Nixen, Zwergen und Wichten.'],
              '34. Die drei Schwestern': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                          'II. Von Elfen und Nixen, Zwergen und Wichten.'],
              '35. Das Schloßfräulein': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                         'II. Von Elfen und Nixen, Zwergen und Wichten.'],
              '36. Der Schloßgarten auf dem Großen Stiefel': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                              'II. Von Elfen und Nixen, Zwergen und Wichten.'],
              '37. Die Schloßfrau und ihre Wäsche': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                     'II. Von Elfen und Nixen, Zwergen und Wichten.'],
              '38. Die weiße Dame vom Pauliner Schlößchen': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                             'II. Von Elfen und Nixen, Zwergen und Wichten.'],
              '39. Die Wildfrau': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                   'II. Von Elfen und Nixen, Zwergen und Wichten.'],
              '40. Das Wildfrauloch bei Schweinschied': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                         'II. Von Elfen und Nixen, Zwergen und Wichten.'],
              '41. Das Wildfrauenloch bei Schwarzerden': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                          'II. Von Elfen und Nixen, Zwergen und Wichten.'],
              '42. Das Lindenmütterchen': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                           'II. Von Elfen und Nixen, Zwergen und Wichten.'],
              '43. Die guten Zwerge': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                       'II. Von Elfen und Nixen, Zwergen und Wichten.'],
              '44. Das Graumännchensloch': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                            'II. Von Elfen und Nixen, Zwergen und Wichten.'],
              '45. Das graue Männchen': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                         'II. Von Elfen und Nixen, Zwergen und Wichten.'],
              '46. Der Ritter vom Huneberg': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                              'II. Von Elfen und Nixen, Zwergen und Wichten.'],
              '47. Das Kehrebacher Knüppchen': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                'II. Von Elfen und Nixen, Zwergen und Wichten.'],
              '48. Die Erdmännlein': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                      'II. Von Elfen und Nixen, Zwergen und Wichten.'],
              '49. Die Schlange und das Kind': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                'II. Von Elfen und Nixen, Zwergen und Wichten.'],
              '50. Die Schlangenkönigin': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                           'III. Von Dämonen und Göttern.'],
              '51. Der Drachenfels bei Dürkheim': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                   'III. Von Dämonen und Göttern.'],
              '52. Der Drachenfels bei Busenberg': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                    'III. Von Dämonen und Göttern.'],
              '53. Das wütende Heer': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                       'III. Von Dämonen und Göttern.'],
              '54. Die wilde Jagd': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                     'III. Von Dämonen und Göttern.'],
              '55. Vom Rosse des wilden Jägers': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                  'III. Von Dämonen und Göttern.'],
              '56. Die Riesen des Bliestales': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                'III. Von Dämonen und Göttern.'],
              '57. Die Riesen des Wasgenwaldes': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                  'III. Von Dämonen und Göttern.'],
              '58. Das Heidentürmchen zu Speyer': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                   'III. Von Dämonen und Göttern.'],
              '59. Der Riese Kreuzmann': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                          'III. Von Dämonen und Göttern.'],
              '60. Das Riesen- oder Hünengrab': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                 'III. Von Dämonen und Göttern.'],
              '61. Vom Gotte Wodan': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                      'III. Von Dämonen und Göttern.'],
              '62. Kolb von Wartenberg': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                          'III. Von Dämonen und Göttern.'],
              '63. Die Waldkapelle': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                      'III. Von Dämonen und Göttern.'],
              '64. Gott Donar und sein Gefährt': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                  'III. Von Dämonen und Göttern.'],
              '65. Der Burgbau auf dem Rheingrafenstein': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                           'IV. Von Teufeln, Hexen und Zauberern.'],
              '66. Der Teufelsstein': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                       'IV. Von Teufeln, Hexen und Zauberern.'],
              '67. Der Teufelstisch': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                       'IV. Von Teufeln, Hexen und Zauberern.'],
              '68. Der Teufelsberg': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                      'IV. Von Teufeln, Hexen und Zauberern.'],
              '69. Der Teufelsbrunnen': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                         'IV. Von Teufeln, Hexen und Zauberern.'],
              '70. Der Müller und der Teufel': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                'IV. Von Teufeln, Hexen und Zauberern.'],
              '71. Die Hexe vom Münstertal': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                              'IV. Von Teufeln, Hexen und Zauberern.'],
              '72. Die gebrannte Hexe': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                         'IV. Von Teufeln, Hexen und Zauberern.'],
              '73. Die diebische Hexe': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                         'IV. Von Teufeln, Hexen und Zauberern.'],
              '74. Das Hexengewitter': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                        'IV. Von Teufeln, Hexen und Zauberern.'],
              '75. Der Hexenball': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                    'IV. Von Teufeln, Hexen und Zauberern.'],
              '76. Hexentanz und Hexenkraut': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                               'IV. Von Teufeln, Hexen und Zauberern.'],
              '77. Der Zauberschüße Punker von Rohrbach': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                           'IV. Von Teufeln, Hexen und Zauberern.'],
              '78. Der Schnittlfelsen': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                         'IV. Von Teufeln, Hexen und Zauberern.'],
              '79. Der Heidenfelsen': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                       'IV. Von Teufeln, Hexen und Zauberern.'],
              '80. Der krumme Dallacker': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                           'IV. Von Teufeln, Hexen und Zauberern.'],
              '81. Der Stab des Klausners': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                             'V. Von Zeichen und Wundern.'],
              '82. Das Marienbild zu Gräfinthal': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                   'V. Von Zeichen und Wundern.'],
              '83. Das Muttergottesbild zu Forst': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                    'V. Von Zeichen und Wundern.'],
              '84. Das Marienbild zu Ranschbach': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                   'V. Von Zeichen und Wundern.'],
              '85. Das fromme Knäblein zu Speyer': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                    'V. Von Zeichen und Wundern.'],
              '86. Das Marienbild im Dom zu Speyer': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                      'V. Von Zeichen und Wundern.'],
              '87. Der rauschende Kelch im Speyerer Dom': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                           'V. Von Zeichen und Wundern.'],
              '88. Die Maria-Hilf-Kapelle auf dem Kolmerberg': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                                'V. Von Zeichen und Wundern.'],
              '89. Die Kapelle und das Glöckchen des hl. Cyriakus': [
                  'A. Vom alten und neuen Glauben. (Mythische Sagen.)', 'V. Von Zeichen und Wundern.'],
              '90. Der hl. Cyriakus und der Wingertsbalken': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                              'V. Von Zeichen und Wundern.'],
              '91. Die Strutelpeters-Kapelle': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                'V. Von Zeichen und Wundern.'],
              '92. Die St. Lorenzkapelle': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                            'V. Von Zeichen und Wundern.'],
              '93. Das goldene Kreuz im Klosterweiher': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                         'V. Von Zeichen und Wundern.'],
              '94. Der Servatiusbrunnen': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                           'V. Von Zeichen und Wundern.'],
              '95. Der Lorenzenbrunnen': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                          'V. Von Zeichen und Wundern.'],
              '96. Die Wunder des hl. Philipp von Zell': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                          'V. Von Zeichen und Wundern.'],
              '97. Die Glocken zu Speyer': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                            'VI. Von Glocken und Schätzen.'],
              '98. Die fliegende Glocke': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                           'VI. Von Glocken und Schätzen.'],
              '99. Die große Glocke von Neustadt': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                    'VI. Von Glocken und Schätzen.'],
              '100. Die Glocke von Lindesheim': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                 'VI. Von Glocken und Schätzen.'],
              '101. Das versunkene Glöcklein': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                'VI. Von Glocken und Schätzen.'],
              '102. Die vergrabenen Glocken': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                               'VI. Von Glocken und Schätzen.'],
              '103. Die goldene Orgel': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                         'VI. Von Glocken und Schätzen.'],
              '104. Das goldene Kegelspiel': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                              'VI. Von Glocken und Schätzen.'],
              '105. Der Schatz zu Beilstein': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                               'VI. Von Glocken und Schätzen.'],
              '106. Das weiße Fräulein an der dicken Eiche': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                              'VI. Von Glocken und Schätzen.'],
              '107. Die Schätze zu Wilenstein': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                 'VI. Von Glocken und Schätzen.'],
              '108. Der Stolzenberger Schatz': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                'VI. Von Glocken und Schätzen.'],
              '109. Der weiße Peter': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                       'VI. Von Glocken und Schätzen.'],
              '110. Der Schatz auf dem Disibodenberg': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                        'VI. Von Glocken und Schätzen.'],
              '111. Der Schatz auf Hohenfels': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                'VI. Von Glocken und Schätzen.'],
              '112. Der Schatz zu Rotenkirchen': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                  'VI. Von Glocken und Schätzen.'],
              '113. Der Schatz auf Scharfeneck': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                  'VI. Von Glocken und Schätzen.'],
              '114. Die Juden und der Schatz': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                'VI. Von Glocken und Schätzen.'],
              '115. Die Heidenburg': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                      'VI. Von Glocken und Schätzen.'],
              '116. Der Krötenstuhl': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                       'VI. Von Glocken und Schätzen.'],
              '117. Der Klosterbrunnen bei Pirmasens': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                        'VI. Von Glocken und Schätzen.'],
              '118. Der Bauer und der Schatz': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                'VI. Von Glocken und Schätzen.'],
              '119. Die vergessene Schlüsselblume': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                     'VI. Von Glocken und Schätzen.'],
              '120. Die Schätze im Innern des Kirkeler Bergs': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                                'VI. Von Glocken und Schätzen.'],
              '121. Der Birkenbusch auf Kirkel': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                  'VI. Von Glocken und Schätzen.'],
              '122. Die unterirdischen Schätze im Pauliner Schlößchen': [
                  'A. Vom alten und neuen Glauben. (Mythische Sagen.)', 'VI. Von Glocken und Schätzen.'],
              '123. In Gold verwandelte Porzellanscherben': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                             'VI. Von Glocken und Schätzen.'],
              '124. Das weiße Fräulein auf der Leinbachmühle': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                                                'VI. Von Glocken und Schätzen.'],
              '125. Der entgangene Schatz': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                             'VI. Von Glocken und Schätzen.'],
              '126. Der gehobene Schatz': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                           'VI. Von Glocken und Schätzen.'],
              '127. Das Glühhäuschen': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                        'VI. Von Glocken und Schätzen.'],
              '128. Die Glut': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)', 'VI. Von Glocken und Schätzen.'],
              '129. Die blaue Flamme': ['A. Vom alten und neuen Glauben. (Mythische Sagen.)',
                                        'VI. Von Glocken und Schätzen.'],
              '130. Die Heidenmauer': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.', 'IVI. Ohne Gruppe'],
              '131. Attilas Grab': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.', 'IVI. Ohne Gruppe'],
              '132. Wie die Heidenburg fiel': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                               'IVI. Ohne Gruppe'],
              '133. Kaiser Adolfs Tod': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                         'IVI. Ohne Gruppe'], '134. Wie die Bauern Schloß Lindelbrunn nahmen': [
            'B. Von pfälzischer Landes-, Orts- und Familiengeschichte.', 'IVI. Ohne Gruppe'],
              '135. Die Bauern auf Neuleiningen': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                   'IVI. Ohne Gruppe'],
              '136. Das Klösterlein zu Fischbach': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                    'IVI. Ohne Gruppe'],
              '137. Der Hirt von Oggersheim': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                               'IVI. Ohne Gruppe'],
              '138. Die Mordkammer': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.', 'IVI. Ohne Gruppe'],
              '139. Zerstörung des Klosters St. Medard': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                          'I. Von Kriegen und Fehden und anderen Nöten.'],
              '140. Belagerung von Burg Lichtenberg': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                       'I. Von Kriegen und Fehden und anderen Nöten.'],
              '141. Neustadts Retterin': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                          'I. Von Kriegen und Fehden und anderen Nöten.'],
              '142. Der Metallfühler': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                        'I. Von Kriegen und Fehden und anderen Nöten.'],
              '143. Jammerhalde und Hahnenfalz': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                  'I. Von Kriegen und Fehden und anderen Nöten.'],
              '144. Der Trompeter an der dicken Eiche': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                         'I. Von Kriegen und Fehden und anderen Nöten.'],
              '145. Der tote Soldat': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                       'I. Von Kriegen und Fehden und anderen Nöten.'],
              '146. Der heimgekehrte Krieger': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                'I. Von Kriegen und Fehden und anderen Nöten.'],
              '147. Nächtliche Erscheinung zu Speyer': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                        'I. Von Kriegen und Fehden und anderen Nöten.'],
              '148. Wie du willt, Melchior': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                              'I. Von Kriegen und Fehden und anderen Nöten.'],
              '149. Treuenfels': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                  'I. Von Kriegen und Fehden und anderen Nöten.'],
              '150. Der Eberkopf': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                    'I. Von Kriegen und Fehden und anderen Nöten.'],
              '151. Der Mönchskopf': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                      'I. Von Kriegen und Fehden und anderen Nöten.'],
              '152. Die Grafen von Eberstein': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                'I. Von Kriegen und Fehden und anderen Nöten.'],
              '153. Die Burgfrau von Berwartstein': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                     'I. Von Kriegen und Fehden und anderen Nöten.'],
              '154. Der böse Wolfsberger': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                            'I. Von Kriegen und Fehden und anderen Nöten.'],
              '155. Das Grab Noes und die Pest': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                  'I. Von Kriegen und Fehden und anderen Nöten.'],
              '156. Entstehung von Kaiserslautern': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                     'II. Von Gründungen, Stiftungen und Ortsbenennungen.'],
              '157. Schloß und Dorf Neidenfels': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                  'II. Von Gründungen, Stiftungen und Ortsbenennungen.'],
              '158. Kehrdichannichts, Murmelnichtviel, Schaudichnichtum': [
                  'B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                  'II. Von Gründungen, Stiftungen und Ortsbenennungen.'],
              '159. Entstehung von Bad Diedelkopf': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                     'II. Von Gründungen, Stiftungen und Ortsbenennungen.'],
              '160. Gründung Kreuznachs': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                           'II. Von Gründungen, Stiftungen und Ortsbenennungen.'],
              '161. Gründung des Klosters Difibodenberg': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                           'II. Von Gründungen, Stiftungen und Ortsbenennungen.'],
              '162. Stiftung von Klingenmünster': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                   'II. Von Gründungen, Stiftungen und Ortsbenennungen.'],
              '163. Limburgs Entstehung': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                           'II. Von Gründungen, Stiftungen und Ortsbenennungen.'],
              '164. Das Kloster Rosenthal': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                             'II. Von Gründungen, Stiftungen und Ortsbenennungen.'],
              '165. Die Rosentreppe': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                       'II. Von Gründungen, Stiftungen und Ortsbenennungen.'],
              '166. Der Roßsprung bei Speyer': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                'II. Von Gründungen, Stiftungen und Ortsbenennungen.'],
              '167. Das Fuchsloch oder Gnadenwasser bei Zeiskam': [
                  'B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                  'II. Von Gründungen, Stiftungen und Ortsbenennungen.'],
              '168. Die Felsenkirche zu Oberstein': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                     'II. Von Gründungen, Stiftungen und Ortsbenennungen.'],
              '169. Der Abt Jakob von Hornbach': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                  'II. Von Gründungen, Stiftungen und Ortsbenennungen.'],
              '170. Das Dietrichskirchel': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                            'II. Von Gründungen, Stiftungen und Ortsbenennungen.'],
              '171. Die verkehrte Kirche': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                            'II. Von Gründungen, Stiftungen und Ortsbenennungen.'],
              '172. Die Wolfskirche bei Bosenbach': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                     'II. Von Gründungen, Stiftungen und Ortsbenennungen.'],
              '173. Das Kind von der Falkenburg': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                   'II. Von Gründungen, Stiftungen und Ortsbenennungen.'],
              '174. Die Peternell bei Bergzabern': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                    'II. Von Gründungen, Stiftungen und Ortsbenennungen.'],
              '175. Die Dagobertshecke und die Haingeraiden': [
                  'B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                  'II. Von Gründungen, Stiftungen und Ortsbenennungen.'],
              '176. Des Remigs Teil vom Wafichenwald': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                        'II. Von Gründungen, Stiftungen und Ortsbenennungen.'],
              '177. Das steinerne Kreuz': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                           'III. Von Kreuzen und Steinen, von'],
              '178. Das gläserne Kreuz': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                          'III. Von Kreuzen und Steinen, von'],
              '179. Das Steinkreuz im Walde': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                               'III. Von Kreuzen und Steinen, von'],
              '180. Das weiße Kreuz im Bienwald': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                   'III. Von Kreuzen und Steinen, von'],
              '181. Sickingens Würfel': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                         'III. Von Kreuzen und Steinen, von'],
              '182. Der Abtstein': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                    'III. Von Kreuzen und Steinen, von'],
              '183. Der Hohe Stein': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                      'III. Von Kreuzen und Steinen, von'],
              '184. Der Gollenstein': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                       'III. Von Kreuzen und Steinen, von'],
              '185. Ein Grabstein in der St. Johanniskirche zu Dürkheim': [
                  'B. Von pfälzischer Landes-, Orts- und Familiengeschichte.', 'III. Von Kreuzen und Steinen, von'],
              '186. Der Reitersprung': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                        'III. Von Kreuzen und Steinen, von'],
              '187. Kühner Sprung': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                     'III. Von Kreuzen und Steinen, von'],
              '188. Der Jungfernsprung bei Battenberg': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                         'III. Von Kreuzen und Steinen, von'],
              '189. Der Jungfernsprung bei Dahn': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                   'III. Von Kreuzen und Steinen, von'],
              '190. Der Wolfsfels': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                     'III. Von Kreuzen und Steinen, von'],
              '191. Die Hirschtrabe': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                       'III. Von Kreuzen und Steinen, von'],
              '192. Der Nonnenfels': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                      'III. Von Kreuzen und Steinen, von'],
              '193. Das Frifraloch bei Offenbach am Glan': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                            'III. Von Kreuzen und Steinen, von'],
              '194. Die Heidenhöhle': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                       'III. Von Kreuzen und Steinen, von'],
              '195. Das Affolterloch': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                        'III. Von Kreuzen und Steinen, von'],
              '196. Der Maidenbrunnen': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                         'III. Von Kreuzen und Steinen, von'],
              '197. Der Reiterbrunnen': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                         'III. Von Kreuzen und Steinen, von'],
              '198. Der tiefe Brunnen': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                         'III. Von Kreuzen und Steinen, von'],
              '199. Wasserberg und tiefer Brunnen': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                     'III. Von Kreuzen und Steinen, von'],
              '200. Von drei Brunnen': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                        'III. Von Kreuzen und Steinen, von'],
              '201. Der Hungerbrunnen bei Kaiserslautern': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                            'III. Von Kreuzen und Steinen, von'],
              '202. Die Silbergrube': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                       'IV. Vom heimischen Bergbau.'],
              '203. Die Erzgrube im Langental': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                 'IV. Vom heimischen Bergbau.'],
              '204. Die drei Züge': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                     'IV. Vom heimischen Bergbau.'],
              '205. Ernesti-Glück': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                     'IV. Vom heimischen Bergbau.'],
              '206. Die Geißkammer': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                      'IV. Vom heimischen Bergbau.'],
              '207. Der Kampf am Wasgenstein': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                'V. Von Helden, Geschlechtern und Wappen.'],
              '208. Keiser Friderich zu Keiserslautern': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                          'V. Von Helden, Geschlechtern und Wappen.'],
              '209. Des Kaisers Bett': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                        'V. Von Helden, Geschlechtern und Wappen.'],
              '210. Der Hecht im Kaiserwoog': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                               'V. Von Helden, Geschlechtern und Wappen.'],
              '211. Der Ritter von Beilstein': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                'V. Von Helden, Geschlechtern und Wappen.'],
              '212. Das Hufeisen zu Kaiserslautern': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                      'V. Von Helden, Geschlechtern und Wappen.'],
              '213. Warum die Kaiser im Dom zu Speyer bestattet wurden': [
                  'B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                  'V. Von Helden, Geschlechtern und Wappen.'],
              '214. Kaiser Rudolfs Ritt zum Grabe': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                     'V. Von Helden, Geschlechtern und Wappen.'],
              '215. Kaiser Heinrich IV. zu Böckelheim': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                         'V. Von Helden, Geschlechtern und Wappen.'],
              '216. Der Lindenplatz auf Hartenburg': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                      'V. Von Helden, Geschlechtern und Wappen.'],
              '217. Die Göllheimer Ulme': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                           'V. Von Helden, Geschlechtern und Wappen.'],
              '218. Die Tschiffliker Kirschen': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                 'V. Von Helden, Geschlechtern und Wappen.'],
              '219. Der Pfeil': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                 'V. Von Helden, Geschlechtern und Wappen.'],
              '220. Der Löwe im pfälzischen und bayerischen Wappen': [
                  'B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                  'V. Von Helden, Geschlechtern und Wappen.'], '221. Raugraf Heinrich und Maria von Brabant': [
            'B. Von pfälzischer Landes-, Orts- und Familiengeschichte.', 'V. Von Helden, Geschlechtern und Wappen.'],
              '222. Franz von Sickingen und der Geist vom Rotenfelsen': [
                  'B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                  'V. Von Helden, Geschlechtern und Wappen.'],
              '223. Der alte Ruppert vom Ruppertsfelsen': ['B. Von pfälzischer Landes-, Orts- und Familiengeschichte.',
                                                           'V. Von Helden, Geschlechtern und Wappen.'],
              '224. Das Kloster Seebach': ['C. Von allerlei Gutem und Bösem. (Ethische Sagen.)',
                                           'I. Von mancherlei Treue und Verrat.'],
              '225. Das Kloster Marienstein': ['C. Von allerlei Gutem und Bösem. (Ethische Sagen.)',
                                               'I. Von mancherlei Treue und Verrat.'],
              '226. Die Brautfahrt': ['C. Von allerlei Gutem und Bösem. (Ethische Sagen.)',
                                      'I. Von mancherlei Treue und Verrat.'],
              '227. Weibestreue': ['C. Von allerlei Gutem und Bösem. (Ethische Sagen.)',
                                   'I. Von mancherlei Treue und Verrat.'],
              '228. Das Fräulein mit dem steinernen Herzen': ['C. Von allerlei Gutem und Bösem. (Ethische Sagen.)',
                                                              'I. Von mancherlei Treue und Verrat.'],
              '229. Die Lilie zu Altenbaumberg': ['C. Von allerlei Gutem und Bösem. (Ethische Sagen.)',
                                                  'I. Von mancherlei Treue und Verrat.'],
              '230. Die gelben Schlüsselblumen': ['C. Von allerlei Gutem und Bösem. (Ethische Sagen.)',
                                                  'I. Von mancherlei Treue und Verrat.'],
              '231. Hildegard von Hoheneck': ['C. Von allerlei Gutem und Bösem. (Ethische Sagen.)',
                                              'I. Von mancherlei Treue und Verrat.'],
              '232. Das Fräulein von Wilenstein': ['C. Von allerlei Gutem und Bösem. (Ethische Sagen.)',
                                                   'I. Von mancherlei Treue und Verrat.'],
              '233. Schön Elsbeth von der Kästenburg': ['C. Von allerlei Gutem und Bösem. (Ethische Sagen.)',
                                                        'I. Von mancherlei Treue und Verrat.'],
              '234. Richard Löwenherz auf Trifels': ['C. Von allerlei Gutem und Bösem. (Ethische Sagen.)',
                                                     'I. Von mancherlei Treue und Verrat.'],
              '235. Das Pfälzer Weberlein': ['C. Von allerlei Gutem und Bösem. (Ethische Sagen.)',
                                             'I. Von mancherlei Treue und Verrat.'],
              '236. Das ehrliche Weberlein zu Zeiskam': ['C. Von allerlei Gutem und Bösem. (Ethische Sagen.)',
                                                         'I. Von mancherlei Treue und Verrat.'],
              '237. Der Junker von Randeck': ['C. Von allerlei Gutem und Bösem. (Ethische Sagen.)',
                                              'I. Von mancherlei Treue und Verrat.'],
              '238. Der böse Scharfenecker': ['C. Von allerlei Gutem und Bösem. (Ethische Sagen.)',
                                              'I. Von mancherlei Treue und Verrat.'],
              '239. Die lederne Brücke': ['C. Von allerlei Gutem und Bösem. (Ethische Sagen.)',
                                          'I. Von mancherlei Treue und Verrat.'],
              '240. Des Spangenbergers Sohn': ['C. Von allerlei Gutem und Bösem. (Ethische Sagen.)',
                                               'I. Von mancherlei Treue und Verrat.'],
              '241. Der Raub der Monstranz': ['C. Von allerlei Gutem und Bösem. (Ethische Sagen.)',
                                              'II. Von übler Taten Lohn.'],
              '242. Der Raubritter Wynant': ['C. Von allerlei Gutem und Bösem. (Ethische Sagen.)',
                                             'II. Von übler Taten Lohn.'],
              '243. Die Falkensteiner Blutnelken': ['C. Von allerlei Gutem und Bösem. (Ethische Sagen.)',
                                                    'II. Von übler Taten Lohn.'],
              '244. Kaspar von Spangenberg': ['C. Von allerlei Gutem und Bösem. (Ethische Sagen.)',
                                              'II. Von übler Taten Lohn.'],
              '245. Das Mordloch': ['C. Von allerlei Gutem und Bösem. (Ethische Sagen.)', 'II. Von übler Taten Lohn.'],
              '246. Der Mutter Fluch': ['C. Von allerlei Gutem und Bösem. (Ethische Sagen.)',
                                        'II. Von übler Taten Lohn.'],
              '247. Der ewige Fuhrmannsweg': ['C. Von allerlei Gutem und Bösem. (Ethische Sagen.)',
                                              'II. Von übler Taten Lohn.'],
              '248. Junker Elz von Wecklingen': ['C. Von allerlei Gutem und Bösem. (Ethische Sagen.)',
                                                 'II. Von übler Taten Lohn.'],
              '249. Die Hand des Toten': ['C. Von allerlei Gutem und Bösem. (Ethische Sagen.)',
                                          'II. Von übler Taten Lohn.'],
              '250. Die unverwelkliche Hand': ['C. Von allerlei Gutem und Bösem. (Ethische Sagen.)',
                                               'II. Von übler Taten Lohn.'],
              '251. Die Edelfräulein zu Altdorf': ['C. Von allerlei Gutem und Bösem. (Ethische Sagen.)',
                                                   'II. Von übler Taten Lohn.'],
              '252. Der böse Bischof und der getreue Hutzmann': ['C. Von allerlei Gutem und Bösem. (Ethische Sagen.)',
                                                                 'II. Von übler Taten Lohn.'],
              '253. Das Balkemännel': ['C. Von allerlei Gutem und Bösem. (Ethische Sagen.)',
                                       'II. Von übler Taten Lohn.'],
              '254. Der Mann im Monde': ['C. Von allerlei Gutem und Bösem. (Ethische Sagen.)',
                                         'II. Von übler Taten Lohn.'],
              '255. Der böse Müller': ['C. Von allerlei Gutem und Bösem. (Ethische Sagen.)',
                                       'II. Von übler Taten Lohn.'],
              '256. Der Eremit auf dem Rosenberg': ['C. Von allerlei Gutem und Bösem. (Ethische Sagen.)',
                                                    'II. Von übler Taten Lohn.'],
              '257. Das versunkene Kloster': ['C. Von allerlei Gutem und Bösem. (Ethische Sagen.)',
                                              'II. Von übler Taten Lohn.'],
              '258. Woher die Pfalz ihren Namen hat': ['D. Von Schalkheit und Torheit. (Humoristische Sagen.)',
                                                       'I. Von Orts- und Spitznamen.'],
              '259. Wie vier ehemals Guttenbergische Dörfer ihre Namen erhielten': [
                  'D. Von Schalkheit und Torheit. (Humoristische Sagen.)', 'I. Von Orts- und Spitznamen.'],
              '260. Noch zwei andere Ortsnamen': ['D. Von Schalkheit und Torheit. (Humoristische Sagen.)',
                                                  'I. Von Orts- und Spitznamen.'],
              '261. Warum die Pfälzer Krischer heißen': ['D. Von Schalkheit und Torheit. (Humoristische Sagen.)',
                                                         'I. Von Orts- und Spitznamen.'],
              '262. Die Sausenheimer "Essel"': ['D. Von Schalkheit und Torheit. (Humoristische Sagen.)',
                                                'I. Von Orts- und Spitznamen.'],
              '263. Die Oppauer "Dampfnudelstürmer"': ['D. Von Schalkheit und Torheit. (Humoristische Sagen.)',
                                                       'I. Von Orts- und Spitznamen.'],
              '264. Die Friesenheimer "Eulen"': ['D. Von Schalkheit und Torheit. (Humoristische Sagen.)',
                                                 'I. Von Orts- und Spitznamen.'],
              '265. Annweilers Name und Spottname': ['D. Von Schalkheit und Torheit. (Humoristische Sagen.)',
                                                     'I. Von Orts- und Spitznamen.'],
              '266. Der Sammetärmel von Annweiler': ['D. Von Schalkheit und Torheit. (Humoristische Sagen.)',
                                                     'I. Von Orts- und Spitznamen.'],
              '267. Was der Teufel verlor': ['D. Von Schalkheit und Torheit. (Humoristische Sagen.)',
                                             'I. Von Orts- und Spitznamen.'],
              '268. Der Hofnarr von Münster': ['D. Von Schalkheit und Torheit. (Humoristische Sagen.)',
                                               'II. Von Streichen und Schwänken.'],
              '269. Der Pfarrer von Grumbach': ['D. Von Schalkheit und Torheit. (Humoristische Sagen.)',
                                                'II. Von Streichen und Schwänken.'],
              '270. Die dicke Landgräfin': ['D. Von Schalkheit und Torheit. (Humoristische Sagen.)',
                                            'II. Von Streichen und Schwänken.'],
              '271. Der Trunk aus dem Stiefel': ['D. Von Schalkheit und Torheit. (Humoristische Sagen.)',
                                                 'II. Von Streichen und Schwänken.'],
              '272. Der durstige Abt': ['D. Von Schalkheit und Torheit. (Humoristische Sagen.)',
                                        'II. Von Streichen und Schwänken.'],
              '273. Der Weinkampf zu Wachenheim': ['D. Von Schalkheit und Torheit. (Humoristische Sagen.)',
                                                   'II. Von Streichen und Schwänken.'],
              '274. Der Gescheideste': ['D. Von Schalkheit und Torheit. (Humoristische Sagen.)',
                                        'II. Von Streichen und Schwänken.'],
              '275. Des Pfalzgrafen Hirschjagd': ['D. Von Schalkheit und Torheit. (Humoristische Sagen.)',
                                                  'II. Von Streichen und Schwänken.'],
              '276. Der Reiterlud von Iggelheim': ['D. Von Schalkheit und Torheit. (Humoristische Sagen.)',
                                                   'II. Von Streichen und Schwänken.'],
              '277. Die Kugeltaufe zu Ebernburg': ['D. Von Schalkheit und Torheit. (Humoristische Sagen.)',
                                                   'II. Von Streichen und Schwänken.'],
              '278. Der pfälzische Eulenspiegel': ['D. Von Schalkheit und Torheit. (Humoristische Sagen.)',
                                                   'II. Von Streichen und Schwänken.'],
              '279. Das Eselsei': ['D. Von Schalkheit und Torheit. (Humoristische Sagen.)',
                                   'III. Vom pfälzischen Schilda.'],
              '280. Das neue Schulhaus': ['D. Von Schalkheit und Torheit. (Humoristische Sagen.)',
                                          'III. Vom pfälzischen Schilda.'],
              '281. Der englische Schneider': ['D. Von Schalkheit und Torheit. (Humoristische Sagen.)',
                                               'III. Vom pfälzischen Schilda.'],
              '282. Die Adjunkten-Wahl': ['D. Von Schalkheit und Torheit. (Humoristische Sagen.)',
                                          'III. Vom pfälzischen Schilda.'],
              '283. Wie tief ist der Brunnen?': ['D. Von Schalkheit und Torheit. (Humoristische Sagen.)',
                                                 'III. Vom pfälzischen Schilda.']}

    locs = [['Bad Dürkheim', 49.4618, 8.17236], ['Kaiserslautern', 49.41546, 7.79963], ['Speyer', 49.35, 8.4],
            ['Bliesbolchen', 49.15374, 7.11467], ['Erfweiler', 49.19618, 7.17922], ['Sponheim', 49.84496, 7.72665],
            ['Donnersberg', 49.6, 7.95], ['Frankenthal', 49.56306, 8.29083], ['Dernbach', 50.53643, 7.57683],
            ['Dernbach', 50.53643, 7.57683], ['Berwartstein', 49.10843, 7.86304], ['Dannenfels', 49.62868, 7.94355],
            ['Neustadt an der Haardt', 49.35009, 8.13886], ['Kaiserslautern', 49.41546, 7.79963],
            ['Medard a. Glan', 'NaN'], ['Biedershausen', 49.31667, 7.48333], ['Rhodt', 49.26972, 8.10778],
            ['Kottweiler', 49.48333, 7.53333], ['Münchweiler an der Alsenz', 49.55, 7.88333],
            ['Finkenbach', 49.68333, 7.75], ['Klingenmünster', 49.14056, 8.01861], ['Beilstein', 50.74796, 8.35069],
            ['Meisenheim', 49.70721, 7.66765], ['NaN', 'NaN'], ['Homburg', 48.33333, 8.85],
            ['Jägersburg', 49.69311, 8.52689], ['Niederauerbach', 49.2572, 7.39403],
            ['Neustadt an der Haardt', 49.35009, 8.13886], ['Niederauerbach', 49.2572, 7.39403],
            ['Ensheim', 49.22361, 7.1206], ['Offenbach a. Glan', 'NaN'], ['Ensheim', 49.22361, 7.1206],
            ['Ehlingen', 49.19618, 7.17922], ['Busenberg', 52.16667, 13.38333], ['Großer Stiefel', 49.25562, 7.08969],
            ['Großer Stiefel', 49.25562, 7.08969], ['Pauliner Schlößchen', 'NaN'], ['NaN', 'NaN'],
            ['Frohnerbacherhof', 'NaN'], ['Schweinschied', 49.7, 7.56667], ['Kusel', 52.22857, 12.07273],
            ['Lindelbrunn', 49.14221, 7.89975], ['Ensheim', 49.22361, 7.1206], ['Bischmisheim', 49.22158, 7.06897],
            ['Pirmasens', 49.2593, 7.60442], ['Huneberg', 51.85, 10.51667], ['Rheingrafenstein', 49.81222, 7.85995],
            ['Hagenbach', 48.36877, 8.12124], ['Harzofen', 49.26607, 7.98552], ['Erzhütten', 49.45833, 7.7324],
            ['Bad Dürkheim', 49.4618, 8.17236], ['Buhlstein', 'NaN'], ['Pirmasens', 49.2593, 7.60442],
            ['Friedrichsthal', 52.87217, 14.14723], ['Königsberg bei Wolfstein', 'NaN'], ['Bliestal', 'NaN'],
            ['Wasgenwald', 'NaN'], ['Speyer', 49.35, 8.4], ['Großer Stiefel', 49.25562, 7.08969],
            ['Buren', 51.48333, 8.56667], ['Rodenbach b. Kaisersl.', 'NaN'], ['Wartenberg', 49.5276, 7.85258],
            ['Kaiserslautern', 49.41546, 7.79963], ['Donnersberg', 49.6, 7.95], ['Rheingrafenstein', 49.81222, 7.85995],
            ['Limburg', 49.42423, 8.39049], ['Dahn', 49.08771, 7.7116], ['Burrweiler', 49.24778, 8.07833],
            ['Einöd', 47.32652, 10.2838], ['Kirchheim', 48.64683, 9.45378], ['Freilaubersheim', 'NaN'],
            ['Wolfstein', 48.72035, 13.47336], ['NaN', 'NaN'], ['Oggersheim', 49.4925, 8.36833],
            ['Sickinger Gegend', 'NaN'], ['Niederlauterbach', 48.63481, 11.64105], ['Lindelbrunn', 49.14221, 7.89975],
            ['Erlenbach b. Dahn', 'NaN'], ['Erlenbach b. Dahn', 'NaN'], ['Königsberg bei Neustadt a. H.', 'NaN'],
            ['Donnersberg', 49.6, 7.95], ['Blieskastel', 49.23724, 7.25617], ['NaN', 'NaN'],
            ['Leinsweiler', 49.18333, 8.01917], ['Speyer', 49.35, 8.4], ['Speyer', 49.35, 8.4], ['Speyer', 49.35, 8.4],
            ['Dörrenbach', 49.65869, 6.93307], ['Cyriakuskapelle', 'NaN'], ['Cyriakuskapelle', 'NaN'],
            ['Blieskastel', 49.23724, 7.25617], ['Eschringen', 49.18894, 7.10149], ['Niederhochstadt', 49.242, 8.21828],
            ['Servatiusbrunnen', 'NaN'], ['Göllheim', 49.57587, 8.01423], ['Enkenbach', 49.48333, 7.9],
            ['Speyer', 49.35, 8.4], ['Aschbach b. Kaiserslautern', 'NaN'], ['Königsberg bei Neustadt a. H.', 'NaN'],
            ['Colgenstein', 49.58692, 8.20478], ['Eschringen', 49.18894, 7.10149], ['Albersweiler', 49.21917, 8.03],
            ['Albersweiler', 49.21917, 8.03], ['Altdahn', 49.15072, 7.80347], ['Beilstein', 50.74796, 8.35069],
            ['Enkenbach', 49.48333, 7.9], ['Karlstal', 49.35582, 7.74914], ['Bayerfeld-Cölln', 'NaN'],
            ['Wachenheim', 49.42799, 8.1398], ['Disibodenberg', 49.77708, 7.70152], ['Donnersberg', 49.6, 7.95],
            ['Kirchheimbolanden', 49.66249, 8.01513], ['Dernbach', 50.53643, 7.57683], ['Börsborn', 49.43333, 7.4],
            ['Heidenburg bei Oberstaufenbach', 'NaN'], ['Fleckenstein', 'NaN'], ['Pirmasens', 49.2593, 7.60442],
            ['Großer Stiefel', 49.25562, 7.08969], ['Großer Stiefel', 49.25562, 7.08969], ['Kirkel', 49.28333, 7.23333],
            ['Kirkel', 49.28333, 7.23333], ['Pauliner Schlößchen', 'NaN'], ['Pauliner Schlößchen', 'NaN'],
            ['Frankenstein', 49.43333, 7.93333], ['Altwolfstein', 'NaN'], ['Annweiler', 49.26297, 7.86495],
            ['Kaiserslautern', 49.41546, 7.79963], ['Erzenhausen', 49.5, 7.61667], ['Finkenbach', 49.68333, 7.75],
            ['Bad Dürkheim', 49.4618, 8.17236], ['Kallbach', 50.53857, 6.55448],
            ['Heidenburg bei Oberstaufenbach', 'NaN'], ['Göllheim', 49.57587, 8.01423],
            ['Lindelbrunn', 49.14221, 7.89975], ['Altleiningen', 49.5075, 8.07333], ['Fischbach b. Hochspeyer', 'NaN'],
            ['Frankenthal', 49.56306, 8.29083], ['Donnersberg', 49.6, 7.95], ['St. Medard', 48.30311, 8.84299],
            ['Körborn', 49.56667, 7.36667], ['Frankenthal', 49.56306, 8.29083], ['Landsberg', 48.10794, 10.98205],
            ['Beilstein', 50.74796, 8.35069], ['Hochspeyer', 49.41624, 7.91226], ['Löllbach', 49.87762, 9.66691],
            ['Odernheim', 49.76511, 7.70427], ['Speyer', 49.35, 8.4], ['Donnersberg', 49.6, 7.95],
            ['Altenbaumberg', 'NaN'], ['Ebernburg', 49.81159, 7.84523], ['Hartenburg', 50.39689, 10.56353],
            ['Göllheim', 49.57587, 8.01423], ['Bergzabern', 49.21746, 8.04752],
            ['Neustadt an der Haardt', 49.35009, 8.13886], ['Schwarzerden', 49.87013, 7.53526],
            ['Einsiedel', 49.2188, 12.36174], ['Lichtenstein', 50.1647, 10.76427], ['Bad Dürkheim', 49.4618, 8.17236],
            ['Diedelkopf', 49.54655, 7.38668], ['Kreuznach', 49.82389, 7.69833], ['Disibodenberg', 49.77708, 7.70152],
            ['Blidenfeld', 'NaN'], ['Speyer', 49.35, 8.4], ['Göllheim', 49.57587, 8.01423], ['Rosentreppe', 'NaN'],
            ['Otterstadt', 49.39412, 8.47249], ['Zeiskam', 49.23278, 8.24722], ['Disibodenberg', 49.77708, 7.70152],
            ['Altheim', 48.45471, 8.63681], ['Dietrichskirchel', 'NaN'], ['Aschbach b. Kaiserslautern', 'NaN'],
            ['Bosenbach', 49.54015, 7.50549], ['Falkenburg', 50.00682, 7.85201], ['Bergzabern', 49.21746, 8.04752],
            ['Dagobertshecke', 'NaN'], ['Altenglan', 49.55, 7.46667], ['Winnweiler', 49.56667, 7.85],
            ['Mannweiler', 49.7, 7.8], ['Miesenbach', 47.77832, 12.64913], ['Niederlauterbach', 48.63481, 11.64105],
            ['Landstuhl', 49.4211, 7.53242], ['Abtstein', 49.52711, 8.78679], ['Vollmersweiler', 49.065, 8.07722],
            ['Alschbach', 49.23954, 7.23806], ['Bad Dürkheim', 49.4618, 8.17236], ['Fischbach b. Schönau', 'NaN'],
            ['Eppenbrunn', 49.11667, 7.56667], ['Battenberg', 50.96537, 8.62244], ['Dahn', 49.08771, 7.7116],
            ['Steinalb', 49.31667, 7.65], ['Marienthal', 50.03807, 7.15949], ['Hartenburg', 50.39689, 10.56353],
            ['Offenbach a. Glan', 'NaN'], ['St. Ingbert', 49.2833, 7.11667], ['Affolterloch', 'NaN'],
            ['Hohenburg', 50.31667, 9.16667], ['Karlsberg', 53.03901, 14.20304], ['Neuwolfstein', 'NaN'],
            ['Edenkoben', 49.28393, 8.12714], ['Battweiler', 49.29218, 7.47254],
            ['Hungerbrunnen bei Kaiserslautern', 'NaN'], ['Donnersberg', 49.6, 7.95], ['Donnersberg', 49.6, 7.95],
            ['Drei Züge', 'NaN'], ['Bingert', 49.78137, 7.79915], ['Bingert', 49.78137, 7.79915],
            ['Wasgenstein', 'NaN'], ['Kaiserslautern', 49.41546, 7.79963], ['Hagenau', 48.56776, 11.20512],
            ['Kaiserslautern', 49.41546, 7.79963], ['Beilstein', 50.74796, 8.35069],
            ['Kaiserslautern', 49.41546, 7.79963], ['Speyer', 49.35, 8.4], ['Germersheim', 49.2144, 8.36687],
            ['Böckelheim', 49.80891, 7.74425], ['Hartenburg', 50.39689, 10.56353], ['Göllheim', 49.57587, 8.01423],
            ['Tschifflick', 'NaN'], ['Neudahn', 49.1628, 7.75729], ['Altenbaumberg', 'NaN'], ['Altenbaumberg', 'NaN'],
            ['Ebernburg', 49.81159, 7.84523], ['Ruppertsfelsen', 'NaN'], ['Seebach', 48.40372, 8.31336],
            ['Marienstein', 51.62561, 9.9307], ['Böckelheim', 49.80891, 7.74425], ['Montfort', 49.76611, 7.76449],
            ['Altenbaumberg', 'NaN'], ['NaN', 'NaN'], ['Großer Stiefel', 49.25562, 7.08969],
            ['Enkenbach', 49.48333, 7.9], ['Aschbach b. Kaiserslautern', 'NaN'], ['Speyer', 49.35, 8.4],
            ['Trifels', 49.19662, 7.97848], ['Sembach', 50.88333, 10.45], ['Heimbach', 50.4736, 7.54447],
            ['Altleiningen', 49.5075, 8.07333], ['Ramberger Schloß', 'NaN'], ['Erfenstein', 49.35378, 8.01775],
            ['Erfenstein', 49.35378, 8.01775], ['Montfort', 49.76611, 7.76449], ['Großer Stiefel', 49.25562, 7.08969],
            ['Falkenstein', 49.96667, 6.18333], ['Spangenberg', 51.11667, 9.7], ['Beckenhof', 49.31539, 11.43754],
            ['Lauterecken', 49.64993, 7.59265], ['Lingenfeld', 49.25389, 8.33861], ['Ballweiler', 49.2038, 7.21527],
            ['Eußerthal', 49.25, 7.96667], ['Eisenberg', 51.15922, 13.68021], ['Altdorf', 49.40131, 11.33798],
            ['Speyer', 49.35, 8.4], ['NaN', 'NaN'], ['Bad Dürkheim', 49.4618, 8.17236], ['Landstuhl', 49.4211, 7.53242],
            ['Rosenberg', 49.50126, 11.74598], ['Konken', 49.5088, 7.35393], ['Forst', 53.91667, 11.7],
            ['Freckenfeld', 49.065, 8.11389], ['Lug', 51.28333, 14.55], ['NaN', 'NaN'],
            ['Sausenheim', 49.54744, 8.15769], ['Oppau', 49.51861, 8.39917], ['Friesenheim', 49.51667, 8.45],
            ['Annweiler', 49.26297, 7.86495], ['Annweiler', 49.26297, 7.86495], ['Alsenborn', 49.48333, 7.9],
            ['Dreisen', 51.2, 10.95], ['Grumbach', 49.77222, 8.99167], ['Meisenheim', 49.70721, 7.66765],
            ['Hüffelsheim', 49.81667, 7.8], ['Böckelheim', 49.80891, 7.74425], ['Limburg', 49.42423, 8.39049],
            ['Neustadt an der Haardt', 49.35009, 8.13886], ['Neustadt an der Haardt', 49.35009, 8.13886],
            ['Iagelheim', 'NaN'], ['Ebernburg', 49.81159, 7.84523], ['Bad Dürkheim', 49.4618, 8.17236], ['NaN', 'NaN'],
            ['NaN', 'NaN'], ['NaN', 'NaN'], ['NaN', 'NaN'], ['NaN', 'NaN']]

    n_book = 1
    n_universal = 42  # Start Nummer für universelle Nummer
    num_dict = {}  # ID/Nummern statt Sagennamen als key. Manche Sagen können die gleichen Titel haben, zb. einfach Nummern
    i = 0
    uid = 2442
    werkID = "Pfalz1"
    dict = {}
    for title in titles:
        group = titles[title][1]
        categorie = titles[title][
            0]  # if cat and group already in dict, replace with value[1]. Nested categories split using a symbol(f.ex. @)
        placeID = locs[i][0]
        if locs[i][1] != "NaN":
            longitude = locs[i][2]
            latitude = locs[i][1]
        else:
            longitude = 0
            latitude = 0
        # xml_id = "Elsass2." + str(n_book)
        dict[title] = [uid, werkID, n_book, title, categorie, group, placeID, longitude,
                       latitude, 7]
        # num_dict[xml_id] = dict[key]
        n_book += 1
        i += 1
        uid += 1
    # print(dict)
    # print(num_dict)

    return dict


def get_sql():
    name = "pfalz_sagen"
    # book_title = "Trier und seine Umgebung in Sagen und Liedern"
    dict = get_dict()
    # lang = "deutsch"
    return name, dict


get_dict()
